interuss/monitoring

monitoring/monitorlib/rid_v2.py
monitoring/prober/run_locally.sh

Implements step 1 of the procedure in #17

[prober] Add behavior switch between W84 and WGS84 for F3411-22a

---

build/dev/docker-compose_dss.yaml
monitoring/monitorlib/rid_v2.py
monitoring/prober/run_locally.sh

This PR implements step 5 of #17 and resolves #17

[prober] Update to DSS v0.7.0 and remove `WGS84`/`W84` behavior selection

---

monitoring/monitorlib/auth.py

The existing `ServiceAccount` `AuthAdapter` requires a service account key file to exist on the local filesystem. Care must be taken to handle this sensitive key material.
In Google Cloud, or other environments where [Application Default Credentials (ADC)](https://cloud.google.com/docs/authentication/application-default-credentials) are configured, a simpler and safer solution is to use ADC credentials via the `google-auth` library, which does not require the application to manage any key material.
This PR adds a `ServiceAccountImpersonation` `AuthAdapter` which uses these ADC credentials to impersonate a 2nd service account to finally perform the token request. The impersonation step is added to decouple the ADC account from the service account used for token exchange. For example, if …

[monitorlib] Add an AuthAdapter to impersonate a given service account

---

monitoring/mock_uss/scdsc/routes_injection.py

As per the standard:
> NOTE 13—The exception in requirements SCD0030 and SCD0050
regarding conflicts that already exist is included in recognition that not all
conflicts may be resolvable through replanning due to insufficient time or
other factors such as other operational intents or constraints in the area.
Consequently this specification does not force replanning as the sole
means to resolve the conflict. The conflict might, for example, be
addressed through tactical means such as DAA onboard the UA.

[mock_uss] Add exception to priority handling to comply with SCD0030

---

monitoring/uss_qualifier/resources/flight_planning/flight_intents_resource.py
monitoring/uss_qualifier/resources/overrides.py

A small fix following [this comment thread](https://github.com/interuss/monitoring/pull/79#discussion_r1157150260).

[uss_qualifier] apply_overrides: properly parse the new resource

---

monitoring/uss_qualifier/configurations/dev/local_test.json
monitoring/uss_qualifier/configurations/dev/netrid_v22a.yaml
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/__init__.py
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.py
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml

~~Note: this PR depends on #128. While it can already be reviewed, I am leaving it as draft until both are merged.~~

[uss_qualifier/scenarios/netrid/dss_interop] Setup execution of v22a

---

monitoring/atproxy/requests.py
monitoring/atproxy/routes_scd.py
monitoring/mock_uss/atproxy_client/daemon.py
monitoring/mock_uss/scdsc/routes_injection.py
monitoring/uss_qualifier/resources/flight_planning/flight_planner.py
monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
requirements.txt

This PR revs the uas_standards package from v1.3.0 to v2.0.0.

Update to uas_standards v2.0.0

---

monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss_interoperability.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.md

Note that I'm not 100% sure this is the right approach for this requirement, which appears basically equivalent to DSS0130 in terms of testing to me, so I'm welcoming any feedback.

[uss_qualifier/rid/dss_interop] Add requirement DSS0070 to existing checks

---

monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md

I merged #194 without syncing properly which left some autogenerated files un-regenerated -- this is causing post-merge CI to fail.  This PR should fix that issue.  The contents of this PR were generated merely by running `make format` on head.

[uss_qualifier] Fix out-of-sync autogenerated files

---

monitoring/uss_qualifier/scenarios/documentation/parsing.py

[uss_qualifier/scenarios/documentation] Allow additional checks when a step is linked

---

monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html

This PR improves the look and feel of the tested requirements artifact via CSS and HTML structure updates.  Importantly, the header and large-rowspan cell content stick to the top of the screen giving the user more context for the information they're seeing.

[uss_qualifier] Improve tested requirements CSS

---

monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md

Add on the recently added NET0470 to check for NET0450 by comparing the observed data with the injected one.

[uss_qualifier] Add consistency/recency checks for NET0450 (observed data == injected data)

---

monitoring/uss_qualifier/README.md

This PR fixes a common problem new developers experience by improving documentation.

[docs] Add submodule initialization documentation

---

monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html
monitoring/uss_qualifier/reports/tested_requirements.py

This PR implements a small user request to include a list of other test participants in the tested_requirements summary.

[uss_qualifier/tested_requirements] Add other participants to tested_requirements summary

---

monitoring/uss_qualifier/reports/tested_requirements.py

This PR makes a small fix to a bug noticed during usage.

[uss_qualifier] Fix bug in tested_requirements with in-configuration suite definitions

---

monitoring/monitorlib/rid_v2.py
monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
monitoring/uss_qualifier/configurations/dev/library/validation.yaml
monitoring/uss_qualifier/reports/validation/definitions.py
monitoring/uss_qualifier/reports/validation/report_validation.py
monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py
monitoring/uss_qualifier/scenarios/astm/netrid/store_flight_data.py
schemas/monitoring/uss_qualifier/reports/validation/definitions/EachElementCondition.json
schemas/monitoring/uss_qualifier/reports/validation/definitions/TestScenarioApplicability.json
schemas/monitoring/uss_qualifier/reports/validation/definitions/ValidationCriterionApplicability.json

This PR resolves #307 and the bugs previously hidden by not failing validation when execution errors were present.

[uss_qualifier] Fix execution error validation and hidden bugs

---

monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py

[uss_qualifier] Fix operator location check with unspecified location

---

monitoring/monitorlib/geotemporal.py
requirements.txt

With implicitdict 2.3.0, classes that inherit lists can be simplified.  This PR updates to 2.3.0 and simplifies two classes like this.

[uss_qualifier] Simplify collections

---

build/dev/docker-compose.yaml

This version incorporates fixes we need wrt down USS mechanism.

[CI/build] Bump DSS version used to 0.9.0-rc1

---

monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py

This also removes a few unhelpful log statements that were remaining.

[uss_qualifier] remove a noisy log statement from the subscription_simple scenario

---

monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py

relates to #368
Accesses the correct object attributes when reaching an error path. Those changes work on my local env but I've not gone further in terms of test/formatting.

[uss_qualifier] Fix error raising exception in uss_qualifier on some error paths

---

monitoring/monitorlib/infrastructure.py
monitoring/prober/rid/v1/test_isa_simple_heavy_traffic_concurrent.py
monitoring/prober/scd/test_operation_simple_heavy_traffic_concurrent.py

[uss_qualifier] AsyncUTMTestSession's query functions also return headers

---

monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md
monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py

See https://github.com/interuss/monitoring/pull/383#discussion_r1423092090

[uss_qualifier/utm/down_uss] Remove 'low-priority' wording about Flight 1

---

monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md

[uss_qualifier/scenarios/utm/down_uss] Add validation of op intent not shared

---

monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py

[uss_qualifier/scenarios/utm/down_uss] Fix check for op intent managing USS

---

monitoring/uss_qualifier/scenarios/astm/utm/dss_interoperability.md
monitoring/uss_qualifier/scenarios/astm/utm/dss_interoperability.py
monitoring/uss_qualifier/suites/astm/utm/dss_probing.yaml

I had a note to myself to properly fix the availability check:
As we've just added a `planningResource` I also included it so we're searching for an area the DSS is responsible for.

[uss_qualifier] properly check dss availability in dss_interoperability scenario

---

build/dev/docker-compose.yaml

Update to `interuss/dss/v0.10.0-rc1`

[ci/dev] update the dss image to latest released version

---

monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py

This adds to `submit_flight` a validation that the expected results both for success or failure do not overlap. 
This mimics what was done for `submit_flight_intent` in #411.
(this also enhances slightly the readability of the function)
Helps in addressing #398

[uss_qualifier/flight_planning/submit_flight] Guard against invalid input; Enhance readability

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.py

Fix some leftover remarks from #469 
(With the exception of mentioning where the subscription validation code is: that's being added in #490)

[qualifier] small fixes for subscription_simple

---

build/dev/docker-compose.yaml

Bump DSS version to latest release.

[misc] update dss version to v0.11.0-rc1

---

monitoring/prober/scd/test_operations_simple.py

The next DSS release will allow the creation of operational intent references that don't specify a subscription or a base USS url, if the OIR state is 'ACCEPTED'.
This requires an adaptation of a prober test that: the request still fails but with a different error code.

[prober] adapt test_operations_simple for next DSS version

---

monitoring/monitorlib/fetch/__init__.py
monitoring/monitorlib/scd.py

Utility function to generate an `ExchangeRecord` from a `Query`. 
Updates some functions on `Query` to help with that.

[monitorlib] Add scd.make_exchange_record

---

monitoring/mock_uss/f3548v21/flight_planning.py
monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.md
monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
monitoring/uss_qualifier/test_data/flight_intents/standard/invalid_flight_intents.yaml

Do note that only the last commit (aa6b717cb9229d9ead54ba53ae280b4282d53193) is part of this PR, as it sits on top of #554

[uss_qualifier/utm/flight_intent_validation] Add intent recently ended test step

---

monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py

The message would end up missing the first part.

[uss_qualifier/flight_planning] Fix check details generation

---

monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/receive_notifications_for_awareness/receive_notifications_for_awareness.md
monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/receive_notifications_for_awareness/receive_notifications_for_awareness.py
monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
monitoring/uss_qualifier/test_data/flight_intents/standard/non_conflicting.yaml

cc FYI @punamverma 
I believe this should be enough to finalize coverage of SCD0080 for Q1 deadline.

[uss_qualifier/scenarios/utm/receive_notifications_for_awareness] Add modification while activated case

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.py

Add mutation to the OIR sync scenario

[uss_qualifier] check mutated OIRs properly propagate to every DSS (dss0210,2a-f slice 2/n)

---

monitoring/prober/infrastructure.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.py

- expose some functions and variables outside of the class/file
- remove step checking for absence of non-intersecting subscriptions ([c.f. this discussion](https://github.com/interuss/monitoring/pull/597#discussion_r1537717678))
- remove background subscription 2 (not needed anymore)
- refactor code flow to prepare upcoming changes
- add missing recording of queries
- some additional cleanups

[uss_qualifier/scenarios/utm/dss/subscription_interactions] Cleanup scenario

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/read_correct.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/read_query.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/search_correct.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/search_query.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/sync.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/validators/oir_validator.py
monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
monitoring/uss_qualifier/suites/faa/uft/message_signing.md
monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
monitoring/uss_qualifier/suites/uspace/flight_auth.md
monitoring/uss_qualifier/suites/uspace/required_services.md

Search for OIRs across all DSSes to confirm their extents are properly synced. 
Note that:
- reorganized slightly the code flow for clarity
- removed some validation checks that were making the flow more complex (those are not needed in this scenario)
- split some "CRUD" checks

[uss_qualifier/scenarios/utm/dss/OIRSynchronization] DSS0210,2e: check OIR area propagation

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/sub/crud/__init__.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions_deletion.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/subscription_synchronization.py

- Add a function implementing the test step fragment
- Replace many duplicated implementatons
- Use fragment in a scenario
Helps with #601: one of the cleaned up checks did not specify a participant.

[uss_qualifier/scenarios/utm/dss/fragments/sub/create_query] Add check function and harmonize callsites

---

monitoring/monitorlib/fetch/__init__.py

mock_uss has been observed very occasionally failing calls to a hosted DSS instance with a ConnectionError indicating that the remote host closed the connection without responding, but the DSS logs indicate a successful response to the client.  This seems likely to be correctable upon retry, so this PR adds that specific error to the types of errors that can have retry attempts in query_and_describe.

[monitorlib] Retry certain ConnectionErrors

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/sub_api_validator.py

Progress on #601 for proper check attribution.

[uss_qualifier] properly attribute SCD subscription authentication checks

---

.github/workflows/ci.yml
.github/workflows/monitoring-test.yml

This new version is supposedly faster.

[CI] Upgrade (upload|download)-artifact GH action to v4

---

monitoring/uss_qualifier/resources/flight_planning/flight_intent_validation.py

PR stacked on top of #660: please review only commit 59988e33ac86087b49994352cd3007313a867552

[uss_qualifier/ressources/flight_intent_validation] Add computation of extents to validate_flight_intent_templates

---

monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_flight_intent.md
monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py

PR stacked on top of #661: please review only commit e27881bdcdbe1e27e0e66aa2e9d989feafaa0f38
Note that it also enhances the corresponding .md file.

[uss_qualifier/scenarios/flight_planning] Add modify_activated_flight

---

monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py

PR stacked on top of #662: please review only commit a52a20e8929b8ee63e9c48bd51d8918e2629492f

[uss_qualifier/scenarios/utm/OpIntentValidator] Enable computing extents from FlightInfo

---

monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.md
monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py

~~PR stacked on top of #663: please review only commit 0355cbd11753bd284732f30bfbe7cfb5b4b4fbb6~~ rebased

[uss_qualifier/scenarios/utm/flight_intent_validation] Migrate scenario away from FlightIntent

---

monitoring/uss_qualifier/scenarios/flight_planning/delete_flight_intent.md
monitoring/uss_qualifier/scenarios/flight_planning/modify_planned_flight_intent.md

~~PR stacked on top of #666: please review only commit c15767ac9fa9c7c0b4d02151caa21ca80cf8e038~~ rebased

[uss_qualifier/scenarios/flight_planning] Add severity to fragments modify_planned_flight_intent and delete_flight_intent

---

monitoring/monitorlib/clients/flight_planning/client_scd.py

See note in code for additional context.

[monitorlib/clients/flight_planning/client_scd] Assume correct USS behavior in API translation layer for off-nominal flights

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_state_transitions.py

See https://github.com/interuss/monitoring/issues/699#issuecomment-2161025755 for context.
This credits the DSS user participants to the validation of the SCD0100 requirement.

[uss_qualifier/scenarios/utm/dss/op_intent_ref_state_transitions] Credit SCD0100 to DSS user participants

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/read_correct.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/read_query.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/sync.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/validate/mutated.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/validate/non_mutated.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/constraint_ref_synchronization.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/constraint_ref_synchronization.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/validators/cr_validator.py
monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
monitoring/uss_qualifier/suites/faa/uft/message_signing.md
monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
monitoring/uss_qualifier/suites/uspace/flight_auth.md
monitoring/uss_qualifier/suites/uspace/required_services.md

Expand the constraint references sync scenario to verify that a constraint reference is propagated to every configured DSS.

[uss_qualifier] constraint references: check created references are synced - 2/n

---

monitoring/monitorlib/schema_validation.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/search_correct.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/search_query.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/sync.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/constraint_ref_synchronization.md
monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/constraint_ref_synchronization.py
monitoring/uss_qualifier/scenarios/astm/utm/dss/validators/cr_validator.py
monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
monitoring/uss_qualifier/suites/faa/uft/message_signing.md
monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
monitoring/uss_qualifier/suites/uspace/flight_auth.md
monitoring/uss_qualifier/suites/uspace/required_services.md

Adds constraint reference search to the synchronization scenario.

[uss_qualifier] constraint reference sync: check created references can be searched - 3/n

---

monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
monitoring/uss_qualifier/configurations/dev/library/resources.yaml
monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/baseline.libsonnet
monitoring/uss_qualifier/resources/astm/f3411/dss.py
monitoring/uss_qualifier/resources/dev/test_exclusions.py
monitoring/uss_qualifier/resources/netrid/observers.py
monitoring/uss_qualifier/resources/netrid/service_providers.py
monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.md
monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.py
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.py
monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
monitoring/uss_qualifier/suites/interuss/dss/all_tests.yaml
schemas/monitoring/uss_qualifier/resources/astm/f3411/dss/DSSInstanceSpecification.json
schemas/monitoring/uss_qualifier/resources/dev/test_exclusions/TestExclusionsSpecification.json
schemas/monitoring/uss_qualifier/resources/netrid/observers/ObserverConfiguration.json
schemas/monitoring/uss_qualifier/resources/netrid/service_providers/ServiceProviderConfiguration.json

Second and last part of addressing #739

[uss_qualifier] Replace local_debug by new field allow_cleartext_queries in resource TestExclusionResource

---

monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.md

Stacked on top of #755, please consider only commit 5f20840a15ad573ea4626a7f211fd0c01bfa4d4f.

[uss_qualifier/scenarios/netrid/aggregate_checks] Specify severity through .md doc

---

monitoring/monitorlib/clients/scd.py

The mock_uss was incorrectly requesting the CMSA scope even when it was not required for the state about to be submitted.
This PR ensures that the CMSA scope is only requested for creation and update to non-conformant states, allowing the mock_uss to run in an environment where CMSA is not enabled at all.
Close #787

[mock_uss] OIR creation selects the proper scope for the requested state

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/uss_availability_synchronization.py

[uss_qualifier] scd: USS availability sync attributes failed query to target DSS only

---

monitoring/uss_qualifier/scenarios/astm/utm/dss/dss_interoperability.py

[uss_qualifier] scd: dss-interop properly handles hostnames that fail to resolve

---

monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
monitoring/uss_qualifier/suites/uspace/network_identification.md
monitoring/uss_qualifier/suites/uspace/required_services.md

[uss_qualifier] netrid: net0260 - check SP properly reports vertical speed

---

monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
monitoring/uss_qualifier/suites/uspace/network_identification.md
monitoring/uss_qualifier/suites/uspace/required_services.md

[uss_qualifier] netrid: net0260 check SP reports correct speed

---

monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
monitoring/uss_qualifier/suites/uspace/network_identification.md
monitoring/uss_qualifier/suites/uspace/required_services.md

[uss_qualifier] netrid: net0260 - check SP correctly reports speed accuracy

---

monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
monitoring/uss_qualifier/suites/uspace/network_identification.md
monitoring/uss_qualifier/suites/uspace/required_services.md

[uss_qualifier] netrid: net0260 - check SP correctly reports track

---

monitoring/monitorlib/fetch/rid.py
monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
monitoring/uss_qualifier/suites/uspace/network_identification.md
monitoring/uss_qualifier/suites/uspace/required_services.md

[uss_qualifier] netrid: net0260 - check observed vertical accuracy is as expected

---

monitoring/mock_uss/riddp/routes_observation.py

The `mock_uss` will now report the horizontal and vertical accuracy as specified on flight injection.

[mock_uss/observation-api] populate most recent position's horizontal and vertical accuracy

---

monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py

Add base generic unit test for the generic evaluator.

 [uss_qualifier/scenarios/netrid/nominal_behavior] Generic unit tests 

---

monitoring/monitorlib/fetch/__init__.py
monitoring/uss_qualifier/resources/netrid/service_providers.py
schemas/monitoring/monitorlib/fetch/Query.json

Required for scenarios that are being built for Net0030/Net0040

[uss_qualifier] NetRIDServiceProvider function for querying user notifications

---

monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validator.py
monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/delete_isa.md
monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/get_isa.md
monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/put_isa.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/delete_isa.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/get_isa.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/put_isa.md

[uss_qualifier] NetRID: migrate some severities to markdown documentation

---

requirements.in
requirements.txt

This PR addresses a Dependabot finding by upgrading our `requests` dependency and running `make requirements.txt`.

[security] Upgrade requests dependency

---

monitoring/uss_qualifier/resources/netrid/simulation/kml_flights.py

This PR add vertical speed, generated from altitude.
It's arbitrarily rounding to 0.25 increments to have nice numbers (I think the specs doesn't precise anything ?).
This fix #943

[uss_qualifier/resources/netrid/simulation/kml_flights] generate vertical speed

---

monitoring/uss_qualifier/scenarios/scenario_test/utils.py

This PR follow #961 and contribute to testing of uss_qualifier's scenario.py. You may want to review only the last commit.
This PR adds a set of helpers functions that will be used in future PRs for testing. It has been isolated there for easier reviews.

[uss_qualifier] Units tests for scenario.py: utils 

---

monitoring/uss_qualifier/scenarios/scenario_test/functions_test.py

This PR follow #962 and contribute to testing of uss_qualifier's scenario.py. You may want to review only the last commit.
This PR add tests on the single functions found in scenario.py.  It has been isolated there for easier reviews.

 [uss_qualifier] Units tests for scenario.py: simple functions 

---

monitoring/uss_qualifier/scenarios/scenario_test/pendingcheck_test.py

This PR follow #963  and contribute to testing of uss_qualifier's scenario.py. You may want to review only the last commit.
This PR add tests on the PendingCheck class found in scenario.py.  It has been isolated there for easier reviews.

 [uss_qualifier] Units tests for scenario.py: PendingCheck 

---

monitoring/uss_qualifier/scenarios/scenario_test/generic_test_scenario_test.md
monitoring/uss_qualifier/scenarios/scenario_test/generic_test_scenario_test.py
monitoring/uss_qualifier/scenarios/scenario_test/generic_test_scenario_without_cleanup.md
monitoring/uss_qualifier/scenarios/scenario_test/generic_test_scenario_without_cleanup.py

This PR follow #964  and contribute to testing of uss_qualifier's scenario.py. You may want to review only the last commit.
This PR add tests on the GenericTestScenario class found in scenario.py.  It has been isolated there for easier review, but it's the most complex and long one.

 [uss_qualifier] Units tests for scenario.py: GenericTestScenario 

---

monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight_details.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight_details.md
monitoring/uss_qualifier/scenarios/documentation/checks_without_severity.json

[uss_qualifier] Move severity checks of common_dictionary_evaluator to the documentation

---

monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_simple.py
monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_simple.md
monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/search_isas_miss.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_simple.md
monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/search_isas_miss.md
monitoring/uss_qualifier/scenarios/documentation/checks_without_severity.json

Also updates the deletion step to check for ISA content
Part of the effort on #975

[uss_qualifier] isa_simple search test steps now validate ISA content

---

monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.md
monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
monitoring/uss_qualifier/scenarios/documentation/checks_without_severity.json
monitoring/uss_qualifier/scenarios/flight_planning/prep_planners.py
monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
monitoring/uss_qualifier/scenarios/versioning/get_system_versions.md
monitoring/uss_qualifier/scenarios/versioning/get_system_versions.py

Contrib to #404
Note that most of them in that PR already had severity in documentation and therefore where only removed from the code.

[uss_qualifier] Move various severity checks in documentation

---

requirements.in
requirements.txt

Upgrade implicitdict to 3.0.0

---

Makefile
build/dev/docker-compose.yaml
monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
monitoring/uss_qualifier/configurations/dev/uspace.yaml
monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/baseline.libsonnet
monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
monitoring/uss_qualifier/scenarios/astm/utm/make_uss_report.md
monitoring/uss_qualifier/scenarios/astm/utm/make_uss_report.py
monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
monitoring/uss_qualifier/suites/faa/uft/message_signing.md
monitoring/uss_qualifier/suites/uspace/flight_auth.md
monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
monitoring/uss_qualifier/suites/uspace/required_services.md
monitoring/uss_qualifier/suites/uspace/required_services.yaml

This PR documents and implements a test for makeUssReport per #987.

[uss_qualifier] Add makeUssReport test

---

monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py

Small PR to address comment in #972 :)

[dev] Fix docstring's PEP257 from #972

---

monitoring/mock_uss/logging.py

This PR try to avoid errors when mock_uss try to log things outside of a log request.
I was not able to reproduce the error, but it has been reported in #991
The new behavior is not to log those entry, but we could also log them 'just in case'.

[mock_uss] ignore logging outside of request context

---

monitoring/monitorlib/fetch/__init__.py

This PR adds to `fetch` a feature to immediately fail without any actual attempt queries for network locations identified as fake. The default setting for that is set to *testdummy.interuss.org*.
Hopefully this change will address #991 (see https://github.com/interuss/monitoring/issues/991#issuecomment-2743201011).

[monitorlib/fetch/query_and_describe] Immediately fail queries targetting fake network locations

---

monitoring/mock_uss/riddp/routes_riddp_v19.py
monitoring/mock_uss/riddp/routes_riddp_v22a.py

This PR fixes #1010 by fixing function names on the dp side.

[mock_uss] Fix duplicate function name between ridsp and riddp

---

test/repo_hygiene/pyproject.toml
test/repo_hygiene/uv.lock

* Remove constrains about repo_hygiene dependencies  ([UV take care of that for us](https://docs.astral.sh/uv/concepts/projects/sync/#upgrading-locked-package-versions))
* Upgrade to latests versions

 [tooling] Upgrade repo_hygiene dependencies to the latest version 
