interuss/monitoring

- monitoring/prober/run_locally.sh
Discovered in [this `dss` PR](https://github.com/interuss/dss/pull/938), prober's run_locally.sh would actually succeed (exit with code 0) when the probing itself failed.  This PR fixes that problem in this repository.
> [prober] Ensure probing indicates error on failure

- monitoring/uss_qualifier/configurations/dev/f3548.json
- monitoring/uss_qualifier/configurations/dev/faa/uft/f3548.yaml
- monitoring/uss_qualifier/configurations/dev/non_docker/resources.yaml
- monitoring/uss_qualifier/configurations/dev/resources.yaml
- monitoring/uss_qualifier/fileio.py
- monitoring/uss_qualifier/test_data/usa/kentland/flight_intents/conflicting_flights.yaml
- monitoring/uss_qualifier/test_data/usa/kentland/flight_intents/priority_preemption.yaml
Currently, we only have one dataset used for testing functionality related to flight planning -- it is labeled "CHE", but actually has operational intents in Ethiopia due to a reversal of latitude and longitude.  In preparation for use of InterUSS in FAA's UTM Field Trials (UFT), this PR adds an additional set of flight intents reflective of the Mid-Atlantic Aviation Partnership (MAAP) involvement in this activity.  The two primary files added by this PR are monitoring/uss_qualifier/test_data/usa/kentland/flight_intents/*.yaml, plus a configuration file to use these flight intents at monitoring/uss_qualifier/configurations/dev/faa/uft/f3548.yaml.
The configurations.dev.resources.yaml file is also restructured to differentiate between F3548 resources for CHE versus USA, which uncovered a …
> [uss_qualifier] Add Kentland Farms flight intents

- monitoring/mock_uss/scdsc/routes_injection.py
- monitoring/monitorlib/scd_automated_testing/scd_injection_api.py
Based on my understanding of the SCD injection API, 
The implementation of the SCD injection API in the mock USS seems to be lacking a result type: `ReadyToFly`.
If my understanding is correct, this result must be returned when the operational intent is in the state `Activated`.
This PR adds the injection result type to the enum and returns it when the operational intent is in the `Activated`.
PS: I'm not yet quite used to the testing codebase (nor Python), so there is high probability that for my first PRs I do things ignoring some context, so please don't hesitate with the feedback.
> [mock_uss] SCD flight injection: return ReadyToFly result when OpIntent is Activated

- monitoring/mock_uss/Makefile
- monitoring/monitorlib/Makefile
- monitoring/uss_qualifier/Makefile
Those fail if the local paths have spaces in them.
> Quote arguments in Makefile

- .github/workflows/ci.yml
- Makefile
- monitoring/uss_qualifier/scripts/test_docker_fully_mocked.sh
This PR enhances the CI by saving as artifacts the logs of the containers and of the tracer.
This will be useful for debugging issues, e.g. the timeout issue that sometimes happen in the CI.
[See for example this run](https://github.com/interuss/monitoring/actions/runs/4084261787):
> [CI] Collect local logs and upload them as CI run artifacts

- monitoring/uss_qualifier/configurations/personal/.gitignore
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
An important piece of information missing from previous failed check messages when attempting to inject user flight intents was what the expected result was.  This PR adds that information while simplifying check message generation and cleaning up a few other small items.
> [uss_qualifier] Improve flight injection failed check messages

- monitoring/mock_uss/atproxy_client/daemon.py
- monitoring/monitorlib/clients/scd.py
- monitoring/monitorlib/fetch/__init__.py
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/resources/flight_planning/flight_planner.py
- monitoring/uss_qualifier/resources/interuss/mock_uss.py
- monitoring/uss_qualifier/resources/netrid/observers.py
- monitoring/uss_qualifier/resources/netrid/service_providers.py
Currently, failure to query a flight planner that results in an exception (e.g., a timeout exception) will not report information about the attempted query because the exception will jump immediately up to the scenario exception handler.  This means #28 is hard to diagnose as information about the query that times out is not available anywhere.  This PR addresses that issue by performing the flight planner queries with `fetch.query_and_describe` which captures exceptions, now including timeouts, gracefully so that the query information can be included in the report.
This replacement of query-then-describe_query with query_and_describe is repeated in most other places to provide the same resiliency to query errors in other locations as well.
Finally, some additional logging is added to the …
> [uss_qualifier] Improve query error handling

- monitoring/mock_uss/tracer/context.py
- monitoring/mock_uss/tracer/routes.py
- monitoring/monitorlib/clients/scd.py
- monitoring/monitorlib/fetch/__init__.py
- monitoring/monitorlib/fetch/rid.py
- monitoring/monitorlib/fetch/scd.py
- monitoring/monitorlib/mutate/rid.py
- monitoring/monitorlib/mutate/scd.py
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/resources/netrid/observers.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
- monitoring/uss_qualifier/test_data/che/netrid/circular_flights.json
- requirements.txt
When the "fetch" mechanisms in monitorlib were written a long time ago, the implicitdict tool was not yet available.  To provide semantic interpretation and expectations around dict content, "fetch" objects simply inherit dict and provide methods to interact with that data.  This PR improves on that older paradigm by migrating "fetch" objects to ImplicitDicts so that the expected data contract can be validated and field usage easily traced in an IDE.  The "coerce" method is replaced by ImplicitDict.parse, which includes validation logic.
An implicitdict update supports consistent StringBasedDateTime datetime representations (naive vs timezone-aware) and causes the circular_flights.json generated file to be updated.
> [monitorlib] Convert fetch objects to ImplicitDicts

- monitoring/atproxy/app/__init__.py
- monitoring/atproxy/handling.py
- monitoring/atproxy/routes.py
- monitoring/atproxy/routes_handler.py
- monitoring/atproxy/routes_rid_injection.py
- monitoring/atproxy/routes_rid_observation.py
- monitoring/atproxy/routes_scd.py
- monitoring/mock_uss/atproxy_client/daemon.py
- monitoring/monitorlib/fetch/__init__.py
- monitoring/uss_qualifier/scenarios/definitions.py
This PR attempts to improve #28 by enhancing logging in atproxy and logging but not failing in atproxy_client's daemon when a query to atproxy fails.  This PR is not expected to resolve the problem as the root cause of atproxy_client's call to atproxy timing out has not been addressed (or identified).
Also, it turns out MappingProxyType was not a good substitute for an immutable dict as it is not serializable.  This PR also fixes that problem with an equivalent behavior.
> [atproxy] Improve atproxy logging and reduce atproxy_client daemon failures

- monitoring/atproxy/gunicorn.conf.py
- monitoring/atproxy/start.sh
- monitoring/mock_uss/gunicorn.conf.py
- monitoring/mock_uss/ridsp/routes_injection.py
- monitoring/mock_uss/server.py
- monitoring/mock_uss/tracer/context.py
- monitoring/mock_uss/tracer/routes.py
- monitoring/monitorlib/fetch/rid.py
- monitoring/monitorlib/mutate/rid.py
- monitoring/monitorlib/rid_v2.py
- requirements.txt
This PR completes the work started by #39 to improve monitorlib's standards-based interactions to support both versions of F3411 RID by updating the mutation objects/operations to the new model.
I noticed that a pattern in the fetch objects was more verbose than necessary (parsing and catching parsing exceptions for version-specific values in two places), so the fetch objects are updated with the new pattern along with the mutate objects.  Also, v19 and v22 class fields were shadowing the namespaces of the same names, so those fields were renamed *_value instead.
A number of error messages are added or improved to help with debugging.
In the quest against #28, some gunicorn server hooks are added to both atproxy and mock_uss to assist determining where and why the timeouts are occurring. …
> [monitorlib] Make RID mutation operations version-independent

- monitoring/uss_qualifier/requirements/interuss/automated_testing/rid.md
- monitoring/uss_qualifier/requirements/interuss/automated_testing/rid/observation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
Currently, RID testing in uss_qualifier matches observed flights to expected/injected flights using the observed flight ID.  This is not a reliable method as Display Providers are free to identify flights to their Display Applications with any IDs they see fit, and these IDs do not need to match the IDs specified by the Service Provider.  This PR addresses that issue described in #4 by matching flights by precise 2D position rather than flight ID.  Since Service Providers report actual telemetry when available, latitudes and longitudes should match exactly with the injected telemetry.  To make identification easier, this PR also imposes the constraint that a (lat,lng) 2D position may not appear twice across all injected telemetry.
This PR should resolve #4 to the extent possible with the …
> [uss_qualifier] Match RID flights by 2D position

- monitoring/monitorlib/kml.py
- monitoring/uss_qualifier/configurations/dev/faa/uft/uft.yaml
- monitoring/uss_qualifier/reports/graphs.py
- monitoring/uss_qualifier/resources/netrid/simulation/kml_flights.py
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
- monitoring/uss_qualifier/suites/definitions.py
- monitoring/uss_qualifier/suites/suite.py
- monitoring/uss_qualifier/test_data/usa/kentland/rid.kml
Originally, uss_qualifier accepted just a test suite name in the configuration to define what to run.  This was later expanded to specification of a test suite action (a test suite, test scenario, or action generator) to support running a specific scenario rather than suite.  This PR takes this generalization one step further and enables full definition of a test suite within a configuration file -- this will allow full flexibility for how users define what tests they want to run.
An example configuration (uft.yaml) is added, along with a new injectable RID file (rid.kml), to demonstrate this capability (and also further UFT).
Some fixes were necessary in the KML -> NetRID test data conversion code.
> [uss_qualifier] Add in-configuration suite definitions

- monitoring/monitorlib/fetch/rid.py
- monitoring/uss_qualifier/configurations/dev/faa/uft/uft.yaml
- monitoring/uss_qualifier/reports/report.py
- monitoring/uss_qualifier/resources/astm/f3411/dss.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
- monitoring/uss_qualifier/scenarios/scenario.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
Currently, the RID nominal behavior test is completely independent of which RID standard is used because it only tests whether injections cause observations.  The down side of this approach is that the responsible party (between the Service Provider and Display Provider) cannot easily be assigned.  This PR adds an optional feature to that scenario that will cause uss_qualifier to directly query the DSS and Service Provider when DSS information is provided.  The responses to these queries are checked first before the end-to-end observation is performed.
> [uss_qualifier] Directly query Service Providers in RID nominal behavior test

- scripts/git/upstream_owner.sh
This PR should resolve #13 by improving upstream owner detection when an upstream of `origin` is not defined.
> Improve upstream owner detection

- monitoring/monitorlib/rid.py
- monitoring/monitorlib/schema_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md
- requirements.txt
This PR adds schema validation capability to read an OpenAPI specification and then validate JSON data against an object schema defined in that specification.  This capability is used to check schema compliance for responses to /flights and flight details queries in F3411-19 RID (included in continuous integration tests) and F3411-22a RID (checked once manually for this PR), as well as operational intent details in F3548-21 SCD.  Two remaining errors were found in the F3411-19 API and fixed in the upstream submodule repo, then the submodule pointer updated in this PR.  Likewise 1 error found and corrected in F3548-21 API (UUIDv4 regex).
> [uss_qualifier] Add canonical schema compliance checks

- monitoring/mock_uss/riddp/routes_observation.py
- monitoring/mock_uss/ridsp/routes_injection.py
- monitoring/monitorlib/fetch/rid.py
- monitoring/uss_qualifier/resources/netrid/service_providers.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/injection.py
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.py
This PR addresses a number of issues encountered while conducting remote ID automated tests:
* Validates received Flight information before attempting to use it in mock_uss to produce clear error messages rather than internal errors
* Fixes DeleteTest endpoint in mock_uss to use missing version in path
* Fixes uss_qualifier to include version in path when calling DeleteTest endpoint
* Records injected test information rather than just injected flights in uss_qualifier
* Validates presence of position information before attempting to use it in uss_qualifier RID display data evaluator
> [uss_qualifier, mock_uss] Fix rid automated testing

- monitoring/mock_uss/ridsp/routes_ridsp_v22a.py
- monitoring/uss_qualifier/reports/report.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/nominal_behavior.md
- monitoring/uss_qualifier/test_data/usa/kentland/rid.kml
This PR fixes the altitude check in the RID nominal behavior scenario (checking that reported altitude matches injected altitude).  The previous implementation was wrong in a number of ways and this approach is substantively different.  The check is now performed separately for the uss_qualifier observation of the Service Provider under test and the observation from the Display Provider under test.
Service Providers that pass the checks for uss_qualifier's direct observation are also assumed to not be at fault for failed checks related to unexpected observations from a Display Provider under test.
Some terminology is clarified (dp_observation was originally meant to convey "observation made by uss_qualifier as the Display Provider", but that was hard to distinguish from "observation of …
> [uss_qualifier] Fix RID altitude check

- .github/workflows/CI.md
- .github/workflows/ci.yml
- .gitignore
- monitoring/Makefile
- monitoring/prober/Makefile
- monitoring/prober/run_locally.sh
- monitoring/prober/scripts/test_docker_fully_mocked.sh
This PR adds the prober to the CI checks. I took the opportunity to rename the report so it clarifies the project it belongs to.
This requires an update of the DSS repository when published.
Note that the PR #63 will have to be merged first to successfully pass the check.
> [ci][prober] Run prober in CI and capture report as artifact

- monitoring/uss_qualifier/resources/flight_planning/flight_intents_resource.py
- monitoring/uss_qualifier/test_data/usa/kentland/flight_intents/conflicting_flights.yaml
#73 introduced the very useful concept of named flight intent resources that could be defined like "same as X flight intent, but with these changes".  However, the timestamp updates (changing the timestamps to be relative to the current time rather than reference_time) were applied unconditionally after constructing the flight intent.  This meant that if flight intent X were loaded, the timestamp correction would be applied and produce a valid flight intent.  But, if flight intent Y were defined as "same as flight intent X, except these changes", the timestamp correction would again be applied to the timestamps of already-corrected flight intent X.
This PR solves that problem by determining the appropriate fields to which timestamp correction should be applied (all time_start and time_end …
> [uss_qualifier] Fix delta flight intents

- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning_priority/nominal_planning_priority.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
This allows using different participant IDs than "uss1" and "uss2" in test scenarios implementation.
> [uss_qualifier] in validate_shared_op_intent: pass USSs and DSS as parameters of function

- monitoring/uss_qualifier/resources/flight_planning/flight_intents_resource.py
Perfectly valid flight intents would be considered invalid due to this issue.
> [uss_qualifier] fix parsing of delta flight intents

- monitoring/uss_qualifier/resources/flight_planning/flight_intents_resource.py
This reverts the fix implemented in #79 and fixes the issue differently. The issue was that a mutation of the `reference_time` would not be taken into account, as in, with a mutated `reference_time` the times would not be shifted.
This PR fixes this by iterating an additional time on the processed flight intents to shift properly all the times after all the deltas are resolved.
> [uss_qualifier] Split flight intents processing in two steps

- .editorconfig
In the repo, all the `*.json`, `*.yml`  and others files have an indent of size 2. It seems that only `*.py` files actually have an indent of size 4. So this change should normally reflect the actual practices of the repo.
> [.editorconfig] Set default indent size to 2 except for .py files

- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md
Update after feedback: add validation of the OPIN0025 requirement on some checks (if "1) the operational intent reference isn't found in the DSS or 2) the operational intent details aren't obtainable or accurate").
The additional part (i.e. "the intent of the original check [...] is to make sure the operational intent actually shared is compatible with the user's flight intent") is left for another PR.
Additionally here I removed the return value of the function `validate_shared_operational_intent`.
> [uss_qualifier] validate_shared_operational_intent: mark some checks as validating requirement OPIN0025

- monitoring/monitorlib/fetch/__init__.py
This PR attempts to further band-aid #28 by retrying a timeout once before giving up.  I expect that this will substantially reduce our CI failures, even if it doesn't address the root cause of the problem.
> [monitorlib] Add timeout retry logic for query_and_describe

- monitoring/uss_qualifier/requirements/documentation.py
- monitoring/uss_qualifier/requirements/documentation_test.py
- monitoring/uss_qualifier/requirements/interuss/uss_qualifier/unit_test.md
- monitoring/uss_qualifier/requirements/interuss/uss_qualifier/unit_test/set1.md
When using anchored reference for requirement sets, current implementation skip the last markdown block leading to an empty section and ignored requirements. 
This PR fixes this issue.
> [uss_qualifier] Fix requirement sets parser

- monitoring/mock_uss/scdsc/routes_injection.py
- monitoring/monitorlib/scd.py
- fixes the operational intent reference published at the DSS: it is supposed to contain the off-nominal volumes
- fixes exception for conflicts: according to standard, only the operational intent being modified is supposed to be Activated, not necessarily both
- also fixes the type of `extents` in the model used for the REST API 
- also add some debug logging that was useful when debugging the issues fixed here
> [mock_uss/scdsc] fix extents published at DSS and fix conflict in Activated state

- monitoring/monitorlib/scd.py
- monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/nominal_planning.py
- monitoring/uss_qualifier/scenarios/flight_planning/prioritization_test_steps.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
Following the discussion for requirement SCD0045.
Order of arguments is changed where not necessarily needed for the purpose of consistency.
> Allow flight intent injection directly in Activated state

- monitoring/uss_qualifier/reports/capabilities.py
- monitoring/uss_qualifier/reports/capability_definitions.py
This PR changes the capability granting condition to consider an empty capability requirement set as not successful.
> [uss_qualifier] Do not grant capability if no requirement has been checked.

- monitoring/uss_qualifier/main.py
Small improvement to catch the missing config flag when parsing the command line arguments and gracefully exit.
> [uss_qualifier] Require config flag at the parser level

- build/dev/run_locally.sh
- build/dev/startup/core_service.sh
- build/dev/wait_for_local_dss.sh
- monitoring/prober/run_locally.sh
Due to the difference in naming conventions employed by Docker Compose V1 and V2 the script needed to be updated to handle both possibilities.
> Update Shell Scripts to use Docker Compose V2

- build/dev/docker-compose_dss.yaml
- monitoring/loadtest/README.md
- monitoring/prober/run_locally.sh
Updated dss_sandbox network definition to use a custom naming convention there-in making it independent of V1/V2 naming convention issues.
> Update custom network definition for local DSS

- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
Noticed the issue on some failing tests: if there is an expection interrupting the test exception while in the middle of `ValidateNotSharedOperationalIntent`, the `__exit__` function will be called anyway, but the test framework will error out at `begin_test_step`. This catches the exception (passed as a param), record a note and return if there is an exception.
> [uss_qualifier/scenarios/utm/ValidateNotSharedOperationalIntent] catch exceptions in __exit__

- monitoring/uss_qualifier/configurations/dev/noop.yaml
- monitoring/uss_qualifier/resources/dev/__init__.py
- monitoring/uss_qualifier/resources/dev/noop.py
- monitoring/uss_qualifier/scenarios/dev/__init__.py
- monitoring/uss_qualifier/scenarios/dev/noop.md
- monitoring/uss_qualifier/scenarios/dev/noop.py
Add a "no-op" `TestScenario` with the accompanying `Resource` and an example configuration.
This is useful for basic end-to-end tests when integrating the `uss_qualifier` into other systems, without any dependencies on external services.
> [uss_qualifier] Add a no-op test scenario

- monitoring/uss_qualifier/resources/interuss/report.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/interuss/evaluation_scenario.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
- monitoring/uss_qualifier/suites/definitions.py
- monitoring/uss_qualifier/suites/suite.py
This adds in the test framework the ability to define in test suites a report evaluation scenario, which if defined will be executed after all the actions were executed.
Such a scenario needs to inherit from `ReportEvaluationScenario`.
The framework will inject the report as a resource.
This also bootstraps the RID aggregate check scenarios v19+v22a with a dummy implementation.
> [uss_qualifier] Add report evaluation scenario feature

- monitoring/monitorlib/geo.py
- monitoring/monitorlib/mutate/rid.py
- monitoring/monitorlib/rid.py
- monitoring/monitorlib/schema_validation.py
- monitoring/uss_qualifier/action_generators/astm/f3411/__init__.py
- monitoring/uss_qualifier/action_generators/astm/f3411/for_each_dss.py
- monitoring/uss_qualifier/configurations/dev/local_test.json
- monitoring/uss_qualifier/configurations/dev/netrid_v22a.yaml
- monitoring/uss_qualifier/configurations/dev/resources.yaml
- monitoring/uss_qualifier/reports/graphs.py
- monitoring/uss_qualifier/reports/report.py
- monitoring/uss_qualifier/resources/astm/f3411/__init__.py
- monitoring/uss_qualifier/resources/astm/f3411/dss.py
- monitoring/uss_qualifier/resources/interuss/__init__.py
- monitoring/uss_qualifier/resources/interuss/id_generator.py
- monitoring/uss_qualifier/resources/netrid/__init__.py
- monitoring/uss_qualifier/resources/netrid/service_area.py
- monitoring/uss_qualifier/resources/resource.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/nominal_behavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_simple.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
- monitoring/uss_qualifier/suites/dev/local_test.yaml
- monitoring/uss_qualifier/suites/uspace/network_identification.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
This PR begins the migration of the tests performed in the legacy `prober` tool to uss_qualifier.  It starts by implementing the first portion of test_isa_simple.py from prober, with TODOs for the unimplemented portions.
Two brand new resources are added: an ID generator, to make ISA IDs that can be easily inspected as test IDs by a human, and a service area definition, to describe how test ISAs should look (where they are, etc).  Also, a single DSS instance resource is added (as a companion to the existing resource representing a pool of DSS instances).  These resources are defined in the dev configuration resources.yaml and added to the F3411-22a suite and all suites that end up using that suite.
Since prober acts on a single DSS instance, a ForEachDSS action generator is added to step …
> [uss_qualifier] Add ISASimple NetRID DSS scenario

- .github/workflows/ci.yml
- monitoring/uss_qualifier/run_locally.sh
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/scenarios/scenario.py
- monitoring/uss_qualifier/suites/suite.py
Currently, we not-infrequently experience problems communicating between containers during CI checks.  Since CI requires fully-successful tests, as soon as one of these errors occurs, we know the CI cannot succeed.  But, test execution continues because we do not fail fast.  This PR adds an option (specified via USS_QUALIFIER_STOP_FAST environment variable, marked true in CI) to upgrade any failed test check to critical severity, thus causing the test run to end early.
This PR also fixes a bug where some test steps would swallow any exception (including TestRunCannotContinueError raised by critical-severity failed checks) and continue execution with only a note that an exception had occurred.
Finally, this PR also tidies the cleanup action of a TestScenario so that if a critical-severity …
> [uss_qualifier] Add option to stop uss_qualifier fast

- monitoring/uss_qualifier/reports/capabilities.py
- monitoring/uss_qualifier/reports/report.py
Previously, query_passed_checks and query_failed_checks did not generate correct JSON Paths at the TestSuiteActionReport level, and the ultimate path results were not prefixed with `$.` when placed into the capability evaluation report.  This PR should fix both problems.
> [uss_qualifier] Fix JSONPath generation in TestSuiteActionReport check queries

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
Note that both conditions (b and c) are controlled for together for simplifying the implementation. 
For reference, net-0270 b and c respectively state that upon entering or leaving the requested area, the requester is only provided with the last/first data point outside of the area.
Most of the logic is there to handle the case where an aircraft would cross the boundary multiple times within the minute for which recent data can be displayed.
> [uss-qualifier] add NET0270 b and c

- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
These changes are to ensure that Telemetry is being used when available and not extrapolation.
> [uss_qualifier] Add F3411 check for NET0290

- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
This assumes that a successful injection means that there is an available SP test instance. I hope it is a valid one.
> [uss_qualifier/rid/nominal] Add requirement NET0500 to existing check

- monitoring/monitorlib/schema_validation.py
- monitoring/uss_qualifier/README.md
- monitoring/uss_qualifier/configurations/configuration.py
- monitoring/uss_qualifier/main.py
- monitoring/uss_qualifier/resources/resource.py
- monitoring/uss_qualifier/run_locally.sh
- monitoring/uss_qualifier/validation.py
Constructing a valid configuration can be difficult given the fairly huge data structure being defined, potentially over many different files.  To help users create, edit, and manage these configurations, this PR first robustly validates an input configuration using ImplicitDict-generated JSON Schema before proceeding.  It also adds some execution options to only validate the configuration, and to write the flattened configuration for review or archival.
Separately, it fixes some uss_qualifier documentation in README.md.
> [uss_qualifier] Validate configuration and add configuration-based execution options

- monitoring/uss_qualifier/run_locally.sh
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_simple.md
- schemas/monitoring/uss_qualifier/configurations/configuration/ArtifactsConfiguration.json
- schemas/monitoring/uss_qualifier/configurations/configuration/ReportConfiguration.json
- schemas/monitoring/uss_qualifier/configurations/configuration/TemplatedReportConfiguration.json
- schemas/monitoring/uss_qualifier/configurations/configuration/TemplatedReportInjectedConfiguration.json
- schemas/monitoring/uss_qualifier/reports/templates/InjectedConfiguration.json
Previously, the ISASimple scenario would not clean up the ISA which would cause problems in the rest of the NetRID suite.  This PR fixes that bug and also enables netrid_v22a as a configuration in the CI.  netrid_v19 is still excluded from CI to avoid lengthening CI execution time even more.
This PR also includes some schema file changes as a result of `make format` that apparently weren't detected as not regenerated in `make lint` for a previous PR.
> [uss_qualifier] Clean up ISA in ISASimple scenario

- monitoring/monitorlib/rid.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/subscription_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/subscription_validation.md
Adds a test to cover DSS0050: for a given area modelled by the DSS, we should only be allowed to create 10 subscriptions, not more.
> [uss_qualifier] Test DSS Subscription limitations (too many subscriptions)

- .github/workflows/ci.yml
- monitoring/uss_qualifier/scripts/test_docker_fully_mocked.sh
Currently, the most important CI step is labeled with "F3411-22a" because, previously, we had to deploy the local USS mocks differently to test F3411-19 versus F3411-22a.  This PR first removes the "F3411-22a" label to make it clear that this step is the main uss_qualifier test set, then it also removes the last RID_VERSION environment variable switch as it is no longer needed.
> [CI] Rename CI steps

- monitoring/monitorlib/fetch/__init__.py
- monitoring/monitorlib/rid.py
- monitoring/uss_qualifier/resources/netrid/observers.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.md
Note that validating the performance of the DP for returning details requires us to actually generate some queries for that endpoint.
To this end we query details for each flight that is returned when checking the `display_data` endpoint.
> [uss_qualifier] NET0460 evaluate display provider's flight data details endpoint performance

- monitoring/monitorlib/infrastructure.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/misbehavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/misbehavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/misbehavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/misbehavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/misbehavior.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Add check for NET0210, which is about checking that service providers correctly authenticate requests.
This is done via a new `misbehavior` scenario that will inject flight data and query the SP's endpoint for that data without providing credentials.
It behaves very similarly to the `nominal_behavior` scenario, with these two tweaks:
* a DSS instance is required instead of being optional
* the polling stops as soon as we have validated that the SP properly authenticates the flights and flight_details requests.
> [uss_qualifier] Validate that some queries to service_providers are properly authenticated for NET0210

- monitoring/monitorlib/fetch/__init__.py
- monitoring/monitorlib/fetch/rid.py
- monitoring/monitorlib/mutate/rid.py
- monitoring/monitorlib/mutate/scd.py
- monitoring/uss_qualifier/configurations/dev/library/environment.yaml
- monitoring/uss_qualifier/resources/astm/f3411/dss.py
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/resources/flight_planning/flight_planner.py
- monitoring/uss_qualifier/resources/interuss/mock_uss.py
- monitoring/uss_qualifier/resources/netrid/observers.py
- monitoring/uss_qualifier/resources/netrid/service_providers.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/misbehavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Checking for NET0220 by ensuring all queries to USSes are relying on https.
In order to validate that queries are not sent in cleartext while not breaking local non-https setups, this:
* tags all/most queries with the server_id it is intended to
* adds a `local_debug` flag to service providers, observers and dss'es 
* adds a check to the aggregate checks that validates all recorded queries are using https when they target an USS that isn't in `local_debug` mode.
Open questions/notes:
* We may want to add the participant_id/server_id to the UTM session object? That might make this PR a bit simple.
> [uss_qualifier] Inspect all collected queries for the usage of https (NET0220)

- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
As discussed with @barroco NET0450 is probably already checked for implicitly, and we need to properly mention that.
> [uss_qualifier] Add NET0450 to existing checks

- monitoring/uss_qualifier/action_generators/README.md
- monitoring/uss_qualifier/scenarios/astm/dss/crdb_access.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/operator_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/crdb_access.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/crdb_access.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/operator_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/operator_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/crdb_access.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/crdb_access.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/operator_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/operator_interactions.py
- monitoring/uss_qualifier/suites/README.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/documentation/documentation.py
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/geo_awareness_cis.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Internally, InterUSS contributors have an idea of how some additional F3411 requirements could be tested, but these tests may not be implemented in the near future.  As a placeholder to document these thoughts for future improvements, this PR primarily adds a few additional NetRID test scenarios with null implementations in order to capture plans for verifying compliance to currently-unverified requirements in official documentation.
This PR also improves top-level test suite and action generator documentation and links to it when it may be useful.
Finally, this PR also improves the "Status" values for requirements checking in test suite documentation as "Planned" was confusing to some readers.
> [uss_qualifier] Add empty scenarios for RID documentation

- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
NET0340 is covered by NET0710, NET0730 and NET0740. Note that only NET0710 was implemented so far, so only these checks are modified.
> [uss_qualifier] mention NET0340 where relevant in existing checks

- monitoring/uss_qualifier/configurations/configuration.py
- monitoring/uss_qualifier/configurations/dev/f3548.yaml
- monitoring/uss_qualifier/configurations/dev/netrid_v22a.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/main.py
- monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html
- monitoring/uss_qualifier/reports/tested_requirements.py
- schemas/monitoring/uss_qualifier/configurations/configuration/TestedRequirementsConfiguration.json
This PR introduces the capability to define a set of requirements that each participant wants to demonstrate compliance with via the tested requirements artifact.  If omitted, the set of requirements is assumed to be all the currently-documented requirements potentially testable by the test run configuration (same as before this PR).
> [uss_qualifier] Add optional requirements collection specification for tested requirements artifact

- monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html
- monitoring/uss_qualifier/reports/tested_requirements.py
- monitoring/uss_qualifier/requirements/definitions.py
- monitoring/uss_qualifier/requirements/documentation.py
- monitoring/uss_qualifier/suites/documentation/documentation.py
This PR primarily adds links to requirement packages in the tested_requirements artifact optionally produced by uss_qualifier.  To accomplish this, it establishes a new explicit PackageID type and propagates that new type to appropriate places.
This PR also addresses a few minor issues with the tested_requirements artifact: it adds a dash to some identifiers, some missing span tags, and alternating-rows background formatting.
Finally, this PR improves the name of a RequirementID method to be more specific.
> [uss_qualifier/reports] Link to requirement packages in tested requirements artifact

- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/aggregate_checks.md
This check was problematic for #204 where there is a query that is not attributed but that's OK (a notification to a non-existent USS during the DSS interoperability scenario). Having a trace of the information is useful though, so this PR transforms it into a recorded note.
> [uss_qualifier/scenarios/aggregate_checks] Convert unattributed queries check to a note

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
Also validate details that are observed through the DP.
Note that this PR also replaces a few dashes (from – to -)
> [uss_qualifier] NET0450 check that observed details (from a display provider) correspond to injected ones

- monitoring/mock_uss/database.py
- monitoring/mock_uss/ridsp/routes_injection.py
- monitoring/mock_uss/scdsc/routes_injection.py
- monitoring/monitorlib/fetch/__init__.py
In an effort to address #230, this PR adds some additional logging in mock_uss and also attempts to make sure mutating requests are not accidentally repeated.  The latter is accomplished by always appending a `request_id` field to any outgoing requests which contain a JSON body and don't already have this field, then checking for that field in handlers for mutating operations.
> [mock_uss] Improve logging and use request_ids

- .github/workflows/CI.md
- CONTRIBUTING.md
- monitoring/uss_qualifier/scenarios/README.md
This PR replaces the old CONTRIBUTING.md with a reference to the common InterUSS contributing process, plus specifics for this repository (most of which is newly-drafted).  Since this links to the CI documentation, that is updated as well.
> [docs] Refer to InterUSS contributing procedure, improve contributing doc

- monitoring/mock_uss/templates/tracer/log.html
- monitoring/monitorlib/fetch/__init__.py
- monitoring/monitorlib/html/templates/explorer.html
- monitoring/uss_qualifier/configurations/configuration.py
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/main.py
- monitoring/uss_qualifier/reports/report.py
- monitoring/uss_qualifier/reports/sequence_view.py
- monitoring/uss_qualifier/reports/templates/report.html
- monitoring/uss_qualifier/reports/templates/sequence_view/overview.html
- monitoring/uss_qualifier/reports/templates/sequence_view/scenario.html
- monitoring/uss_qualifier/scenarios/scenario.py
- schemas/monitoring/uss_qualifier/configurations/configuration/ArtifactsConfiguration.json
- schemas/monitoring/uss_qualifier/configurations/configuration/ReportHTMLConfiguration.json
- schemas/monitoring/uss_qualifier/configurations/configuration/SequenceViewConfiguration.json
- schemas/monitoring/uss_qualifier/reports/report/PassedCheck.json
This PR adds a new artifact to uss_qualifier focused on communicating what actually happened during a test run, partially addressing #222.  When this artifact is configured (as it now is on configurations.dev.uspace) with an output path, an HTML file per scenario in the test run will be produced along with an index file to access them.  Only small adaptations are made to reuse the "explorer" template to dynamically expand and collapse query details, and a few other minor places.  The .json files are autogenerated according to schema adjustments in the Python files.
The index file looks something like:
Each scenario file looks something like:
> [uss_qualifier] Add sequence view artifact

- monitoring/mock_uss/scdsc/routes_injection.py
Currently, mock_uss always pulls the latest operational intent information when conducting a flight planning activity.  But, that is unnecessary when managing an off-nominal flight as off-nominal flights do not need to deconflict with other flights.  This PR optimizes mock_uss flight planning to skip pulling the latest operational intent information when managing an off-nominal flight.
It also fixes a bug where a valid-transition check could exit the flight planning routine without releasing the lock established on an existing flight (the check is moved into the `try` block where the corresponding `finally` block releases the lock).
> [mock_uss] Do not query operational intents when not deconflicting

- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/reports/templates.py
> [uss_qualifier/report] Fix report generation with html strings

- monitoring/uss_qualifier/reports/sequence_view.py
- monitoring/uss_qualifier/reports/templates/sequence_view/overview.html
- monitoring/uss_qualifier/reports/tested_requirements.py
This PR adds some additional information about the test run to the sequence view artifact index page.
> [uss_qualifier] Add information to sequence view index page

- monitoring/uss_qualifier/configurations/dev/f3548.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/reports/report.py
- monitoring/uss_qualifier/reports/sequence_view.py
- monitoring/uss_qualifier/reports/templates/sequence_view/overview.html
- monitoring/uss_qualifier/suites/suite.py
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
- monitoring/uss_qualifier/suites/uspace/network_identification.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
- schemas/monitoring/uss_qualifier/reports/report/SkippedActionReport.json
Currently, the U-space development test is skipping two test suites because recently-created resources are not being provided to the lower-level test suites by the high-level test suites.  This is causing a few different artifacts to render in confusing ways.  This PR first fixes the sequence view artifact to show skipped actions in a reasonable way, and then fixes the skipped actions by providing the new resources from the higher-level test suites.
> [uss_qualifier] Fix U-space test

- .github/workflows/ci.yml
- .github/workflows/dev-checks.yml
- .github/workflows/image-publish.yml
- .github/workflows/monitoring-test.yml
Currently, our Actions summaries have warnings that our [checkout@v2 action](https://github.com/actions/checkout) "uses node12 which is deprecated and will be forced to run on node16".  This PR upgrades to checkout@v4 to resolve those warnings.  No functional changes are intended or anticipated.
> [CI] Update GitHub checkout action version

- monitoring/mock_uss/start.sh
- requirements.txt
See https://github.com/interuss/monitoring/issues/28#issuecomment-1764586324 for context.
This may or may not fix the issue.
This also sets the worker tmp dir to a RAM-based storage. See those links for insight as to why that may help the #28 situation, and will improve performances in any case: 
- https://pythonspeed.com/articles/gunicorn-in-docker/
- https://docs.gunicorn.org/en/stable/faq.html#blocking-os-fchmod
> [mock_uss/gunicorn] Use gevent worker type to mitigate #28

- monitoring/uss_qualifier/action_generators/action_generator.py
- monitoring/uss_qualifier/action_generators/astm/f3411/for_each_dss.py
- monitoring/uss_qualifier/action_generators/astm/f3548/for_each_dss.py
- monitoring/uss_qualifier/action_generators/flight_planning/planner_combinations.py
- monitoring/uss_qualifier/action_generators/interuss/mock_uss/with_locality.py
- monitoring/uss_qualifier/action_generators/repetition/repeat.py
- monitoring/uss_qualifier/suites/suite.py
This PR changes action generators from actually running test suite actions themselves to merely generating them via an iterator.  In addition to making implementation cleaner, this is needed in order to prepare for the addition of execution control (skipping actions, running just specified actions, etc).
> [uss_qualifier] Use iterators with action generators

- monitoring/uss_qualifier/configurations/dev/library/resources.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/suites/definitions.py
- monitoring/uss_qualifier/suites/suite.py
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
- schemas/monitoring/uss_qualifier/suites/definitions/TestSuiteDeclaration.json
- schemas/monitoring/uss_qualifier/suites/definitions/TestSuiteDefinition.json
When we have a test tool that can be used in many different kinds of tests, the use in one particular test suite may require customization that doesn't really make sense to have the user configure.  For instance, U-space is likely to be sufficiently harmonized that the U-space-certified-system should be the same across member states.  So, it makes sense to pick a single identifier for a U-space system for the purpose of obtaining version information rather than specifying that identifier in each member state's configuration.
This PR adds the ability to define resources within a test suite rather than requiring all resources to come from the parent resource pool.  This capability is exercised on the system identifier for versioning in the U-space test suite.
> [uss_qualifier] Add local test suite resources

- monitoring/uss_qualifier/reports/report.py
Currently, an execution error (a raised Exception during scenario execution) is not considered a critical error and therefore execution continues.  This small PR makes it a critical error, which will therefore (gracefully) stop test execution.
> [uss_qualifier] Make execution error critical

- Makefile
`black` was happily descending into my local `venv` directory when running `make format` at the root: such a setup seems common enough to warrant an exclusion by default.
This was tested on a fresh `venv` installed in the repository root.
> [tooling] Ignore venv directory in root `make format` target

- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validation.py
Noticed that `common/isa_validation.py` forgot to set the participant ID on some queries.
This also adds the HTTP method to the recorded note in the aggregated checks: it should help with locating unattributed queries (there are still quite a few but I'll keep fixing these for another time)
> [uss_qualifier] Add missing participant attribution in ISA validation scenario

- monitoring/prober/infrastructure.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_expiry.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_expiry.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_expiry.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_expiry.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_expiry.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.yaml
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Ports the existing `test_isa_expiry.py` prober test to a new `ISAExpiry` generic test scenario.
> [uss_qualifier] DSS0030 migrate isa expiry check from prober

- monitoring/mock_uss/__init__.py
- monitoring/mock_uss/docker-compose.yaml
- monitoring/mock_uss/flight_planning/routes.py
- monitoring/mock_uss/scdsc/routes_injection.py
- monitoring/mock_uss/scdsc/routes_scdsc.py
- monitoring/monitorlib/clients/flight_planning/client_scd.py
- monitoring/monitorlib/clients/flight_planning/client_v1.py
- monitoring/monitorlib/clients/flight_planning/flight_info.py
- monitoring/monitorlib/geo.py
- monitoring/monitorlib/geotemporal.py
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
This PR adds an implementation of [the flight_planning automated testing API](https://github.com/interuss/automated_testing_interfaces/tree/main/flight_planning) to mock_uss by simply calling the existing flight planning handlers for [the legacy scd interface](https://github.com/interuss/automated_testing_interfaces/tree/main/scd).  The interface used in uss_qualifier's CI automated tests is switched to this new API for all but one of the mock_uss instances.
The overall state of mock_uss flight planning handling is still left in need of some attention after this PR, but I hope to follow up with some improvements.
> [mock_uss] Add flight_planning API implementation to mock_uss

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/utm/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/scenarios/scenario.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This adds aggregated checks scenario for UTM scenarios, with test of SCD0075 about performances of operational intent details retrieval from USSs.
Additionally: 
- attribute proper query type for DSS operational intent search queries 
- attribute proper participant ID and query type for USS operational intent details queries 
- queries log now show the attributed participant ID + query type at the time of being recorded (if this is not desirable because of the noise it generates I can remove it, but that is useful when working with aggregate checks scenario)
> [uss_qualifier/utm] Add AggregateChecks scenario with SCD0075 check

- monitoring/monitorlib/fetch/rid.py
- monitoring/prober/infrastructure.py
- monitoring/uss_qualifier/requirements/interuss/f3411/dss_endpoints.md
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/utils.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.yaml
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This ports the existing `test_subscription_isa_interaction.py` prober test to a generic `ISASubscriptionInteractions` scenario.
This also adds a `delete_any_subscription` function to `monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/utils.py`
A few API methods have been added to `requirements/interuss/f3411/dss_endpoints.md`, as this scenario depends on implementation details specified in the A4.1 annex that are not mentioned in the standard.
> [uss_qualifier] DSS0030 port ISA-subscriptions interactions test

- monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html
- monitoring/uss_qualifier/reports/templates/tested_requirements/test_run_report.html
- monitoring/uss_qualifier/reports/tested_requirements.py
This PR adds a bit of additional information to the tested_requirements uss_qualifier artifact:
* System version, from the first instance of a GetSystemVersions test scenario, if one exists
* Overall status of requirements verification (rolling up all requirements identified for the artifact)
This PR also outputs a small JSON file with the top-level information included in the human-readable tested_requirements report.
> [uss_qualifier/artifacts] Supplement tested requirements artifact with additional information

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/test_data/che/rid/foca.kml
- monitoring/uss_qualifier/test_data/usa/kentland/rid.kml
- monitoring/uss_qualifier/test_data/usa/netrid/dcdemo.kml
Two issues were discovered by a NetRID automated testing user, both of which are addressed by this PR:
1. The registration_number values used in NetRID test data (which are put into [the registration_id field](https://github.com/uastech/standards/blob/astm_rid_api_2.1/remoteid/canonical.yaml#L1628)) do not follow the prescribed format, and therefore should fail validation in a fully-compliant USS.  This issue was not noticed previously because we [don't yet check registration_id format](https://github.com/interuss/monitoring/blob/89aaa4bba65b0bde664bed817e2968c855cc5658/monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py#L306).
2. The HTTP response code for "area too large" in [a number of ASTM F3411-22a …
> [uss_qualifier] Fix NetRID automated testing issues

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/utils.py
Following the discussion [here](https://github.com/interuss/monitoring/pull/291#discussion_r1377851163) on #291 , don't use the subscription notification URL as the participant ID.
Instead, rely on the query's participant_id. Note that currently, this will mostly not be set, and if we run into many failures that can't be attributed, we'll probably want to find a way to attribute those queries properly.
> [uss_qualifier] Don't use participant notification URLs as participant IDs

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/utils.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/subscription_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/subscription_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss_interoperability.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/subscription_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/subscription_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
As [pointed out](https://github.com/interuss/monitoring/pull/295#discussion_r1375303789) in #295 the subscription cleanups require two checks.
This updates the helper function on `dss_wrapper` to reflect that fact, and fixes the documentation of `subscription_validation` and `dss_interoperability`
The redundant `delete_any_subscription` function in `utils.py` is removed as well and the two existing call-sites are now using the cleanup function on the `DSSWrapper`
> [uss_qualifier] Split subscription cleanup checks into their "query" and "deletion" parts

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/utils.py
This PR should resolve #309 and a few similar locations
> [uss_qualifier] Fix participant_id access

- monitoring/uss_qualifier/resources/interuss/id_generator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py
This is an initial quick fix for issue #306: it profits of the fact that the `sub` claim is already made available in the `IDGeneratorResource` and that the `subscription_simple` scenario already depends on it.
A proper fix probably involves defining a new resource, as described in #306 . Discussion on this topic will continue on the issue.
> [uss_qualifier] Expect correct value of 'owner' in subscription_simple scenario

- monitoring/mock_uss/f3548v21/flight_planning.py
- monitoring/mock_uss/scd_injection/routes_injection.py
- monitoring/monitorlib/clients/flight_planning/flight_info.py
- monitoring/monitorlib/clients/flight_planning/flight_info_template.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
This PR works toward reoganizing mock_uss flight planning routines to better encapsulate functionality.  F3548-21 things are moved to f3548v21/flight_planning.py and out of scd_injection/routes_injection.py.  Some of the scd-injection-API-focused routines are adjusted to use API-independent FlightInfo and FlightRecord instead.
One apparent bug is fixed in conflict_equal_priority_not_permitted.py -- Nonconforming necessarily means the flight plan is active (aircraft is flying) and not merely Planned, so the expected response is updated to ReadyToFly, which mock_uss currently indicates.
> [mock_uss] Clean up mock_uss flight planning

- monitoring/uss_qualifier/common_data_definitions.py
- monitoring/uss_qualifier/scenarios/README.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/validate_not_shared_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md
- monitoring/uss_qualifier/scenarios/documentation/definitions.py
- monitoring/uss_qualifier/scenarios/documentation/parsing.py
- monitoring/uss_qualifier/scenarios/flight_planning/activate_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/activate_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/modify_planned_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/plan_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/plan_flight_intent.md
Currently, test scenario documentation does not allow a reader to easily understand the flow-control impact of a failing check because the severity of a failing check is provided only in code.  This PR begins a process to eventually require all check documentation to indicate default Severity, though this value will still be possible to override at runtime in rare conditions.  This PR:
* Adds a description of check severity documentation in the test scenarios README
* Extracts severity information from test scenario documentation (when present)
* Adds severity documentation to conflict_equal_priority_not_permitted.md (though this documentation is not used for anything yet)
> [uss_qualifier] Introduce check severity documentation

- monitoring/mock_uss/f3548v21/flight_planning.py
- monitoring/mock_uss/flight_planning/routes.py
- monitoring/mock_uss/flights/planning.py
- monitoring/mock_uss/scd_injection/routes_injection.py
- monitoring/mock_uss/uspace/flight_auth.py
- monitoring/monitorlib/clients/flight_planning/planning.py
- monitoring/monitorlib/clients/mock_uss/mock_uss_scd_injection_api.py
- monitoring/uss_qualifier/reports/tested_requirements.py
Historically, mock_uss's core flight planning handler routines used API objects from the [now-deprecated scd injection API](https://github.com/interuss/automated_testing_interfaces/tree/main/scd) for both the input/request and output/response.  This PR does most of the work to switch these routines to use business objects instead.  The clear_area routine is also adjusted to target deletion of known flights first before following up with cleanup of straggling operational intents.
> [mock_uss] Remove API objects from flight planning routines

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Added data validation scenario to f3548_21 suite.
> [uss_qualifer] Add data validation scenario to ASTM F3548-21 suite

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/configurations/dev/library/resources.yaml
- monitoring/uss_qualifier/configurations/dev/library/validation.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/main.py
- monitoring/uss_qualifier/scenarios/interuss/geospatial_map/geospatial_feature_comprehension.py
- monitoring/uss_qualifier/scenarios/scenario.py
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
- monitoring/uss_qualifier/test_data/che/flight_intents/non_conflicting.yaml
Our current main branch is failing to detect most test failures in CI runs because the exit code from an inner function in main.py is being discarded in favor of always returning EX_OK.  This PR fixes the bug in main.py and then fixes the errors revealed when that bug is fixed, along with some cleanup noticed while making these fixes.  The bulk of the changes in this PR provide a mock_uss instance and the new flight intents resource to the ASTM F3548-21 suite when called from the U-space suite.  An additional validation criterion is added for most reports that no actions may be skipped (though this is intentionally not applied to f3548_self_contained).  The new flight intents file is copied into Switzerland test data and the lat/lng coordinates are adjusted to be in Switzerland for that …
> [uss_qualifier] Fix report validation

- monitoring/mock_uss/flight_planning/routes.py
- monitoring/mock_uss/scd_injection/routes_injection.py
- monitoring/monitorlib/clients/flight_planning/client_v1.py
- monitoring/monitorlib/inspection.py
- monitoring/uss_qualifier/requirements/interuss/automated_testing/flight_planning.md
- monitoring/uss_qualifier/scenarios/astm/utm/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/prep_planners.md
- monitoring/uss_qualifier/scenarios/astm/utm/prep_planners.py
- monitoring/uss_qualifier/scenarios/documentation/parsing.py
- monitoring/uss_qualifier/scenarios/flight_planning/__init__.py
- monitoring/uss_qualifier/scenarios/flight_planning/prep_planners.md
- monitoring/uss_qualifier/scenarios/flight_planning/prep_planners.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.md
For most flight planning tests (currently ASTM F3548-21 + U-space), it is important to ensure the test area is clear of any other flights as any other flights in the area would render these tests invalid.  Currently, we attempt to have maximum encapsulation of each individual scenario by clearing the area as the first step in the scenario.  This, however, is [not always effective](https://github.com/interuss/monitoring/issues/21) as we often run scenarios with a subset of flight planners known to the overall test run/configuration, so lingering flights might be from a planner that is part of the test run, but not part of the current scenario.
This PR addresses this issue by creating a PrepareFlightPlanners scenario that checks readiness and clears all relevant areas.  This scenario is …
> [uss_qualifier] Add PrepareFlightPlanners scenario

- monitoring/uss_qualifier/reports/sequence_view.py
- monitoring/uss_qualifier/reports/templates/sequence_view/overview.html
- monitoring/uss_qualifier/reports/templates/sequence_view/scenario.html
Currently, the sequence view artifact does not visualize execution errors.  This can lead to confusion when viewing the artifact for a test run that had execution errors (everything will appear normal, but truncated).  This PR fixes that by displaying execution error information when present and visually indicating that one happened for a particular scenario on the overview page.
Since `TestedScenario` is only an in-memory object and is not serialized or deserialized, there is no reason for it to be an ImplicitDict so it is changed to a dataclass while already modifying it for the reason above.
A heading title in the artifact is also adjusted for clarity.
> [uss_qualifier] Display execution errors in sequence view artifact

- .dockerignore
- monitoring/Makefile
Currently, *.pyc files affect whether the monitoring image is rebuilt or not, so if someone using the repository has a tool that manipulates *.pyc files (e.g., a full-featured IDE like IntelliJ), they will build the monitoring image far more frequently than is necessary.  This PR excludes prebuilt *.pyc files from the image and removes them as a make dependency.  Removing prebuilt *.pyc files is also desirable generally as the host machine on which they are built may build them differently than the container in which the image is run.
> [build] Exclude pyc files from image

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_subscription_interactions.md
The specification (the standard or the OpenAPI spec) don't say much on what should happen when optional parameters are not set, so I have not added any particular checks for these situations.
Note that this also includes a little renaming for some cleanup checks in `isa_subscription_interactions`: as is often the case when creating test subscriptions, it reveals some check naming issues in the cleanup checks of other scenarios.
> [uss_qualifier] DSS0030 let subscription_simple create subscriptions that don't set optional parameters

- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_validation.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Catching up on some [clean up](https://github.com/interuss/monitoring/pull/238#discussion_r1358574003) tasks
> [uss_qualifier] add standard references to the isa_validation documentation

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
This to reflect its use in `isa_validation.py`: most if not all scenarios that have a `DSSWrapper` have access to its internals one way or another, so keeping `handle_query_result` private does not protect much.
If there is an important reason I missed, I'm happy to do the necessary adaptations in `isa_validation.py`
> [uss_qualifier] dss_wrapper's handle_query_result function is made public

- monitoring/monitorlib/auth.py
- monitoring/prober/infrastructure.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/token_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/token_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/token_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/token_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/token_validation.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.yaml
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This is an almost direct port of the old `test_token_validation.py` v1 scenario, but it supports both versions of the standard.
There is the possibility for also testing the endpoints for searching ISAs, which I can do in a later PR.
> [uss_qualifier] DSS0030 token validation scenario

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
- monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.md
- monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
As a follow-up to #331, this PR removes area clearing from individual test scenarios in favor of (existing, per #331) invocations of the PrepareFlightPlanners scenario.
> [uss_qualifier] Remove area clearing from individual scenarios

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/library/resources.yaml
- monitoring/uss_qualifier/fileio.py
- monitoring/uss_qualifier/resources/flight_planning/flight_intent.py
- monitoring/uss_qualifier/resources/flight_planning/flight_intents_resource.py
- schemas/monitoring/monitorlib/clients/flight_planning/flight_info/ASTMF354821OpIntentInformation.json
- schemas/monitoring/monitorlib/clients/flight_planning/flight_info/FlightAuthorisationData.json
- schemas/monitoring/monitorlib/clients/flight_planning/flight_info/RPAS26FlightDetails.json
- schemas/monitoring/monitorlib/clients/flight_planning/flight_info_template/BasicFlightPlanInformationTemplate.json
- schemas/monitoring/monitorlib/clients/flight_planning/flight_info_template/FlightInfoTemplate.json
- schemas/monitoring/uss_qualifier/resources/flight_planning/flight_intent/DeltaFlightIntent.json
- schemas/monitoring/uss_qualifier/resources/flight_planning/flight_intent/FlightIntentCollection.json
- schemas/monitoring/uss_qualifier/resources/flight_planning/flight_intent/FlightIntentCollectionElement.json
- schemas/monitoring/uss_qualifier/resources/flight_planning/flight_intent/FlightIntentsSpecification.json
Some users may want to embed flight intent information directly in a configuration (and therefore the final report); this PR adds that flexibility rather than forcing the user to specify an external file containing the flight intent information.  This change should be backwards-compatible for configurations.
Also, the $ref loading structure is updated to allow package-based $ref locations when specified.
Note that most of the lines changed in this PR are auto-generated files in response to embedding the FlightIntentCollection type within the resource specification object.
> [uss_qualifier] Add ability to specify flight intents directly in configuration

- monitoring/monitorlib/fetch/evaluation_test.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
Initial investigation into, and subsequent fix for #343.
This also:
* adds a simple unit test to confirm that the basic thing is working as expected (although the issue was unrelated to the method being tested).
* adds an additional `record_note` with the exact times that were used to compute the statistic (with the hope that it might help troubleshoot any future bugs and give more information to USS's that fail this check)
Before the fix we would have duplicate times being considered in the statistics computation:
```
Computed durations: 
init=
[0.009221, 0.017303, 0.006969, 0.015645, 0.019991, 0.020171, 0.019669, 0.022012, 0.024948, 0.024175, 0.023265, 0.022342, 0.02261, 0.026369, 0.02529, 0.024384, 0.024189, 0.024016, 0.022973, 0.020148, 0.016649, 0.010734, 0.007285, 0.010437, …
```
> [uss_qualifier] Fix aggregate queries stats for #343

- monitoring/uss_qualifier/Makefile
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/subscription_simple.md
- monitoring/uss_qualifier/scripts/check-netrid-cross-references.sh
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This occurred to me sufficiently to be worth an automated check. 
This also fixes issue #352 
`monitoring/uss_qualifier/scripts/check-netrid-cross-references.sh` was tested against `main` before fixing the doc, and it also fails if you manually add a mistake in a v19 doc file.
> [uss_qualifier] Make target that checks if a v19 doc file references v22a or vice-versa (and fix #352)

- monitoring/mock_uss/f3548v21/flight_planning.py
- monitoring/mock_uss/scd_injection/routes_injection.py
Currently if a notification to an USS fails after the mock USS shares or deletes an op intent, the entire call fails.
That is not compatible with notably the expected behavior when a USS is down. And in general I do not believe those calls are expected to fail if a notification fails.
This PR changes this behavior to attempt all notifications, and if some of them do fail, the error is returned up the stack and returned as notes in the response.
> [mock_uss/flight_planning] Do not fail op intent injection or deletion when a notification fail

- monitoring/monitorlib/clients/flight_planning/flight_info_template.py
- monitoring/monitorlib/geotemporal.py
- monitoring/monitorlib/temporal.py
- monitoring/uss_qualifier/configurations/dev/library/resources.yaml
- monitoring/uss_qualifier/resources/flight_planning/flight_intent.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/flight_planning/prep_planners.py
- monitoring/uss_qualifier/scenarios/interuss/flight_authorization/general_flight_authorization.py
- monitoring/uss_qualifier/scenarios/interuss/geospatial_map/geospatial_feature_comprehension.py
- monitoring/uss_qualifier/suites/suite.py
- monitoring/uss_qualifier/test_data/che/flight_intents/conflicting_flights.yaml
- monitoring/uss_qualifier/test_data/che/flight_intents/general_flight_auth_flights.yaml
- monitoring/uss_qualifier/test_data/che/flight_intents/invalid_flight_auths.yaml
- monitoring/uss_qualifier/test_data/che/flight_intents/invalid_flight_intents.yaml
- monitoring/uss_qualifier/test_data/che/flight_intents/non_conflicting.yaml
- monitoring/uss_qualifier/test_data/make_flight_intent_kml.py
- monitoring/uss_qualifier/test_data/usa/kentland/flight_intents/non_conflicting.yaml
- schemas/monitoring/monitorlib/temporal/TestTime.json
- schemas/monitoring/uss_qualifier/resources/interuss/mock_uss/client/MockUSSSpecification.json
Currently, uss_qualifier produces dynamic times (for telemetry, flight intents, etc) relevant to the current test run from static definitions in just one way: specifying times relative to "start of test".  However, it is unclear when the "test" starts (test run?  test scenario?  test step?) and this does not provide enough flexibility for many use cases.  For instance, a test designer may  want to activate flights "now" and not at a particular time relative to the start of the "test".
This PR replaces start_of_test with a more flexible TimeDuringTest construct that allows the specification of many potentially-relevant dynamic times, initially including start of test run, start of test scenario, and "time of evaluation" (as close to "now" as is feasible).
> [uss_qualifier] Improve dynamic time specification

- monitoring/uss_qualifier/configurations/configuration.py
- monitoring/uss_qualifier/main.py
- monitoring/uss_qualifier/reports/artifacts.py
- schemas/monitoring/uss_qualifier/configurations/configuration/ArtifactsConfiguration.json
Some uss_qualifier users may want to define their own container mount points separate from the configuration to run.  Although the output_path parameter that would be overridden to accomplish this is part of the configuration which is an input to the test baseline hash (and therefore a change would affect the baseline hash), the placement of output files in the uss_qualifier container does not reasonably affect the substance of the test.  So, this PR documents that v1.artifacts.output_path may be overridden without affecting the baseline and then overrides it without affecting the baseline.
Verification can be accomplished by running `./monitoring/uss_qualifier/run_locally.sh configurations.dev.noop` then `./monitoring/uss_qualifier/run_locally.sh configurations.dev.noop --output-path …
> [uss_qualifier] Add output path override CLI flag

- Makefile
- schemas/manage_type_schemas.sh
There are two issues with our JSON Schema generation logic currently: 1) `make check-hygiene` doesn't check schemas, and therefore generated schema verification is actually not part of our CI currently, and 2) `make format` uses the default docker user to create schema files and this normally means the resulting files are owned by root rather than the invoking user.  This PR resolves both of those issues.
> [uss_qualifier] Fix schema generation logic

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/token_validation.py
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.yaml
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Fixes reference to wrong version and regenerates the documentation.
(Also opportunistically removes a TODO that was clarified)
> [uss_qualifier] DSS0030 fix rid version for v22a TokenValidation scenario

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_expiry.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/utils.py
While adding subscription interactions to scenarios, the problem of failing checks because of faulty attempts of the uss_qualifier to notify itself became more salient.
Hence, this adds an `ignore_base_url` parameter to `common/dss/utils.delete_isa_if_exists()`.
> [uss_qualifier] do not check failed notification attempts made against the qualifier

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/message_signing.yaml
- monitoring/uss_qualifier/suites/faa/uft/message_signing.yaml
Ran into some warnings about missing resources when troubleshooting the builds for #362: I do not know if this is actually a problem or if it needs fixing.
Warnings I got when running eg `./run_locally.sh configurations.dev.message_signing` locally on master (or when running _all_ the configurations) – it's only one of them, as I had to iteratively fix them until it worked,
```
2023-11-22 14:02:00.993 | WARNING  | monitoring.uss_qualifier.suites.suite:__init__:259 - Skipping action 1 (test_suite suites.astm.utm.f3548_21) because Test suite "ASTM F3548-21" is missing resource invalid_flight_intents (resources.flight_planning.FlightIntentsResource)
```
> [uss_qualifier] Wire additional resources into certain configurations to avoid warnings

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/token_validation.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/token_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/token_validation.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Extends the `TokenValidation` generic test scenario to also try out the ISA search endpoint.
> [uss-qualifier] verify that searches for ISAs on the DSS can't be done without proper credentials

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This should fix #369: The `current_state` and `altitude` field presence is not enforced anymore
(But we still check their content if they are returned)
Note this also cleans up some old troubleshooting log entries.
> [uss_qualifier] nominal_behavior – align requirements on observations with the standard 

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/delete_isa.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/delete_isa.md
Extract the ISA validation logic present in the `DSSWrapper` into an `ISAValidator` class.
The goal is to reuse this in #358
> [uss_qualifier] separate validation logic for validating ISAs

- monitoring/monitorlib/auth.py
- monitoring/uss_qualifier/configurations/dev/dss_probing.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/configurations/dev/library/resources.yaml
- monitoring/uss_qualifier/configurations/dev/netrid_v19.yaml
- monitoring/uss_qualifier/configurations/dev/netrid_v22a.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/resources/communications/__init__.py
- monitoring/uss_qualifier/resources/communications/client_identity.py
- monitoring/uss_qualifier/resources/interuss/id_generator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/subscription_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/subscription_simple.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.yaml
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.yaml
- monitoring/uss_qualifier/suites/uspace/network_identification.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
- schemas/monitoring/uss_qualifier/resources/communications/client_identity/ClientIdentitySpecification.json
- schemas/monitoring/uss_qualifier/resources/interuss/id_generator/IDGeneratorSpecification.json
This is the proper fix for #306:
The client identity (or more colloquially the `sub` field of its JWT) is now exposed to any resource or scenario that needs it via a `ClientIdentityResource`, which now holds the `whoami_*` audience and scope definitions that were formerly passed to the `IDGeneratorResource`.
The `IDGeneratorResource` now depends on the new resource to obtain the client_identity.
It should be noted that the `whoami_*` audience and scope will be used to request a token only if no other token had yet been requested by the auth_adapter:
The `IDGeneratorResource` will wait until `subscriber()` is called for the first time before checking if `get_sub()` returns something.
> [uss_qualifier] new resource for cleanly exposing the client identity

- monitoring/monitorlib/fetch/__init__.py
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/set_uss_available.md
- monitoring/uss_qualifier/scenarios/astm/utm/set_uss_down.md
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This also adds some things we need:
- additional functions to query the DSS
- utility function to extract generically an error message from a query response
- generic test steps to change availability of an USS
> [uss_qualifier/scd] Add 'Down USS' scenario; SCD0005 requirement validation

- monitoring/monitorlib/geo.py
- monitoring/monitorlib/geo_test.py
- monitoring/prober/infrastructure.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/utils.py
- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_subscription_interactions.md
Extends `ISASubscriptionInteractions` generic scenario to include a subscription that only barely intersects with the ISA.
Note that this subscription's area is generated based on the configured ISA's area (see `generate_slight_overlap_area` in `common/dss/utils.py`). 
For ISA footprints that are a square or rectangle, the new test area is guaranteed to only share a single point with the footprint: if this is too restrictive, we can increase the overlap area.
If required, this new test area could also be added to the configuration instead of being generated, but we would then risk users to configure an area that would not respect the spirit of the test.
> [uss_qualifier] DSS0030 slight overlap subscription interactions

- monitoring/uss_qualifier/scenarios/documentation/parsing.py
In an attempt to write a new scenario by inheriting from another one, I bumped into the issue that the doc in the .md file would not be properly recognized by the test framework when both scenarios are invoked in a single test run.
That is due to the fact that as when the test framework loads the documentation, it caches it as an attribute of the scenario's class. However if scenarios inherit from each other this mechanism does not work well. Making the attribute name depends on the scenario's class name is an easy fix to that issue.
> [uss_qualifier] Make scenario doc cache attribute name depend on scenario name

- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
This fixes an error similar to the one fixed by #371. When a test fails on the new test step for flight planning, the message is not formed properly, breaking the html report.
> [uss_qualifier] Fix error breaking test report

- monitoring/uss_qualifier/scenarios/scenario.py
When recording a note, the default behavior is to override any note that potentially has the same key.
This PR changes that by detecting such cases and automatically adding a suffix to the key in order to not lose notes that way.
> [uss_qualifier] Add suffix for notes with duplicated keys

- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
This should fix #387 if my hypothesis is correct
> [uss_qualifier/utm/OpIntentValidator] Fix corner-case handling when op intent is expected to not be found

- monitoring/Dockerfile
Without these, building the Dockerfile locally fails with the error below when running `make format`, for example.
I assume it is a peculiarity of my ARM environment, or related to OS X. I seem to have this issue since the update to Python 3.11.
```
2.745 Collecting lxml==4.9.1 (from -r /app/monitoring/requirements.txt (line 26))
2.763   Downloading lxml-4.9.1.tar.gz (3.4 MB)
2.837      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 46.2 MB/s eta 0:00:00
2.963   Preparing metadata (setup.py): started
3.067   Preparing metadata (setup.py): finished with status 'error'
3.069   error: subprocess-exited-with-error
3.069   
3.069   × python setup.py egg_info did not run successfully.
3.069   │ exit code: 1
3.069   ╰─> [3 lines of output]
3.069       Building lxml version 4.9.1.
3.069 …
```
> [monitoring] install libxml2-dev libxslt-dev before pip install 

- monitoring/uss_qualifier/scenarios/scenario.py
A common problem in uss_qualifier is developers providing a single ParticipantID rather than a list of ParticipantIDs when initiating a check.  Since a ParticipantID is a string and a string is actually a list (of characters), this problem often goes unnoticed and participants are attributed as "u", "s", "s", and "1".  This is currently a problem both in an active PR and a PR that was merged (was not caught in review).
This PR fixes that problem by allowing either a single ParticipantID or a list of ParticipantIDs to be provided, and treats either correctly.  It also does the same for requirements where the same problem sometimes occurs.
> [uss_qualifier] Relax type requirements when performing test checks

- monitoring/prober/infrastructure.py
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/configurations/dev/message_signing.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/resources/flight_planning/flight_intents_resource.py
- monitoring/uss_qualifier/run_locally.sh
- monitoring/uss_qualifier/scenarios/astm/utm/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_access_control.md
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_access_control.py
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.yaml
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.md
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
This is a first version for a scenario to validation OPIN0035 (DSS only allows owners of an op-intent to modify or delete it).
Among the things that need to be clarified, improved (and possibly completed), whether in this PR or in a follow-up:
* should we start a `DSSWrapper` for the `scd` part, similarly to the wrapper we had for `remoteid`, that takes care of repetitive checks and recording queries?
* Notifications are not currently handled by the scenario: assuming we build a `DSSWrapper`, I'd expect that sending out notifications would be handled there, similarly to [how it's done for ISA's](https://github.com/interuss/monitoring/blob/5b4bd9e24abc4886641979ba11978f5f4010b425/monitoring/monitorlib/mutate/rid.py#L258). Or do we ignore that for now?
* Currently the scenario documentation …
> [uss_qualifier] first DSS op-intents ACL validation

- monitoring/uss_qualifier/scenarios/astm/utm/aggregate_checks.md
- monitoring/uss_qualifier/scenarios/astm/utm/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Extends the `f3548` aggregate check to look for queries that interact with the test instance in order to validate requirement n° GEN0300.
If no interaction is found, the check is skipped. 
Otherwise, the check is reasonably lax: for each possible interaction with the test endpoint, it is enough to have a single successful query to pass.
> [uss_qualifier] f3548 - GEN0300 verify interactions with interoperability test instance

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
As pointed out in #396, we want to use the constants defined by the standard for the API paths and operations.
This updates `monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py` to do so.
> [uss_qualifier] have f3548/v21/dss.py rely on standard constants

- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
Currently, F3548-related test configurations cannot be run without providing a mock_uss instance.  It should be possible to still run most of the test without a mock_uss instance, so that resource should be optional.  This PR makes that change and enables F3548-related test configurations that do not provide a mock_uss instance.
> [uss_qualifier] Allow mock_uss to be omitted from F3548-related test configurations

- monitoring/uss_qualifier/requirements/astm/f3548/v21.md
- monitoring/uss_qualifier/scenarios/astm/utm/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.md
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This PR:
* Splits the `DSS0005` requirement into each of the 5 sub-items that it contains
* Note that `DSS0005` can still be referenced directly, as certain checks seem very coarse grained and it is not possible to attribute them to one of the sub-items – I guess this should be improved but is not in the scope of this PR)
* Makes the documentation more precise by properly calling what we are creating on the DSS an "Operational Intent Reference" and not an "Operational Intent"
> [uss_qualifier] improve documentation for op intent reference ACL validation

- monitoring/uss_qualifier/scenarios/scenario.py
This fixes #408 if what I wrote in https://github.com/interuss/monitoring/issues/408#issuecomment-1857588431 is acceptable.
> [uss_qualifier] Do not upgrade Low severity failures to Critical

- monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/flight_planning/prioritization_test_steps.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
The objective is to display more appropriate/specific summary and details when failing a check with a low severity.
Additionally fix a tiny bug in `expect_flight_intent_state`.
This PR might be enough to address #398.
> [uss_qualifier/flight_planning/submit_flight_intent] Factor out test step boundaries and specific failed checks

- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
This fixes a bug I noticed recently in the *Attempt to modify activated flight in conflict* test case.
> [uss_qualifier/utm/conflict_higher_priority] Fix flight 1 sharing expectation

- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_expiry.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/misbehavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/utm/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss_interoperability.py
#403 removed the complexity of allowing `record_failed` invocations to override the participants specified when initiating the `check`.  However, the method I used to try and find all the existing `record_failed` invocations that specified `participants=` was not effective as I missed many places.  This has caused a failure in [CI for an open PR](https://github.com/interuss/monitoring/actions/runs/7228920476/job/19699095241?pr=376), making it more difficult to identify the root cause of that failure.  This PR attempts to clean up the remaining locations.
I identified the locations in this PR by searching all files for instances of `participants=` and manually evaluating each instance before removing it.  I attempted to remove an instance of `participants=` specification only if 1) it was …
> [uss_qualifier] Remove lingering participants= in record_failed

- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
As part of #380, this PR extracts `begin_test_step` and `end_test_step` from the reusable functions in ASTM UTM's test_steps.py (but not OpIntentValidator; that will be a larger project)
> [uss_qualifier] Remove begin and end test step from reusable functions in test_steps

- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/requirements/uspace/article8.md
- monitoring/uss_qualifier/scenarios/uspace/netrid/msl.md
- monitoring/uss_qualifier/scenarios/uspace/netrid/msl.py
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/network_identification.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.md
According to ASTM's mapping of U-space Article 8 Network Identification, the one requirement not covered by the use of ASTM F3411-22a is provision of MSL altitude to authorised users (Article 8(2)(c)).  This PR adds documentation for a test scenario specific to U-space to verify compliance to that requirement along with a blank implementation, and adds that scenario to the U-space Network Identification Service test suite.
> [uss_qualifier] Add U-space MSL test scenario

- monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
- monitoring/uss_qualifier/scenarios/flight_planning/prioritization_test_steps.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
- monitoring/uss_qualifier/scenarios/scenario.py
- monitoring/uss_qualifier/scenarios/uspace/flight_auth/validation.py
Similar to #417 and parts of #419, this PR works on #380 by pulling begin_test_step and end_test_step out of reusable functions and into the scenarios themselves for the functions in prioritization_test_steps.
> [uss_qualifier] Remove begin and end test step from prioritization_test_steps

- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.md
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
This adds an explicit check to `OpIntentReferenceAccessControl` to verify that the workspace is clean, and skip the scenario steps if it is not.
This also moves the `PrepareFlightPlanners` in front of `ForEachDSS` in the `f3548_21.yaml` test suite configuration, as the stray OIRs reported in #418 seem not to belong to the op intent reference ACL test scenario and there is a higher chance of them getting cleaned up this way.
(This scenario will attempt to cleanup up stray OIRs that seem to belong to the credentials that are being used, but it can't possibly clean up references that are owned by other credentials)
In the event of cleanup failure, the scenario has been updated to simply skip all further checks.
> [uss_qualifier] op-intent refs ACL checks: skip scenario if references can't be cleaned up (fix #418)

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/invalid_op_test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/plan_flight_intent_expect_failed.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/query_mock_uss_interactions.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_get_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_no_notification_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_notification_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_sharing_operational_intent_but_with_invalid_interuss_data.md
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
This PR cleans up a few things in the [Data Validation of GET operational intents by USS test scenario](https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md):
1. `begin_test_step` and `end_test_step` are removed from reusable test step fragments per #380
2. `control_uss` is changed to `mock_uss` because we know that resource is a mock USS, so therefore there is no difference between control_uss and mock_uss, and one consistent name is easier to comprehend
3. The test step to check for notifications is moved to just before its outcome is needed
4. The purpose of the test step to check for notifications is clarified
5. Redundant explanation of the Validate flight2 GET interaction test step is removed …
> [uss_qualifier] Clean up get op data validation scenario

- requirements.txt
This should fix #329 and was obtained through a few iterative updates (it was not immediately obvious to me that the transitive dependencies with a pinned version could simply be removed)
Note that this removes the explicit version pinning of `Werkzeug`, `Jinja2` and `itsdangerous`.
If we need to pin transitive dependencies (which is a generally good idea) I'd suggest looking into something such as [pip-tools](https://github.com/jazzband/pip-tools) (or rolling our own crude version pinning with eg `pip freeze`).
However, there is no urgency with this, as long as dependency management does not start taking too much time.
> [deps] update flask to latest version

- monitoring/uss_qualifier/suites/astm/utm/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/suite.py
#406 attempted to allow mock_uss to be omitted from certain test suites, but it did not ensure that actions within those test suites wouldn't be skipped even when the omitted resource was optional.  This PR fixes that oversight and verifies that omitting mock_uss and second_utm_auth only skips the scenarios that actually need those resources by (temporarily) commenting out the mock_uss and second_utm_auth resources in the f3548_self_contained configuration.
> [uss_qualifier] Fix optional resources mock_uss and second_utm_auth

- monitoring/mock_uss/database.py
- monitoring/mock_uss/scd_injection/routes_injection.py
- monitoring/mock_uss/server.py
- monitoring/monitorlib/errors.py
- monitoring/monitorlib/fetch/__init__.py
- monitoring/monitorlib/idempotency.py
- monitoring/uss_qualifier/main.py
- monitoring/uss_qualifier/reports/report.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/misbehavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/nominal_behavior.py
As evidenced by #367, we call `traceback.format_exception` in a number of different places in our codebase to construct a stracktrace string.  Prompted by some mysterious observed exceptions, this PR makes a single `stacktrace_string` function that everywhere else in the codebase references, and that function is the only place that calls `format_exception` (this would have made #367 easier had it already existed).
While trying to reproduce the issue, I also discovered misbehavior when returning a tuple from idempotent handlers so this PR fixes that issue as well.
Finally, the codebase information is printed to console to help debug problems like this in the future.
Observed logs, lightly redacted:
```
2023-12-19 11:16:04.381 | INFO     | __main__:main:185 - ========== Running …
```
> [uss_qualifier] Centralize traceback.format_exception call

- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
Two methods in OpIntentValidator with Optional arguments do not have a default value. Setting their default value to None.
> [uss_qualifier] Set default value of optional args in OpIntentValidator methods

- monitoring/monitorlib/errors.py
- monitoring/uss_qualifier/scenarios/scenario.py
Currently, the only mechanism we have to ensure that a query isn't recorded in a test report more than once is correctness of all calling code.  This PR introduces a loud warning message on the console if and when a query is recorded multiple times, but it stops short of aborting test execution.  This should allow us to easily detect if this happens in the future.  I don't believe it happens currently, though I have not performed an exhaustive search.
> [uss_qualifier] Identify duplicate record_query calls

- monitoring/monitorlib/clients/flight_planning/client_v1.py
- monitoring/uss_qualifier/resources/flight_planning/flight_planner.py
Fixes #438.
One question is whether to specify None, specify Unknown, or omit the argument when constructing the result when the client's response did not include a value.  I believe all three options are essentially interchangeable for the purpose of processing the result, so I chose the option that made the resulting value more concrete.
> [uss_qualifier] Check for presence of `includes_advisories` before accessing field

- monitoring/deployment_manager/actions/test/hello_world.py
- monitoring/mock_uss/flights/planning.py
- monitoring/mock_uss/ridsp/behavior.py
- monitoring/monitorlib/delay.py
- monitoring/prober/rid/v1/test_isa_expiry.py
- monitoring/prober/rid/v2/test_isa_expiry.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_expiry.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/netrid/virtual_observer.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
- monitoring/uss_qualifier/scenarios/dev/noop.py
Our CI is an extremely valuable tool, but it already takes 15-20 minutes to run and we will want to add more checks to it as we develop more tools.  Therefore, it will be valuable to pay attention to the time we are spending to verify functionality.  We currently have a number of places where we sleep, usually to wait for something to happen.  This PR ensures those places are visible and well-justified by replacing all instances of `time.sleep` with a custom `sleep` function that requires specification of a reason.  In the future, we could also use this function to evaluate how much of the total CI time is spent merely sleeping.
> Sleep loudly

- monitoring/monitorlib/fetch/__init__.py
- monitoring/uss_qualifier/reports/sequence_view.py
- monitoring/uss_qualifier/reports/templates/sequence_view/overview.html
- monitoring/uss_qualifier/reports/templates/sequence_view/scenario.html
- monitoring/uss_qualifier/reports/templates/sequence_view/severity.html
- monitoring/uss_qualifier/reports/templates/sequence_view/style.html
- monitoring/uss_qualifier/scenarios/documentation/parsing.py
- monitoring/uss_qualifier/suites/suite.py
This PR partially addresses #409 via the low-hanging fruit of different console messages and sequence view artifact renderings of low-severity "failed checks".
It also cleans up sequence view artifacts by making the style reusable and fully collapsing query information by default.
A scenario documentation parsing bug is fixed and the default string representation of QueryType is changed to be the fully-qualified value, which should be more clear to user readers.
> [uss_qualifier] Improve severity treatment in sequence view artifact

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/remove_op_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
- monitoring/uss_qualifier/scenarios/astm/utm/prep_planners.md
- monitoring/uss_qualifier/scenarios/astm/utm/prep_planners.py
Currently, uss_qualifier often prepares a clean workspace by having all the flight planners remove flights from test areas.  If a previous test run did not end cleanly, there may also be dangling operational intents managed by uss_qualifier in the test areas, however, and these operational intents will not be removed by any of the USSs (because they do not manage them).  This PR adds a test case to the preparation scenario to remove uss_qualifier's operational intents from the test areas if they exist.  It was tested at development time by artificially adding a uss_qualifier operational intent at the beginning of the scenario.
> [uss_qualifier] Clean uss_qualifier op intents at prep time

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
> [uss_qualifier] Fix variable name in check failure message

- monitoring/monitorlib/inspection.py
- monitoring/uss_qualifier/action_generators/astm/f3548/for_each_dss.py
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/resources/communications/auth_adapter.py
- monitoring/uss_qualifier/resources/versioning/client.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
- monitoring/uss_qualifier/scenarios/astm/utm/prep_planners.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
Following #449, this PR explicitly specifies scopes needed and used with regard to F3548-21 and InterUSS versioning.  The F3548 scopes are almost all used through a "DSSInstance"<sup>1</sup>.  The primary change in this PR is to make it so that obtaining a DSSInstance from a DSSInstanceResource requires the user (usually a test scenario) to specify which scopes they need to use, and then the DSSInstance obtained will refuse to perform operations that require any other unrequested/undeclared scopes.  The declaration of scope usage throws a MissingResourceError if the required scopes aren't available, and this allows test scenarios that require scopes that aren't available to merely be skipped (similar to #449).
While the "standard" dev library resources have all scopes granted, …
> [uss_qualifier] Specify F3548  and versioning scopes explicitly

- github_pages/static/index.md
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
This PR updates the f3548_self_contained CI configuration to generate two tested requirements reports reflecting a simple SCD-only (no CMSA, no constraints, no availability arbitration) activity in multiple phases.  This change will allow us to better target and measure MVP success in #274 and #434.
> [uss_qualifier] Update f3548_self_contained tested requirements

- Makefile
Adds a simple but frequently used combination of make targets to the root `Makefile`: 
`restart-all` makes sure everything is shut down, then starts it again.
This is useful especially when iterating on the DSS or other services that the qualifier depends on to run.
> [make] add a 'restart-all' make target for ease of development iteration

- monitoring/prober/scd/test_operations_simple.py
Discovered that this test was not using the correct version for attempting to delete a subscription.
This was working as long as the DSS was not taking the version into account: with the fix being worked on [here](https://github.com/interuss/dss/pull/986) this will no longer work and we will get a different 4XX code.
The current fix will tolerate both the 400 and 409 outcome so that we may gracefully swap the DSS instance that is used without breaking the test.
> [prober] lookup and specify correct subscription version in deletion test

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
Upon further review of requirements for which that InterUSS could provide automated testing in basic SCD usage, OPIN0005 and OPIN0010 were better verified by the USS performing aggregate conformance monitoring themselves.  Therefore, these two requirements are no longer considered necessary automated tests for [basic SCD automated testing](https://github.com/interuss/monitoring/issues/470).  Since f3548_self_contained is currently attempting to reflect those requirements, this PR removes those two requirements from the tested requirements artifact generated.
> [uss_qualifier] Remove OPIN0005 and OPIN0010 from f3548_self_contained

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/requirements/astm/f3548/v21.md
- monitoring/uss_qualifier/requirements/astm/f3548/v21/dss_provider.md
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/set_uss_available.md
- monitoring/uss_qualifier/scenarios/astm/utm/set_uss_down.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
We want DSS0100 as part of the early MVP, and the first part of the requirement (DSS0100,1) is already implemented.
However, DSS0100,2 is not. This PR splits them so we don't loose track of DSS0100,2.
> [uss_qualifier] split scd DSS0100 requirement into its two components

- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
This addresses partially #447 so that a failure in the deletion interrupts the test execution.
Additionally, this transitions the down_uss scenario to using the icons for setting the severity of the checks.
> [uss_qualifier/scenarios/utm/down_uss] Set severity of op intent deletion failure in cleanup to high

- monitoring/uss_qualifier/reports/tested_requirements.py
Since the purpose of automated testing is to verify compliance of a system to requirements, it is often important to know which system was tested to comply with the requirements (or not).  This PR fulfills a customer request to include the system version for each participant (when known) in the status.json programmatic summary of the tested requirements artifact.
> [uss_qualifier] Add participant's system version to tested requirements status summary

- monitoring/monitorlib/geo.py
- monitoring/monitorlib/kml.py
- monitoring/uss_qualifier/configurations/configuration.py
- monitoring/uss_qualifier/reports/artifacts.py
- monitoring/uss_qualifier/reports/sequence_view/generate.py
- monitoring/uss_qualifier/reports/sequence_view/kml.py
- monitoring/uss_qualifier/reports/sequence_view/summary_types.py
- monitoring/uss_qualifier/reports/templates/sequence_view/scenario.html
- monitoring/uss_qualifier/test_data/make_flight_intent_kml.py
- schemas/monitoring/uss_qualifier/configurations/configuration/SequenceViewConfiguration.json
The sequence view artifact is proving useful in debugging test failures, but one shortcoming is that it is hard to verify geospatial behavior (e.g., "Did the other operational intent actually intersect my operational intent?").  This PR addresses that shortcoming by (optionally) generating a KML file per test scenario in the sequence view artifact where certain geospatial-related queries made during the test scenario are visualized.  Not all visualizable query types are actually visualized in this PR as it is already very large, but the framework should be in place to visualize more query types easily in future PRs when the need arises.
I'm hoping this otherwise-large PR can be feasibly reviewed by looking at the CI-generated KML first -- assuming that looks good, the logic can probably …
> [uss_qualifier] Add KML visualization to sequence view artifact

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/definitions.py
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
- schemas/monitoring/uss_qualifier/suites/definitions/TestSuiteDefinition.json
System version information is important for a number of reasons in automated testing.  First, it serves to identify the system that was actually tested (and therefore what system actually passed the tests, when that occurs).  Second, F3548-21 GEN0305 specifies "An interoperability test instance shall (GEN0305) use the currently deployed version of the implementer’s USS software except when testing an update to the implementer’s USS software."  Therefore, knowing the version of the software under test as well as the "currently deployed" version of the software is needed to satisfy this requirement.
This PR adds a system version retrieval test scenario to the F3548-21 test suite to begin to address GEN0305 (per #467), as well as enabling reporting of the system version tested in tested …
> [uss_qualifier] Query participants for test environment system versions in F3548-21

- monitoring/mock_uss/deployment/gcp/kubernetes-deployment.md
- monitoring/mock_uss/deployment/gcp/mockuss.example.yaml
Since mock_uss is needed for some automated tests, test environments may need to deploy an instance outside a simple local test environment.  These instructions show one tested deployment approach using Google Kubernetes Engine.
> [mock_uss] Add instructions for mock_uss deployment via GKE

- monitoring/prober/infrastructure.py
The [DSS fix](https://github.com/interuss/dss/pull/996) that will start checking for correct v4 UUID (as specified in [RFC 4122](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.1)) requires us to update the ID generation for the prober and the qualifier.
The chosen approach is to save one hex character less from the `owner_id` field and replace it with the static `8`. An alternative would be to shorten the reserved `0000` field and the end of IDs.
> [prober/qualifier] make IDFactory generate correct v4 UUIDs

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/requirements/astm/f3548/v21.md
- monitoring/uss_qualifier/requirements/astm/f3548/v21/dss_provider.md
Separates the `DSS0210` requirement into its sub-components.
This should both help us keep track of progress and give more detailed information to testers when scenarios fail, as `DSS0210` will combine various testing approaches and might be spread across several scenarios.
> [spec] split astm f3548 requirment dss0210 further into sub-specs

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
- monitoring/uss_qualifier/scenarios/astm/utm/prep_planners.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
Regarding issue #458 
Continuation of #483
> [uss_qualifier/resources/f3548/dss/find_op_intent] Use QueryError for error handling

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
Regarding issue #458
Continuation of #483, #496
> [uss_qualifier/resources/f3548/dss/get_op_intent_reference] Use QueryError for error handling

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
Regarding issue #458
Fix PR #483 where I forgot some things
> [uss_qualifier/resources/f3548/dss/delete_op_intent] Fix use of QueryError for error handling

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
Regarding issue #458
Continuation of #483, #496
> [uss_qualifier/resources/f3548/dss/get_op_intent_telemetry] Use QueryError for error handling

- monitoring/uss_qualifier/reports/sequence_view/kml.py
- monitoring/uss_qualifier/reports/tested_requirements.py
This PR fixes two issues blocking usage of uss_qualifier in a particular application:
1. When the scenario to query system versions is run but there are no participants, report generation crashes.  This issue is fixed by checking whether the `notes` field is present before trying to access it.
2. KML generation was broken for a renderer that wanted just the response of the query.  This issue is fixed by correcting an incorrect field name reference.
> [uss_qualifier] Fix bug in version detection and quiet unnecessary warning message

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
> [uss_qualifier/resources/f3548/dss/get_full_op_intent] Use QueryError for error handling

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
> [uss_qualifier/resources/f3548/dss/put_op_intent] Use QueryError for error handling

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
> [uss_qualifier/resources/f3548/dss/set_uss_availability] Use QueryError for error handling

- monitoring/monitorlib/schema_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_validator.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/validate_subscription.md
Create a `SubscriptionValidator` class that wraps the checks for content and structure of subscriptions returned by the DSS.
This also migrates the existing `subscription_simple` scenario to it.
(Includes the commit from #492 to make the validation pass, should thus be merged afterwards)
> [uss_qualifier] create a SubscriptionValidator for scd subscriptions

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss_interoperability.py
Don't attempt to notify the short-lived subscriptions that the `dss_interoperability` scenario created, as these result in requests to `example.com` that time out and cause the scenario's assumptions to break.
(This uses the recently introduced `do_not_notify` parameter.)
This also updates the dummy `uss_base_url` from `example.com` to `example.interuss.org` to take a step forward regarding #275 
Evidence this seems to work:
- this PR seems to pass (tried multiple times)
- #512 passed when rebased on this
- #514 passed when rebased on this
See #517
> [uss_qualifier/scenarios/netrid/dss_interoperability] Avoid timeouts in notifications to dummy subscriptions

- monitoring/prober/infrastructure.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/subscription_crud.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/subscription_sync.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_synchronization.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_synchronization.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/validate_subscription.md
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
First pass at verifying DSS0210: currently this only focuses on subscriptions (DSS0210,1).
It willing ignores the following:
-  manager/access-rights of the subscription
-  area of the subscription
These will be added in later PRs.
This PR also includes a new `crud_subscription.md` documentation fragment to avoid duplication. Existing scenarios that could profit from it will be migrated after this PR lands.
(Built on top of #490, as long as that PR is open make sure to only look at the last commit of this PR)
> [qualifier] DSS0210,1 – add initial inter-DSS subscription synchronization scenario

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/op_intent_ref_access_control.py
- schemas/monitoring/uss_qualifier/resources/astm/f3548/v21/dss/DSSInstanceSpecification.json
Some USS requirements in F3548-21 are enforced by the DSS instance a USS uses.  For instance, the DSS should prevent modification or deletion of operational intent references that a USS doesn't manage, per OPIN0035.  Also, the DSS should prevent creation or modification of an operational intent in a state other than Accepted if the managing USS doesn't have a subscription, [per SCD0080](https://github.com/interuss/monitoring/issues/466#issue-2077443460).
This PR adds information about the users of an F3548 DSS instance so their compliance to DSS-enforced requirements can be recorded, and uses that information in an existing scenario to record OPIN0035 compliance for those users.
> [uss_qualifier] Add USS credit for requirements enforced by DSS

- monitoring/uss_qualifier/scenarios/astm/netrid/common/aggregate_checks.py
- monitoring/uss_qualifier/scenarios/astm/utm/aggregate_checks.py
The unbounded precision on some of our report messages was distractingly large and far beyond the true precision of our knowledge (e.g., "checked performances on 5 queries, 95th percentile: 0.44880650000000005s" -- we have no confidence in the femtosecond range).  This PR adjusts the report messages to more accurately convey the true significant figures of the metrics.
> [uss_qualifier] Limit precision of aggregate computations in report messages

- monitoring/uss_qualifier/suites/definitions.py
- monitoring/uss_qualifier/suites/suite.py
This PR should fix #515.  The f3548_self_contained configuration was verified to correctly retrieve the system version for the default (local resource) system_identity, and the uspace configuration was verified to correctly retrieve the system version for the overridden (external resource) system_identity.  This behavior is visible in the GetSystemVersions test scenario in the F3548-21 test suite of the sequence view artifacts for these two configurations.
> [uss_qualifier] Fix test suite local resource override logic

- monitoring/uss_qualifier/reports/sequence_view/events.py
- monitoring/uss_qualifier/reports/sequence_view/generate.py
- monitoring/uss_qualifier/reports/sequence_view/summary_types.py
- monitoring/uss_qualifier/reports/templates/sequence_view/overview.html
Previously, the sequence view artifact did not display information about the actions in the cleanup phase of a test scenario.  This PR adds that missing information while refactoring the event computation code for clarity.
It also adds visible numbering to the scenarios on the sequence view index page.
> [uss_qualifier/reports] Add cleanup step to sequence view

- monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/test_steps/validate_notification_received.py
Found that the check `Tested USS receives valid notification` was getting skipped in the test step `Validate Flight 2 notification received by tested_uss`  for SCD0080 test case. This was due to the incorrect `if` statement, inside which the check was done.
Fixed the `if` statement. Verified that the report shows the check is being done.
> [uss_qualifier] Fix skipped check Tested USS receives valid notification

- monitoring/prober/scd/test_operations_simple.py
We're [updating the DSS](https://github.com/interuss/dss/pull/1006): the change is about the validation of the `key` field of requests for updating an operational intent reference.
Currently, when an OIR is updated, the DSS will expect the OVN of that OIR to be passed in the `key` field. This contradicts the [specification](https://github.com/astm-utm/Protocol/blob/cb7cf962d3a0c01b5ab12502f5f54789624977bf/utm.yaml#L745C27-L746C46), so required a DSS update.
This PR updates the prober (which was correctly testing the previous behavior) for it to accept the new behavior.
This should be compatible with the current and upcoming version of the DSS (it was tested against the new one already)
> [prober] update prober to support next DSS version

- monitoring/monitorlib/fetch/__init__.py
A `QueryError` often wrap a single query, of which it is common to check the status code.
Additionally, when a check fails, we're interested in the wrapped queries' timestamps.
This PR adds a `last_status_code` and `query_timestamps` method to `QueryError` to make these use cases easier.
> [uss_qualifier] add utility properties to QueryError

- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/sub/sync.md
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
DSS0215 (Write to DAR before returning to caller) and DSS020 (access to any DSS yields same results) can easily be partially covered by the existing subscription synchronization check.
This covers the 'broadcast' part (write on main, query secondaries) of the subscription synchronization checks.
Missing coverage is tracked in #434
> [uss_qualifier] check off DSS0215 and DSS020 for subscriptions (partial)

- monitoring/mock_uss/f3548v21/flight_planning.py
Before that the mock USS would leave this check to the DSS and just fail the request.
> [mock_uss/f3548v21/flight_planning] Validate operational intent are not in the past

- monitoring/monitorlib/schema_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/create.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/delete.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/read.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/update.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/sync.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/validate/correctness.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/validate/mutated.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/validate/non_mutated.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/validators/oir_validator.py
This adds test step fragments related to Op Intent References in the context of DSS0210,2 (OIR synchronization)
These will be used for the actual scenario implementation being added in #530
> [uss_qualifier] fragments+validation code for operational intent references (CRUD & synchronization)

- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
- monitoring/uss_qualifier/scenarios/scenario.py
This will be useful as I'm adding test step fragments that declare flights non-conforming and contingent, which both require CMSA role. If the USS is not CMSA, it will return that this is not supported, and in that case we will want to skip the check, without failing or passing it.
> [uss_qualifier/scenarios/flight_planning] Enable skipping check if USS indicates NotSupported

- monitoring/uss_qualifier/scenarios/flight_planning/prioritization_test_steps.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
Useful for the test step fragments I'm adding that will use FlightInfo format.
> [uss_qualifier/scenarios/flight_planning] Enable expect_flight_intent_state to validate FlightInfo format

- monitoring/prober/infrastructure.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/oir_api_validator.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/clean_workspace.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/create.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/create_format.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/update.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/update_format.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_access_control.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
Extend the authentication checking scenario to include the OIR endpoint.
> [qualifier] DSS0210,A2-7-2,7 validate authentication for OIR CRUD+search endpoints

- monitoring/uss_qualifier/resources/astm/f3411/dss.py
When defining non-local (has_private_address=false) instances of the DSS, the default value of local_debug is not honored.
This PR fixes it.
> [uss_qualifier] Fix local_debug default value

- monitoring/uss_qualifier/resources/interuss/crdb/crdb.py
To test the security of cockroach db nodes, the test scenario uses the default user name picked by the python library. When running the test suite on Mac, the docker container tries by default to pick uid 501 which crashes the execution on the client side.
This PR fixes this problem by specifying a user name.
Example of failed check:
```
New failed check:
details: 'Error message: connection is bad: local user with ID 501 does not exist'
documentation_url: https://github.com/interuss/monitoring/blob/c1a198d79e104417e1456c5eb7da82cdfe964027/monitoring/uss_qualifier/scenarios/astm/utm/dss/crdb_access.md#node-is-reachable-check
name: Node is reachable
participants:
- uss1
requirements: []
severity: High
summary: Node is not reachable
timestamp: '2024-03-21T15:19:21.665883Z'
```
> [uss_qualifier] Cockroach node tests: specify db user

- monitoring/monitorlib/schema_validation.py
Required by some open/draft PRs being worked on in parallel
> [uss_qualifier] add schema paths for op intent ref. entities to schema validation

- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/subscription_synchronization.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/subscription_synchronization.py
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.yaml
Indirectly check that the manager of a subscription is synchronized across a DSS deployment by attempting to delete the a subscription from a DSS to which the subscription was synchronized to, using separate credentials. 
Note that this only checks the case where the wrong credentials are used: confirming that deletion through any DSS works will be added with #550 
Resolves #548
> [uss_qualifier] DSS0210,1b confirm subscription manager is synced

- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/read.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/search.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/sub/crud/read.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/sub/crud/search.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/subscription_synchronization.md
The `oir/crud/read.md` and `oir/sub/read.md` fragments contain checks related to search that are not always run by any scenario importing the fragments, which is something we want to avoid.
This splits the _search_ specific parts of the fragment into a separate file.
> [uss_qualifier] split scd read fragments that have checks related to search

- monitoring/mock_uss/docker-compose.yaml
- monitoring/mock_uss/templates/tracer/base.html
- monitoring/mock_uss/templates/tracer/logs.html
- monitoring/mock_uss/templates/tracer/observation_area_ui.html
- monitoring/mock_uss/templates/tracer/observation_areas_ui.html
- monitoring/mock_uss/tracer/observation_area_operations.py
- monitoring/mock_uss/tracer/observation_areas.py
- monitoring/mock_uss/tracer/routes/observation_areas.py
- monitoring/mock_uss/tracer/routes/ui.py
- monitoring/mock_uss/tracer/tracerlog.py
- monitoring/mock_uss/tracer/ui_auth.py
- requirements.txt
There is an upcoming need to use the tracer functionality of mock_uss in a non-development environment.
Currently, the tracer UI & management endpoints are unprotected with the idea that it will only be used in development environments.  This PR primarily protects all of tracer's unprotected endpoints with HTTP Basic auth.  No session management is implemented as most modern browsers will cache credentials and reuse them on calls to other resources on the server (verified with Chrome).
Also, deployment will likely be [via Kubernetes](https://github.com/interuss/monitoring/blob/main/monitoring/mock_uss/deployment/gcp/kubernetes-deployment.md), so the tasks previously performed via command line directly in a VM need to be performable via the external interface now.  So, downloading of all …
> [mock_uss/tracer] Add auth and log management to tracer

- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
Messages were always displayed as "no notes" when notes were, in fact, available.  I think this may have been due to operator precedence while using the ternary operator.  This PR should hopefully fix that problem by making the logic a bit clearer, though it is difficult to test effectively.
> [uss_qualifier] Fix "no notes" messages

- monitoring/monitorlib/kml/__init__.py
- monitoring/monitorlib/kml/f3548v21.py
- monitoring/monitorlib/kml/flight_planning.py
- monitoring/monitorlib/kml/generation.py
- monitoring/monitorlib/kml/parsing.py
- monitoring/uss_qualifier/reports/sequence_view/kml.py
- monitoring/uss_qualifier/resources/netrid/simulation/kml_flights.py
- monitoring/uss_qualifier/test_data/make_flight_intent_kml.py
Previously, there was only a single kml.py in monitorlib to handle KML operations.  This PR refactors that single file into multiple files to prepare for the addition of new content in a more sustainable manner.
Some KML generation logic previously only found in sequence view generation is moved to general KML routines for future reuse.
KML generation in sequence view is slightly changed.  First, more errors are caught and handled in a generic fashion (so catching problems with the area_of_interest field no longer needs to be specifically performed), and second, the console warning about not being able to generate a particular element is removed.  This is because there are (and will continue to be) places where generation intentionally cannot be accomplished (specifically: when there is …
> [monitorlib] Refactor KML routines

- monitoring/mock_uss/server.py
- monitoring/mock_uss/tracer/README.md
- monitoring/mock_uss/tracer/log_types.py
- monitoring/mock_uss/tracer/routes/__init__.py
- monitoring/mock_uss/tracer/routes/observation_areas.py
- monitoring/mock_uss/tracer/routes/rid.py
- monitoring/mock_uss/tracer/routes/scd.py
- monitoring/mock_uss/tracer/routes/ui.py
- monitoring/mock_uss/tracer/subscriptions.py
- monitoring/mock_uss/tracer/tracer_poll.py
- monitoring/mock_uss/tracer/tracerlog.py
As both a legacy cleanup and preparation for additional tracer capabilities, this PR strongly-types the log entries that tracer writes to disk.  These new types are defined in log_types.py, and behaviors and properties specific to a particular log type are collected there as well.
A few additional tracer cleanup items are completed as well.
> [mock_uss/tracer] Strongly-type tracer log entries

- build/dev/docker-compose.yaml
- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/report.py
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.yaml
This PR enables the check verifying DSS0100,2 and switch the DSS to v0.13.0 since it serves the valid new endpoint.
Note that the first commit demonstrate the failing test on v0.12.0 and the second commit upgrades the DSS version, which successfully pass the test.
> [uss_qualifier] DSS0100,2 - Enable check of makeDSSReport and upgrade dss to v0.13.0

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
The f3548_self_contained CI configuration attempts to capture a representative test and requirements for basic SCD deployment, and that basic deployment doesn't include availability arbitration.  As such, the DSS tests for availability arbitration functionality are not within the scope of this configuration, so this PR removes them from the "Gate 3" tested requirements artifact.
> [uss_qualifier/configurations] Remove availability arbitration reqs from gate 3 req set

- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
Currently, OpIntentValidator will produce a note when exiting its context with an exception, but a common "exception" that is actually unexceptional is a QueryError.  Adding a note about this unexceptional exception is confusing in the report (see, e.g., event 57 in #609) because nothing exceptional has occurred, nor is any part of the testing apparatus broken.  In addition, reraising the exception in `__exit__` [should not be needed](https://docs.python.org/3.11/reference/datamodel.html#object.__exit__).  If a true exception occurs within OpIntentValidator's context, it should simply be propagated out of the context as will happen in the absence of `__exit__`.  Furthermore, OpIntentValidator itself should not log or note this exception because it may (likely is, in the case of …
> [uss_qualifier] Remove exception note

- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.py
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Build on top of the *Subscription and entity interaction* test scenario, extending an existing test case, to add checks for requirement DSS0210,A2-7-2,4c:
> Tests must demonstrate that a subscription can be created on any DSS instance in the DSS pool, [...] and notifications for the subscription are triggered when intersecting entities are [...] modified (<tt>DSS0210,A2-7-2,4c</tt>) to any DSS instance within the DSS pool.
~~This PR builds on top of #588, as such please only review commit 1be30d5dcc78be8820eda62a99cde8be05f47bf2 until rebased.~~ rebased.
> [uss_qualifier/scenarios/utm/dss/subscription_interactions] Add test of requirement DSS0210,A2-7-2,4c

- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.py
First round of checks regarding op-intent reference synchronization.
(This currently excludes DSS0210,2e which will come in a later PR, as well as constraint references, which will have their dedicated scenario)
> [uss_qualifier/scenarios/utm/dss/OIRSynchronization] DSS0210,2a-b-c-d-f: check OIR deletion propagation

- monitoring/uss_qualifier/configurations/configuration.py
- monitoring/uss_qualifier/configurations/dev/dss_probing.yaml
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/reports/tested_requirements/breakdown.py
- monitoring/uss_qualifier/reports/tested_requirements/generate.py
- monitoring/uss_qualifier/reports/tested_requirements/summaries.py
- schemas/monitoring/uss_qualifier/configurations/configuration/TestedRequirementsConfiguration.json
Currently, the tested requirements artifact is generated for each named participant.  When attempting to verify compliance with this artifact, that currently means that only one participant ID can be used for a participant, even if they have logically-separate components of their system.  Specifically, to be verified for both core USS requirements and DSS requirements, the same participant ID must be used for both the core and DSS portions of a USS's system.  This makes the sequence view artifact less readable because the core and DSS portions of the system are often distinctly different subsystems, so it would be nice to attribute problems to one subsystem or another.
This PR addresses this challenge by implementing optional "aggregate participants" for the tested requirements artifact. …
> [uss_qualifier/reports] Add aggregate participants to tested requirements

- github_pages/static/index.md
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
Especially with the completion of #470, the f3548_self_contained CI configuration can be improved; this PR attempts to make those improvements.
The gate1 tested requirements artifact is removed now that ability to verify gate3 is achieved.  The ancillary requirements necessary for confident verification of gate3 are added explicitly.
All of the "environment" portions of the configuration are collected into a contiguous section, and that section is labeled.
A few scattered minor fixes are made as well.
> [uss_qualifier] Clean up f3548 configuration

- monitoring/mock_uss/tracer/kml.py
- monitoring/mock_uss/tracer/log_types.py
- monitoring/mock_uss/tracer/routes/__init__.py
- monitoring/mock_uss/tracer/routes/observation_areas.py
- monitoring/mock_uss/tracer/routes/rid.py
- monitoring/mock_uss/tracer/routes/scd.py
- monitoring/mock_uss/tracer/routes/ui.py
- monitoring/mock_uss/tracer/subscriptions.py
- monitoring/mock_uss/tracer/tracer_poll.py
Following #612, this PR finishes KML generation for operational intents in tracer.  Primarily, the operational intent polling log message now contributes historical volume information.  The log entry data structures were previously missing actual timestamp information -- it was partially encoded into the file names, but this information was not complete when observation and generation spanned more than one calendar day -- so this PR adds a `recorded_at` field for all log entry data structures.  Due to the fairly absurd time required to load YAML using the native Python pyyaml loader, some performance metrics are added to historical KML generation and the YAML loader is switched to the C version.
> [mock_uss/tracer] Finish tracer KML generation for op intents

- monitoring/uss_qualifier/scenarios/interuss/flight_authorization/general_flight_authorization.md
- monitoring/uss_qualifier/scenarios/interuss/flight_authorization/general_flight_authorization.py
This PR applies a few cleanup items to the InterUSS general flight authorization scenario:
* Move severities into documentation and out of code
* Remove extraneous logging statements
* Change order of scenario events so queries are recorded before the checks that depend on them
> [uss_qualifier] Clean up general flight authorization scenario

- monitoring/uss_qualifier/scenarios/astm/utm/prep_planners.py
- monitoring/uss_qualifier/scenarios/flight_planning/__init__.py
- monitoring/uss_qualifier/scenarios/flight_planning/prep_planners.py
- monitoring/uss_qualifier/suites/documentation/format_documentation.py
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
This attempts to fix #620 by renaming the (possibly) colliding class names, in the off chance that it is what causes our bug (whether or not it is the root cause would still need to be determined. #628 shows that it is not specifically due to Python 11)
> [hygiene_check] try to reproduce and fix #620

- monitoring/Dockerfile
The Dockerfile build fails on an M2 laptop when running the `pip install` step:
When `pkg-config` is not installed:
```
error: pkg-config probably not installed: FileNotFoundError(2, 'No such file or directory')
```
Then, when `libhdf5-dev` is missing:
```
error: libhdf5.so: cannot open shared object file: No such file or directory
```
This fixes it for my environment, and I expect it to fix it for any arm64-based image.
> [build] fix Dockerfile to also build on ARM

- monitoring/mock_uss/templates/tracer/observation_areas_ui.html
Instead of hardcoding tracer observation duration to 1 hour, this PR enables the user to set this value.
> [mock_uss] Accept user input for observation duration

- monitoring/uss_qualifier/scenarios/interuss/flight_authorization/general_flight_authorization.py
- monitoring/uss_qualifier/scenarios/interuss/geospatial_map/geospatial_feature_comprehension.py
In InterUSS's general flight authorization and geospatial feature comprehension scenarios, test checks for dynamic test steps are generated programmatically from the scenario configuration.  Prior to this PR, the check severity was not populated from the prototype check -- this PR fixes that problem, and also copies TODO status in case any of the checks acquire a TODO label later.
> [uss_qualifier] Fix dynamic checks

- github_pages/static/index.md
- monitoring/mock_uss/geoawareness/routes.py
- monitoring/mock_uss/geoawareness/routes_geospatial_map.py
- monitoring/monitorlib/clients/geospatial_info/client.py
- monitoring/monitorlib/clients/geospatial_info/client_geospatial_map.py
- monitoring/monitorlib/clients/geospatial_info/querying.py
- monitoring/monitorlib/fetch/__init__.py
- monitoring/monitorlib/geo.py
- monitoring/monitorlib/geotemporal.py
- monitoring/uss_qualifier/configurations/dev/geospatial_comprehension.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/resources/geospatial_info/__init__.py
- monitoring/uss_qualifier/resources/geospatial_info/geospatial_info_providers.py
- monitoring/uss_qualifier/scenarios/interuss/geospatial_map/geospatial_feature_comprehension.md
- monitoring/uss_qualifier/scenarios/interuss/geospatial_map/geospatial_feature_comprehension.py
- schemas/monitoring/monitorlib/fetch/Query.json
- schemas/monitoring/uss_qualifier/resources/geospatial_info/geospatial_info_providers/GeospatialInfoProviderConfiguration.json
- schemas/monitoring/uss_qualifier/resources/geospatial_info/geospatial_info_providers/GeospatialInfoProviderSpecification.json
This PR implements minimal geospatial map querying in the geospatial feature comprehension scenario.  To do this, a generic geospatial info client is added along with one concrete implementation (the one that works with InterUSS's geospatial_map automated testing API).  This client is provided to the test scenario via a new geospatial info provider resource.  To allow the scenario to pass, a trivial implementation of the query endpoint is added to mock_uss.
querying.py contains API-agnostic data objects for geospatial information providers, similar to how the flight planner client supports (in an API-agnostic way) both the newer v1 flight_planner API and the legacy scd injection API.  The actual (current) structure of these data objects is mostly a direct copy of the geospatial_map API, …
> [uss_qualifier, mock_uss] Implement geospatial comprehension querying

- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/generic.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/oir_api_validator.py
Adds participant ID to various non-attributed checks in the SCD endpoint authentication scenario.
Every `.check` invocation in the `monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication` directory is now attributed.
resolves #642
> [uss_qualifier] SCD failed authentication response check properly attributes check

- monitoring/monitorlib/geotemporal.py
- monitoring/uss_qualifier/scenarios/astm/utm/flight_intent_validation/flight_intent_validation.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
- monitoring/uss_qualifier/test_data/che/flight_intents/invalid_flight_auths.yaml
- monitoring/uss_qualifier/test_data/flight_intents/standard/invalid_flight_intents.yaml
- monitoring/uss_qualifier/test_data/flight_intents/standard/non_conflicting.yaml
Add a check and raise if the flight intent that will be injected ends in the past, while also double the default duration for some configured `flight_intents` (see below for details)
This fixes #648 
- is this the correct place for checking the end time?
- is raising a `ValueError` the correct approach? 
- is the new default duration of 10 minutes reasonable? Or should we leave it unchanged, and instruct users to increase the duration if they run into the raised error?
Tested updating the default `duration` in [monitoring/uss_qualifier/test_data/flight_intents/standard/invalid_flight_intents.yaml](https://github.com/interuss/monitoring/blob/e29f1b847402d5061575f098e2695cd419b20a44/monitoring/uss_qualifier/test_data/flight_intents/standard/invalid_flight_intents.yaml#L29) to 5 seconds: …
> [uss_qualifier] submit_flight_intent test step raises if flight intent ends in the past

- monitoring/mock_uss/f3548v21/flight_planning.py
- monitoring/monitorlib/geotemporal.py
- monitoring/monitorlib/kml/generation.py
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html
- monitoring/uss_qualifier/scenarios/interuss/geospatial_map/geospatial_feature_comprehension.md
This PR fixes a few issues discovered while testing InterUSS's generic flight authorization and geospatial comprehension scenarios on user-provided configurations.
Primarily, it fixes the documentation of one of the checks to include the " check" suffix which is otherwise a breaking error (because the check doesn't get defined/recognized as a check).
Also, it cleans up the tested_requirements artifact slightly by not printing an empty list of other participants.
The bulk of the lines of code changed are dedicated to not throwing errors in mock_uss with unusual altitude specifications -- SFC rather than W84, and missing lower/upper altitudes.  A common theme was that InterUSS business geo objects all have defaults for their fields, so the proper check is for boolean equivalence of the …
> [mock_uss, uss_qualifier] Fix geospatial comprehension scenario

- monitoring/uss_qualifier/configurations/dev/library/resources.yaml
- monitoring/uss_qualifier/resources/flight_planning/flight_intent_validation.py
- monitoring/uss_qualifier/scenarios/flight_planning/prep_planners.py
- monitoring/uss_qualifier/test_data/flight_intents/standard/conflicting_flights.yaml
- monitoring/uss_qualifier/test_data/flight_intents/standard/flight_auths.yaml
- monitoring/uss_qualifier/test_data/flight_intents/standard/invalid_flight_intents.yaml
- monitoring/uss_qualifier/test_data/flight_intents/standard/non_conflicting.yaml
This PR band-aids #648 while a longer-term fix can be implemented.  The problem is that older scenarios are rendering flight intents from templates once at instantiation (which is at the beginning of the test run) and therefore time references like TimeOfEvaluation and StartOfScenario don't work (instead using StartOfTestRun instead).  This means that relatively short flights are entirely in the past when a long test run gets around to running the scenario in which they're used.
The long-term fix is to render FligthInfoTemplates just before usage (TimeOfEvaluation), but extending the duration of the flight intents should at least stop the flight end times from being in the past in the meantime.
> [uss_qualifier] Extend durations of standard flight intents

- monitoring/monitorlib/deprecation.py
- monitoring/uss_qualifier/resources/flight_planning/flight_intent.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
Some functionality in this repo is marked as deprecated with the idea that it shouldn't be used in new development, but it isn't worth the time right now to immediately remove existing usages.  This idea has not been sufficient to keep deprecated functionality from being used in new development, so this PR introduces programmatic assurance that deprecated functionality is not accidentally used in new development.  Functions marked deprecated with the new functionality may only be called from the specifically-enumerated list of legacy callers (function, file tuples) or else an exception is thrown.  For developers wanting to quickly start the deprecation process but don't have the time to identify all legacy callers, a lightweight version of this programmatic deprecation assertion is …
> [monitorlib, uss_qualifier] Add deprecation mechanism and apply to deprecated functionality

- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
- monitoring/uss_qualifier/scenarios/flight_planning/activate_priority_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_priority_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/modify_planned_priority_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/plan_priority_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/prioritization_test_steps.py
~~PR stacked on top of #664: please review only commit eeeb3582c173d6b021c5563ba3488ff4c42f13da~~ rebased
Note that this migrates the scenario, but also the directly related test step fragments.
Additionally, the severity is added in the checks of those test step fragments.
Note to reviewer: in this scenario there are some execution paths that are specific to some USS implementations. If one of those path is broken by those changes, this is likely to not be caught by the CI.
> [uss_qualifier/scenarios/utm/nominal_planning/conflict_higher_priority] Migrate scenario away from FlightIntent

- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.md
`DownUSSEqualPriorityNotPermitted` was missing some check severities: these were properly set in the test fragments, but not in the main documentation file.
(First step towards #670)
> [uss_qualifier] DownUSSEqualPriorityNotPermitted – set missing check severities

- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.md
This addresses the part of #670 related to checking the area has been cleared in the DownUSS and DownUSSEqualPriorityNotPermitted scenarios.
My best guess is that DownUSSEqualPriorityNotPermitted needs a clean area, because existing flights might have a conflicting priority and prevent the scenario from being properly executed.
As for DownUSS, it _might_ support having a non-empty area, but the additional test step having been added in the reused `_setup()` function in the DownUSS class (which DownUSSEqualPriorityNotPermitted inherits from), it currently also required a clear area.
> [uss_qualifier] down_uss scenarios properly check area has been cleared

- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/flight_planning/activate_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/modify_planned_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/plan_conflict_flight_intent.md
- monitoring/uss_qualifier/scenarios/flight_planning/prioritization_test_steps.py
~~PR stacked on top of #665: please review only commit 716b5faa98595e16a9dbca317fbdf9771c4346d6~~ rebased
Note that this migrates the scenario, but also the directly related test step fragments.
Additionally, the severity is added in the checks of those test step fragments.
Note to reviewer: in this scenario there are some execution paths that are specific to some USS implementations. If one of those path is broken by those changes, this is likely to not be caught by the CI.
> [uss_qualifier/scenarios/utm/nominal_planning/conflict_equal_priority_not_permitted] Migrate scenario away from FlightIntent

- monitoring/monitorlib/clients/flight_planning/flight_info.py
- monitoring/monitorlib/mutate/scd.py
- monitoring/uss_qualifier/resources/astm/f3548/v21/subscription_params.py
- monitoring/uss_qualifier/resources/flight_planning/flight_intent.py
- monitoring/uss_qualifier/resources/flight_planning/flight_intents_resource.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_access_control.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/subscription_synchronization.py
Currently, a number of uss_qualifier scenarios evaluate/generate timestamps upon scenario instantiation (which happens very close to the start of the test run) but the scenario doesn't run until much later (10-15 minutes).  This results in a number of problems, but one specific problem is that at least scenarios.astm.utm.dss.synchronization.SubscriptionSynchronization attempts to emplace a subscription in the DSS with an end time that is "far" in the past.  The DSS does not allow any subscription to be created whose start time is in the past, but has a [5 minute tolerance](https://github.com/interuss/dss/blob/8a1a5e902df1aec8050074e182c22613a81aaa87/pkg/scd/models/subscriptions.go#L21) regarding "now".  Because of the large gap between scenario instantiation and scenario execution, …
> [uss_qualifier] Fix subscription times

- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md
This adds a check that validates that the operational intent published to the DSS matches the user's flight intent.
> [uss_qualifier/scenarios/utm/validate_shared_operational_intent] Validate operational intent state

- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md
This check was at informational level probably because the response coming from USSes with the old SCD injection API could not successfully represent the off-nominal result, as such it appeared as if the flight intent was `InUse` rather than `OffNominal`.
This was (kinda) fixed in #680 (on which this PR is based on, so please consider only commit 4dbd67e for review), so now we can put this check as high severity as it should be.
> [uss_qualifier/scenarios/utm/conflict_equal_priority_not_permitted] Fix transition check: set severity to high

- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/sync.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.md
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
The scenario checking for operational intent scenario was not referencing some requirements that it implicitly covers.
Part of the effort tracked on #434
> [uss_qualifier] reference DSS0215 and DSS0020 (DAR sync & DSS consistency) in OIR sync documentation

- monitoring/uss_qualifier/automated_testing.md
In an attempt to provide greater clarity for discussions motivated by [this automated_testing_interfaces PR](https://github.com/interuss/automated_testing_interfaces/pull/19), this PR adds automated testing documentation around test sensitivity and what it implies for tests being "good enough", as well as documentation for the motivation to test a system as it will be deployed rather than with a lot of additional testing instrumentation internal to the system under test.
> [documentation] Add sensitivity and system encapsulation documentation

- monitoring/uss_qualifier/reports/templates.py
When executing run_locally script for uss_qualifier, syntax warning appears for an deprecated escape character was being used in uss_qualifier/reports/templates.py 
**Steps to reproduce the behavior**
1. Go to moniroting/uss_qualifier
2. Execute ./run_locally
3. When script is starting,this syntax warning should be logged as shown in screenshot section 
**Difference from expected behavior**
USS qualififer script should be executed without syntax warnings.
**Possible solution**
Changed the deprecated character to \d
**Screenshots**
**System on which behavior was encountered**
OS: Ubuntu Linux 22.04.4 LTS 64 bits
Python version: 3.10.12
**Codebase information**
*Output of `git log -n 1`*:
**Output of `git status`**:
Author: Benjamin Pelletier <BenjaminPelletier@users.noreply.github.com> …
> [uss_qualifier/templates] fix warning for deprecated escape char in templates.py

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md
FAA/NASA feedback recommended making the links to the "Plan" and “Validate” test step fragments of the data validation test scenario more explicit (the same term is being used to link to different test step fragments, which can cause confusion).  This PR follows that recommendation and also cleans up some other parts of the documentation for that test scenario as well.
> [uss_qualifier] Clean up data validation documentation

- monitoring/loadtest/README.md
Because the loadtest tool is not commonly used, its documentation was out of date with the current build and deployment practices.  This PR updates the documentation accordingly.
> [loadtest] Update load test documentation

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/sub_api_validator.py
This PR prepares the `AuthenticationValidation` scenario for checking the endpoints for constraint references and USS availability states.
For those, the notion of a 'wrong' scope is different than for subscriptions and SCD, as the wront scope for SCD might be the correct one for setting a USS availability state.
(PRs introducing the checks for the other endpoints will follow – this is just a preparatory cleanup)
> [uss_qualifier] prepare SCD auth check scenario to check different endpoint groups

- monitoring/uss_qualifier/scenarios/astm/utm/dss/validators/oir_validator.py
The `OIRValidator` was not using the proper way to determine the start and end time of a list of extents.
> [uss_qualifier] SCD: have oir_validator rely on Volume4DCollection to compute start/end times of extends

- monitoring/monitorlib/fetch/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/availability_api_validator.py
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Covers the GET and PUT `/dss/v1/uss_availability` endpoints in the relevant scenario
This depends on #709: the content of this PR is in the last commit.
> [uss_qualifier] scd endpoint auth validation: cover uss availability

- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This should address #697 
Do note that the added check never fails, it only succeeds or is skipped.
> [uss_qualifier/scenarios/conflict_equal_priority_not_permitted] Validate GEN0500 when planning nearby potentially conflicting flight

- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/validate_shared_operational_intent.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
See https://github.com/interuss/monitoring/issues/699#issuecomment-2161025755 for context.
During the validation of a shared operational intent, if it is in an off-nominal state, the USS qualifier will attempt to retrieve its telemetry. 
It does so by validating SCD0100 but as per #699 this is incorrect.
This PR replaces the validation of SCD0100 by USS0105.
> [uss_qualifier/scenarios/utm/validate_shared_operational_intent] Stop validating SCD0100 when retrieving telemetry from USS

- monitoring/uss_qualifier/scenarios/astm/utm/versioning/evaluate_system_versions.py
A particular failure in this test scenario is missing the intermediate `request` field, instead attempting to reference the `timestamp` field directly from the `Query` (where it doesn't exist).  This PR fixes that bug.  The bug is unfortunately only revealed when that particular check fails.
> [uss_qualifier] Fix bug in Evaluate system versions test scenario

- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
Currently, if there is a problem with a USS during execution of the F3548-21 test suite, that USS may leave a dangling operational intent in the DSS.  This is less of an issue as long as that participant is always participating since the next test run starts off by instructing participants to clear the area, but that participant is not always participating.  So, they may leave a dangling operational intent and then another test run without them as a participant would be blocked due to the dangling operational intent.
This PR addresses (but does not fully solve) this issue by adding another instance of the "Prepare flight planners" scenario (whose primary activity is to clear the area) to the end of the test suite.  This should substantially increase the chances that the environment is …
> [uss_qualifier] Add environment cleanup scenario to F3548-21 test suite

- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
- monitoring/uss_qualifier/suites/faa/uft/message_signing.yaml
- monitoring/uss_qualifier/suites/uspace/flight_auth.yaml
Currently, a participant is either part of the F3548-21 test suite or they are not part of the test suite.  This can be problematic if a participant who previously participated is removed from the configuration temporarily, or if there are multiple configurations with different participants.  In that case, a participant that is not part of current test may have left content behind in the ecosystem (though #719 already mitigates this somewhat), but since they are not part of the current test, they will not be asked to clear out that content at the beginning of the test.
This PR addresses that issue by adding a separate `flight_planners_to_clear` resource to the F3548-21 test suite.  In most cases (including all the CI configurations), this resource can simply be the same resource as the …
> [uss_qualifier] Separate flight_planners_to_clear from flight_planners under test in F3548-21 suite

- .github/workflows/ci.yml
- github_pages/static/index.md
- monitoring/uss_qualifier/configurations/dev/README.md
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us.yaml
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_env.yaml
With the [public announcement](https://github.com/utmimplementationus/getstarted) of the US UTM Implementation, this PR aims to create a CI-targeted test configuration reflecting the testing needs of that project as closely as practical.  This will allow the f3548_self_contained test configuration to diverge from this project to more fully exercise the F3548-21 tests not used in that project while maintaining a useful resource for users interested or taking part in that activity.
This PR also adds a simple documentation index of the dev test configurations to make their purposes more accessible.
> [uss_qualifier] Add CI config targeted at US UTM Implementation

- monitoring/uss_qualifier/configurations/README.md
- monitoring/uss_qualifier/fileio.py
- monitoring/uss_qualifier/run_locally.sh
See README changes for a description of this change.
Note that, logically, accessing private repos belongs in the "Specifying" section, but it seems out-of-order to wait until below that explanation to present terminology so "Terminology" is also moved above "Specifying".
> [uss_qualifier] Load configuration elements from private GitHub repos

- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/baseline.libsonnet
As observed in #690 we want to discover when scenarios suddenly start being skipped.
> [config] add a pass condition for skipped_actions to utm_implementation_us

- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
As observed in #690, some deployments under test may not provide scopes for every group of endpoints being tested by the `AuthenticationValidation` scenario.
This lets the scenario selectively test the endpoints for which scopes are available.
If none of the required scopes are available a `MissingResourceError` will be raised at instantiation and the scenario should be reported as skipped.
Note that this also moves the instantiation of the validator classes to the moment in time where they are used, as they depend on the current time.
> [uss_qualifier] authentication validation: don't skip if a scope is missing, improve dependency on current time

- Makefile
- monitoring/mock_uss/interaction_logging/logger.py
- monitoring/mock_uss/interaction_logging/routes_interactions_log.py
- monitoring/monitorlib/clients/mock_uss/interactions.py
- monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/test_steps/validate_notification_received.py
This PR attempts to improve the performance of the `/mock_uss/interuss_logging/logs` GET endpoint. It:
- updates the mock USS's interaction logger to store a full timestamp of the interaction in the relevant filename 
- updates the endpoint logic to filter out files that are older than the required time
Additionally, returned interactions are now sorted before they are returned.
Test plan: the qualifier is still able to run locally against an updated mock_uss, and the scenarios that rely on the `interuss_logging/logs`  endpoint are passing.
This is not guaranteed to solve #677 but is very likely to improve the situation.
> [mock_uss] avoid full file scan when querying interaction log

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/cr_api_validator.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/delete.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/delete_format.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/read_correct.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/read_format.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/search_correct.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/crud/search_format.md
This is heavily inspired from the existing validation logic for operational intent references.
Some additional updates:
- scopes for any endpoint group may be missing without the whole scenario being skipped
- if all scopes are missing (ie, impossible to test any group) then a MissingResourceError is raised (which should cause the scenario to be skipped entirely)
- added a validation step to the `utm_implementation_us` configuration to make the expected number of skipped scenarios explicit, which should allow us to detect if scenarios suddenly start being skipped when we don't expect it.
Note: this also moves the instantiations of the authentication validator classes just before each validator is run, as they depend on the current time.
> [uss_qualifier] expand the authentication validation scenario to include constraint reference endpoints

- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.py
This PR extends the existing `SubscriptionSimple` scenario with a step that attempts to mutate a subscription with both an empty and an incorrect version.
First step towards fulfilling #760
> [uss_qualifier] scd subscription_simple: check mutation is only allowed with correct version

- monitoring/Dockerfile
In the spirit of not installing things where they are not required, this PR adds a check for the local architecture and only installs the arm-specific dependencies when indeed needed.
Notes:
- explicitly add `make` to the first package install: it is required by jsonnet and probably included implicity via the ARM dependencies
- we need to install additional tools for ARM because the base image will behave slightly differently depending on the architecture when the requirements are pip install'ed, probably because some dependencies have differing installation procedures depending on the architecture.
- x86 should be seen as the default architecture we target (that's what is available in CI), and we add what is missing for arm in order to make developer's and users life easier
> [build] only install ARM-specific dependencies on an ARM architecture

- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
`self._availability_dss` is [only set](https://github.com/interuss/monitoring/blob/4f4a63a3f8b40f5c93f933aba9ed8472daafa8a0/monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py#L174) when the relevant scopes are available.
The cleanup logic in `def _ensure_test_entities_dont_exist()` was not checking whether or not that field is available.
Note that the method might also be missing a similar check for the `_scd_dss`, but this will be addressed in a separate PR.
Closes #781
> [uss_qualifier] scd auth: only cleanup availability if the relevant part of the scenario runs

- monitoring/monitorlib/clients/flight_planning/client_v1.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
Update the flight planning client in two ways:
- record flight creation if any kind of HTTP response was received, even non-200 ones 
- upon flight cleanup, do not fail if a 404(*) is received, as cleanup attempts may now happen for flights that were not created.
Furthermore,  the `cleanup_flights` test step now considers any 200 or 404 response a successful cleanup.
(*)  the API [will return a 404](https://github.com/interuss/automated_testing_interfaces/blob/4e07f46eb4452da761fb1658d3775d801d19312b/flight_planning/v1/flight_planning.yaml#L471) if the plan does not exist.
First part of #772
> [uss_qualifier] op-data-validation: cleanup flights even if creation seemingly failed

- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
While addressing #781 with #782 I found that the `AuthenticationValidation` scenario's cleanup logic was:
- not checking if the `_scd_dss` was available before using it to do scd related cleanups
- missing the relevant cleanup for constraints
This PR addresses both issues.
> [uss_qualifier] scd auth: proper cleanup and check for scd and constraints test cases

- monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_simple.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_simple.py
Another stepping stone towards explicitly covering #760
> [uss_qualifier] scd: expand OIRSimple scenario to check mutation requires the correct OVN

- monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_simple.py
#764 additionally considers 404 an acceptable response code when attempting mutations with a missing OVN.
This PR also adds 404 as an acceptable return code for deletion attempt with a missing OVN, while also fixing the actual condition check.
> [uss_qualifier] scd: OIRSimple - fix error status check and include 404

- monitoring/mock_uss/tracer/subscriptions.py
- monitoring/monitorlib/fetch/scd.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions_deletion.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.py
`class FetchedSubscription(fetch.Query)` currently considers receiving a 404 from the DSS a success (ie, the `success` property will return True).
This is not strictly correct and can lead to confusion: a 404 will now cause `success` to be false. Callers that need to differentiate between a failure and a 404 may use `was_not_found` which will only be true if the returned code was 404.
Split out of #720
> [uss_qualifier] scd subscrptions: stop considering 404 a success, add was_not_found

- monitoring/uss_qualifier/README.md
- monitoring/uss_qualifier/make_artifacts.py
- monitoring/uss_qualifier/make_artifacts.sh
An empirically-common use case is for someone to receive a bare report.json and then need to generate the relevant human-friendly artifacts from it.  This PR supports this use case by making explicit specification of a configuration optional when calling make_artifacts.  When not specified, the configuration embedded within the provided report(s) will be used to specify the artifacts to be generated.
> [uss_qualifier] Have make_artifacts use configuration from report by default

- monitoring/mock_uss/f3548v21/flight_planning.py
- monitoring/uss_qualifier/resources/overrides.py
This addresses the second part of #772
> [uss_mock] override logic preserves type of dict implementations

- monitoring/uss_qualifier/scenarios/astm/utm/dss/constraint_ref_simple.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/constraint_ref_simple.py
last piece to implement #760 by having a test case explicitly dedicated to attempting mutation with missing an incorrect OVNs
Only the last commit of this PR is relevant, this will remain a draft until #762 is merged.
> [uss_qualifier] scd CRSimple checks that mutation is only allowed with the correct OVN

- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/baseline.libsonnet
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/local/env.libsonnet
The US UTM Implementation is not currently using availability arbitration and therefore access tokens with that scope cannot be obtained in that context.  This PR reflects the situation in the test configuration attempting to mirror/track that project's usage of InterUSS automated testing.
> [uss_qualifier/configurations] Disable availability arbitration tests in UTM Implementation US config

- .github/ISSUE_TEMPLATE/release_request.md
Because `monitoring` releases include built images, they are more reliable to use for automated testing than commits outside of a release.  This means users are likely to want to request the creation of `monitoring` releases to support automated testing activities needing certain functionality which may not otherwise be released yet.  This PR adds an issue template to facilitate this request process.
> [GitHub] Add release request issue template

- monitoring/mock_uss/__init__.py
- monitoring/mock_uss/gunicorn.conf.py
- monitoring/mock_uss/logging.py
- monitoring/mock_uss/routes.py
- monitoring/uss_qualifier/resources/interuss/mock_uss/client.py
When automated testing fails because of a failure in mock_uss, it is often difficult to determine what happened, and even more difficult for participants without access to mock_uss's logs.  This PR attempts to improve visibility into mock_uss's behavior, primarily by attaching log messages generated while fulfilling a request to that request's response.  This will unfortunately not address the need to debug behavior when a request to mock_uss times out (for instance, if notifying other USSs takes a long time) since uss_qualifier will not have the response for that issue, but it should address a number of other behavior visibility needs.
In addition, this PR adds a full stack trace to 400 and 500 responses to more rapidly identify the problem.  Finally, logging is disabled for the root …
> [mock_uss] Improve mock_uss behavior visibility

- monitoring/monitorlib/fetch/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/versioning/evaluate_system_versions.py
Although a similar fix had previously been made, the F3548-21 evaluate_system_versions test scenario still [attempted to access the non-existent `timestamp` property on `Query` objects](https://github.com/interuss/monitoring/blob/8f2dc5322229c42e72ad07078f5068f0b8cb0c2b/monitoring/uss_qualifier/scenarios/astm/utm/versioning/evaluate_system_versions.py#L134) when logging certain kinds of failures.  This PR attempts to solve this problem again by:
* Accessing `timestamp` of the Query `request` rather than the Query itself
* Adding a `timestamp` property to the Query in case there are other hidden references
* Searching for instances of `q.timestamp` (there don't appear to be any)
* Searching for instances of `query.timestamp` (there don't appear to be any)
* Manually scanning all instances …
> [uss_qualifier] Fix query timestamp property reference

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_no_notification_operational_intent.md
This addresses #797.
We keep track of the operational intent IDs that were created during the scenario run in order to ignore notifications about them that might have been sent asynchronously after the rejected planning attempt. 
This also enhances the failure message of the check and add a low severity check for parsing the interaction query request.
> [uss_qualifier/scenarios/data_exchange_validation] Fix wrong check failure for lack of notification

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- requirements.in
- requirements.txt
This upgrades the library `uas_standards` to the latest version that includes the new `request_ovn_suffix` field (interuss/uas_standards#16) and adds support for it in the dss object. 
That is required for implementing the test scenario covering the feature implemented in interuss/dss#1119.
> [uss_qualifier/f3548] Add support for requested_ovn_suffix field

- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.py
The `OIRImplicitSubHandling` scenario had a check that was not setting the participant identifier.
> [uss_qualifier] scd/OIRImplicitSubHandling: properly attribute query for a check

- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
This is a prerequisite for several upcoming PRs dealing with NET0260 for #754: we'll be accessing multiple fields belonging to an observed flight, and want to directly access the flight object's properties rather that forwarding every call.
> [uss_qualifier] netrid: DPObservedFlight exposes underlying flight object

- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
`cleanup_active_oirs`and `cleanup_constraint_ref` were not registering successful requests to the DSS. The missing registration in `cleanup_active_oirs` likely caused #809.
This PR properly registers the queries in the two aforementioned functions.
(All other fragments in the modified file are properly registering both successful and failed queries)
Resolves #809
> [uss_qualifier] scd: add missing query registration in test_step_fragments

- monitoring/monitorlib/mutate/rid.py
This allows users of the `DSSWrapper` to easily check which subscribers were mentioned in a response to create, mutate or delete an ISA on the DSS.
Up to now this _could_ be reconstructed by looking at the notifications that were effectively sent by the wrapper, but this was needlessly cumbersome and breaks down when the qualifier ignores notifications that should be sent to itself.
(This change was required by #839)
> [uss_qualifier] monitorlib: ISAChange exposes subscribers as returned by DSS

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/test_steps/validate_notification_received.py
Issue #797
Stack on top of #829, please consider only last commit.
This refactors the way `mock_uss_interactions` filters interactions by generalizing the filtering by functions that already existed. On top of simplifying the logic, this enables invoking that function without any filters, which we will need in an upcoming PR.
- Usage of parameters `op_id` and `query_params` is replaced by filter function `operation_filter`
- Usage of parameter `direction` is replaced by filter function `direction_filter`
- `is_op_intent_notification_with_id` is renamed into `notif_op_intent_id_filter`
- `_is_notification_sent_to_url_with_op_intent_id` is replaced by new `base_url_filter` combined with existing `notif_op_intent_id_filter`
> [uss_qualifier/scenarios/utm/data_exchange_validation] Refactor filtering of mock_uss_interactions

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/query_mock_uss_interactions.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_get_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_no_notification_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_notification_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/test_steps/validate_notification_received.md
- monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/test_steps/validate_notification_received.py
- monitoring/uss_qualifier/scenarios/interuss/mock_uss/get_mock_uss_interactions.md
- monitoring/uss_qualifier/scenarios/interuss/mock_uss/test_steps.py
Issue #797
Stacked on top of #831, please only consider last commit.
This factors away inside `interuss/mock_uss` as a test step fragment the retrieval of mock USS interactions.
> [uss_qualifier/scenarios/utm/data_exchange_validation] Factor away as test step fragment 'get_mock_uss_interactions'

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_get_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_operational_intent_details_obtained.md
Issue #797.
Stacked on top of #833, please consider only last commit.
This creates the test step fragment `expect_uss_obtained_op_intent_details` which is used in the scenario data_exchange_validation, replacing some parts of the scenario that were attempting to do the same with some conditional test steps.
With that change we do a single call to the mock USS to retrieve the interaction logs, and from there we are able to determine whether the tested USS has obtained the operational intent details, no matter how. This makes the documentation clearer.
The implementation of the check now validates as well that the status code of the notification or details retrieval is a success (previously a failed call would be considered as valid).
> [uss_qualifier/scenarios/utm/data_exchange_validation] Factor away fragment 'expect_uss_obtained_op_intent_details'

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
Issue #797 
Stacked on top of #835, please consider only last commit.
- Enhance check failure message
- Validate status code of notification
- Ensure the notification is about the correct operational intent
> [uss_qualifier/scenarios/utm/data_exchange_validation] Fix expect_mock_uss_receives_op_intent_notification

- monitoring/monitorlib/fetch/rid.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
> [uss_qualifier] netrid: net0260 - check SP correctly reports horizontal accuracy

- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
The `nominal_behavior` scenario already checks off `NET0430` (which requires a _Display Provider_ to not return data if the requested diagonal is too big) within the "Service Provider polling" test step.
This seems incorrect, as `NET0430` specifically concerns a display provider, it should not be present in the _Service Provider polling_
The PR adds coverage for `NET0250` simply by replacing `NET0430` with `NET0250`
Part of the effort for #754
> [uss_qualifier] netrid: nominal_behavior also covers max area requirement for SPs

- monitoring/monitorlib/fetch/rid.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Expand the generic `NominalBehavior` scenario to check:
- for the presence of the required `timestamp_accuracy` field
- that the field contains the injected value
Because of the way implicit dicts works, checking for the presence of this field requires to look at the raw response Json (see comment in the code)
Part of #754
> [uss_qualifier] netrid: cover net0260 timestamp accuracy

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss_interoperability.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Adds a check that a subscription's area (represented by the cell identifiers that overlap with it) is properly synchronized across all DSS's participating in the deployment.
Part of the effort for #754
> [uss_qualifier] rid: dss0130 - Cell ID synchronization

- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
Fix reference to wrong object and align with convention used for other similar failed checks.
> [uss_qualifier] netrid: display_data_evaluator fix failed check description

- monitoring/uss_qualifier/scenarios/README.md
This PR clarifies the intended usage of test step fragments, in particular invalidating the practice of dumping a bunch of checks into a test step fragment and then reusing that fragment from many places which each use a subset of those checks.
> [uss_qualifier/docs] Add  documentation regarding test step fragments

- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/baseline.libsonnet
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/local/env.libsonnet
This PR adjusts a few characteristics of the utm_implementation_us CI configuration representative of the [US UTM Implementation](https://github.com/utmimplementationus/getstarted) to better match the current state of that project.
It adds two requirements to the set of requirements that must be verified, and also adds the ability (for uss_qualifier) to get the availability arbitration scope to verify DSS instance behavior.
> [uss_qualifier/configurations] Update utm_implementation_us

- build/dev/docker-compose.yaml
- monitoring/uss_qualifier/configurations/dev/dss_probing.yaml
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_containers.yaml
- monitoring/uss_qualifier/configurations/dev/library/environment_localhost.yaml
- monitoring/uss_qualifier/configurations/dev/uspace.yaml
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/baseline.libsonnet
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/local/env.libsonnet
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/uss1.libsonnet
- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/uss2.libsonnet
- monitoring/uss_qualifier/scenarios/interuss/ovn_request/dss_ovn_request.md
- monitoring/uss_qualifier/scenarios/interuss/ovn_request/dss_ovn_request.py
Stacked on top of #816 please consider only last commit.
This upgrades the DSS version used up to v0.19.0-rc2 which has the OVN request support and adapt accordingly the specification of the DSS resources in the configurations.
This also fixes two issues that went unnoticed in the `DSSOVNRequest` scenario:
- not checking for the proper OVN in a step
- removing the `check` suffix when linking a test step fragment
> [uss_qualifier] Upgrade to latest dss version; Add 'supports_ovn_request' field to dss resources; Fix DSSOVNRequest scenario

- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
First simple approach for validating height reported by the SP.
We could narrow down the checks by having test designers provide a resource specifying a maximum envelope for the height, but this is of lower priority and will be added later if time permits.
Part of the effort on #754
> [uss_qualifier] netrid: net0260 check observed height

- requirements.in
- requirements.txt
This will give us access to the new optional fields in the observation APIs
> [deps] update uas_standards dependency to 3.3.0

- monitoring/monitorlib/dicts.py
- monitoring/uss_qualifier/main.py
- monitoring/uss_qualifier/make_artifacts.py
- monitoring/uss_qualifier/reports/artifacts.py
If a user provided execution of uss_qualifier as a service and accepted test configuration from their users, the uss_qualifier executer would want to make sure that a provided test configuration did not cause the artifacts to reveal sensitive information.  This PR adds that capability by adding a --disallow-unredacted flag that produces an error if a test configuration is provided which doesn't redact sensitive information from artifacts.  A redundant check is also added in the artifact generation routine that double checks this redaction directive.
> [uss_qualifier] Add flag to ensure redaction of sensitive information

- monitoring/mock_uss/ridsp/routes_ridsp_v19.py
- monitoring/mock_uss/ridsp/routes_ridsp_v22a.py
- monitoring/monitorlib/rid_automated_testing/injection_api.py
#854 updated uas_standards to the version that includes the `aircraft_type` in the injection data. With the dependency update the injected aircraft_type was 'automatically' stored.
This PR wires up the mock USS to expose it through the observation interface.
There is a special case that is handled: the definitions of the enums in both versions of RID do not match. In v22a VTOL is replaced by HybridAircraft. This PR accounts for that.
> [mock_uss/ridsp] Expose aircraft_type through observation interface

- monitoring/uss_qualifier/resources/netrid/flight_data_resources.py
`aircraft_type` is actually attached to `TestFlight`:
https://github.com/BenjaminPelletier/automated_testing_interfaces/blob/bd9971a43d8a708187567f3da4ce06ea214575ec/rid/v1/injection.yaml#L402-L405
And not `TestFlightDetails`: 
https://github.com/BenjaminPelletier/automated_testing_interfaces/blob/bd9971a43d8a708187567f3da4ce06ea214575ec/rid/v1/injection.yaml#L418-L434
> [uss_qualifier/netrid] Fix injection of aircraft_type

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/display_data_evaluator_clustering.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight_details.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight_details.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/display_data_evaluator_clustering.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
This factors away from the RID nominal_behavior scenario as test step fragment:
- DP flight consistency with dictionary
- DP flight details consistency with dictionary
- SP flight consistency with dictionary
- SP flight details consistency with dictionary
- Clustering
It also shuffles around checks in the scenario in order for them to appear in rough execution order.
Do note that no check has been changed by this PR, it exclusively factors them away.
This is required for upcoming PRs to restore a bit of clarity in that scenario before implementing additional checks.
> [uss_qualifier/scenarios/netrid] Factor away test step fragments from scenario

- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/display_data_evaluator_flight_presence.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/display_data_evaluator_flight_presence.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Stacked on top of #861, please review last commit only.
This factors away from the RID nominal_behavior scenario as test step fragment the 'flight presence' checks.
Those checks are reused across DP and SP polling, and there are some slight differences between them:
- *Premature flight check*: no change
- *Missing flight check*: the SP check covers more requirements than the DP one. However IMO it looks appropriate to have all those requirements covered for both SP and DP (NET0710,1 and NET0340 added on top of NET0610).
- *Lingering flight check*:
- for v19: both SP and DP had NET0270 as requirement
- for v22a: SP has NET0270, and DP has NET0260, but with an issue: the requirement is not linked thus not covered by the check
- I've decided to change all those by the requirement …
> [uss_qualifier/scenarios/netrid] Factor away test step fragment for flight presence from scenario

- monitoring/mock_uss/riddp/routes_observation.py
- monitoring/monitorlib/fetch/rid.py
Follow-up to #859: the DP interface also required an update. In addition this adds in the fetch package the necessary functions to extract the aircraft type from the fetched flight.
> [mock_uss/riddp] Expose aircraft_type through observation interface

- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/expected_interactions_test_steps.py
In the [data exchange validation scenario](https://github.com/interuss/monitoring/blob/89c3b385c0697774b06388d7418f21db20f9be87/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/get_op_data_validation.md), there is [a check that a notification was not sent](https://github.com/interuss/monitoring/blob/89c3b385c0697774b06388d7418f21db20f9be87/monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_no_notification_operational_intent.md#-expect-notification-not-sent-check) in a particular situation.  But, this check would not be performed if there were no interactions found in mock_uss, even though the check should clearly pass in that case.  This PR fixes that problem.
> [uss_qualifier] Fix no-notification check logic

- monitoring/uss_qualifier/resources/netrid/flight_data.py
- monitoring/uss_qualifier/resources/netrid/simulation/adjacent_circular_flights_simulator.py
- monitoring/uss_qualifier/resources/netrid/simulation/kml_flights.py
- monitoring/uss_qualifier/resources/netrid/simulation/operator_flight_details.py
The models from the injection/observation interface are compatible with both versions of RID.
Before the changes in that PR, some RID models from v19 were used for injection, making impossible to test v22a-specific features like 'UA classification'.
> [uss_qualifier/resources/netrid] Use models from injection interface rather than RID v19

- monitoring/uss_qualifier/resources/netrid/simulation/kml_flights.py
- monitoring/uss_qualifier/test_data/che/rid/foca.kml
Stacked on top of #868, please review only last commit.
This adds the support for 'eu_classification' field in the KML flight resource generator by specifying directly both elements 'eu_classification_category' and 'eu_classification_class'.
This also adds to the KML file used in the CI those fields so that they are injected by the USS qualifier.
> [uss_qualifier/resources/netrid/simulation/kml_flights] Add support for 'eu_classification' field

- monitoring/mock_uss/riddp/routes_observation.py
- monitoring/monitorlib/fetch/rid.py
When the mock_uss acts like a Display Provider, we want it to expose the relevant fields of `current_state` that were defined in the injected data. 
We now populates the following additional fields:
* timestamp_accuracy=flight.timestamp_accuracy,
* speed_accuracy=flight.speed_accuracy,
* vertical_speed=flight.vertical_speed,
> [mock_uss/obervation-api] add newly exposed API fields to the current_state

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This PR adds checks for UA type in DP response. This adds coverage for requirements v22a.NET0470,Table1,2 and v19.NET0470,Table1,3. Note that a check for NET0450 is also included here.
> [uss_qualifier/scenarios/netrid/nominal_behavior] Add checks for UA type in DP (NET0470)

- monitoring/uss_qualifier/scenarios/astm/netrid/common/misbehavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/misbehavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/misbehavior.md
This PR adds two steps in misbehavior scenario to ensure invalid credentials (and not only missing credentials) return authentication failures, as stated in #874
> [uss_qualifier/scenarios/netrid/misbehavior] Add checks for invalid credentials (NET0210)

- monitoring/mock_uss/riddp/routes.py
- monitoring/mock_uss/riddp/routes_riddp_v19.py
- monitoring/mock_uss/riddp/routes_riddp_v22a.py
This complements #881 by implementing one of the endpoints for which we will want to log interactions. (Part of the effort to cover Net0740)
> [mock_uss] add isa notification endpoint to mock RID display provider

- monitoring/mock_uss/__init__.py
- monitoring/mock_uss/docker-compose.yaml
- monitoring/mock_uss/interaction_logging/logger.py
In preparation for RID Net0740 (DP with a subscription is notified of newly created ISAs), we wish to determine if the mock_uss has received the relevant requests when it is deployed as a Remote ID Display Provider.
For the sake of completeness this also enables interaction logging for flight search and flight details endpoint, and does so on the mock SP as well.
This also logs at startup whether or not interaction logging is enabled.
> [mock_uss] interaction logging for the mock RID DP and SP

- .github/workflows/ci.yml
- .github/workflows/monitoring-test.yml
I thought #887 would resolve the code scanner findings regarding permissions, but the permissions in the `uses` block apparently are not counted by the scanner.  This PR promotes the permissions definitions directly into the workflow job definitions in an attempt to resolve these automated code scanner findings.
> [security] Expand workflow permissions directly into job definitions

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/heavy_traffic_concurrent.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_expiry.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/subscription_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/subscription_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss_interoperability.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/heavy_traffic_concurrent.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_expiry.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/subscription_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/subscription_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.md
This PR follows PR #882
It does migrate more severity into scenario documentation, mainly for `netrid/dss/isa_subscription_interactions`, but does include others moves for some shared functions used in `isa_subscription_interactions`.
> [uss_qualifier/scenarios/netrid/dss/isa_subscription_interactions] specify some check severity in test scenario documentation only (contrib #404)

- monitoring/uss_qualifier/scenarios/astm/netrid/v19/fragments/flight_injection.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/fragments/sp_polling.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/fragments/flight_injection.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/fragments/sp_polling.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/misbehavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
#880 will add a scenario that does some flight injections, and we start to have some duplicated steps and checks.
This PR proposes to move common steps and checks to their own fragment.
> [uss_qualifier] extract some fragments for scenarios injecting flights

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
Changes:
- If the result checked is from the DP and that it is None, don't perform any additional checks since the DP (through observation API) will never be required to expose any field (case C8).
- When the injected value is None, expect both SP and DP to expose `NotDeclared`
- SP: because it is a required field that must be exposed, so None is not a valid value
- DP: because the DP must expose what it received from the SP (even though in the observation API the field is nullable)
Those changes simplify the control flow of the check and should also facilitate implementation of generic function in #894.
Notably because there should now only be two cases: whether or not the field is required in SP API. Which is equivalent to whether or not this is a required field by the standard. 
Note …
> [uss_qualifier/scenarios/netrid/common_dictionary_evaluator] Simplify check for UA type

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Following #865 and #866' base, this PR add similar checks for Timestamp accuracy.
A generic function is used, with the goal of moving missing checks to a similar structure.
Notice there is already some Timestamp accuracy SP checks that will need to be removed later after this normalization.
> [uss_qualifier/scenarios/netrid/nominal_behavior] Add checks for Timestamp accuracy in SP and DP (NET0260/NET0470)

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Follows #896, you probably want to review only the latest commit.
Add SP/DP checks for Geodetic Vertical Accuracy.
> [uss_qualifier/scenarios/netrid/nominal_behavior] Add checks for Geodetic Vertical Accuracy in SP and DP (NET0260/NET0470)

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Follows #898 , you probably want to review only the latest commit.
Add SP/DP checks for Vertical Speed.
> [uss_qualifier/scenarios/netrid/nominal_behavior] Add checks for Vertical Speed in SP and DP (NET0260/NET0470)

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Follows #899 , you probably want to review only the latest commit.
Add SP/DP checks for Horizontal Accuracy.
> [uss_qualifier/scenarios/netrid/nominal_behavior] Add checks for Horizontal Accuracy in SP and DP (NET0260/NET0470)

- monitoring/Dockerfile
The health checks have a interval of 30s by default, who can be quite long when restarting mocks for testing multiple time.
This PR lower the interval to 3s, making restarts / starts faster.
Since the heath checks are only simple curl call or a simple `exit 0`, this shouldn't probably hurt CPU usage.
> [dev] Lower docker image healthcheck interval

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dp_behavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dp_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dp_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Although we currently have checks for NET0730, I do not believe we have a test that is likely to verify compliance to NET0730 under nominal circumstances.  This PR addresses that issue by adding documentation for a test intended to verify NET0730 compliance under many (but not all) circumstances.
NET0730 essentially requires that a Display Provider accept and properly acknowledge incoming notifications due to a subscription the Display Provider has established in the DSS.  There is currently no way to ensure a Display Provider necessarily has a subscription in the DSS, but many Display Providers will create a subscription when an observer starts looking at a particular area.  Therefore, the DP Behavior test is adjusted in this PR to first query observers before establishing an ISA in an …
> [uss_qualifier/netrid] Add test for NET0730

- requirements.in
- requirements.txt
This PR updates the version of Flask we use to address a Dependabot finding.  This PR also updates a few related packages and runs the `pip-compile --generate-hashes --output-file=requirements.txt requirements.in` command after first deleting requirements.txt which results in newer versions of certain packages.
> [security] Update Flask version

- monitoring/uss_qualifier/scenarios/astm/netrid/v19/fragments/flight_check.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/fragments/flight_details_check.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/nominal_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/fragments/flight_check.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/fragments/flight_details_check.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/nominal_behavior.md
Other scenarios injecting flights are being added: this should help reduce the amount of copy-pasted checks.
> [uss_qualifier] doc: split out some fragments for nominal behavior

- monitoring/mock_uss/ridsp/routes_injection.py
- monitoring/mock_uss/ridsp/user_notifications.py
- monitoring/monitorlib/rid_automated_testing/injection_api.py
This is a building block for the scenario that will cover Net0040, for which notifications must be sent to the operator when the telemetry update rate is insufficient.
(This will allow us to implement the scenario for which documentation was added in https://github.com/interuss/monitoring/pull/907)
> [mock_uss] save a notification when telemetry is too sparse

- monitoring/mock_uss/logging.py
- monitoring/mock_uss/riddp/database.py
- monitoring/mock_uss/riddp/routes_observation.py
- monitoring/mock_uss/riddp/routes_riddp_v19.py
- monitoring/mock_uss/riddp/routes_riddp_v22a.py
- monitoring/monitorlib/geo.py
- monitoring/monitorlib/mutate/rid.py
Currently, mock_uss polls the DSS for current ISAs every time an individual observation for flights is made.  This is generally unrealistic and wasteful as most USSs will keep track of ISAs via subscriptions.  This PR updates mock_uss behavior to emplace a subscription to identify ISAs necessary to fulfill an observation query, and then use existing subscriptions to identify ISAs (with no query to the DSS) when possible.
This behavior change is necessary to validate a new test that verifies compliance to NET0730.
> [mock_uss/RID] Use RID subscriptions in mock_uss

- .github/workflows/ci.yml
- .github/workflows/monitoring-test.yml
This PR addresses two code scanning findings by:
1. Pinning the version of a third-party workflow dependency
2. Explicitly defining the permissions of an internally-defined workflow (even though all uses of that workflow also explicitly set permissions)
> [security] Secure workflows

- monitoring/monitorlib/html/templates/explorer.html
monitorlib houses a Jinja2 macro to render complex dicts as interactive expandable/collapseable elements.  This is used in many places, but one important place is representing queries in uss_qualifier reports.  When troubleshooting, these queries will often have a stack trace value.  But, because Jinja2 renders the string as HTML, newlines are ignored as plain whitespace.  This PR addresses that narrow issue by replacing newlines with explicit HTML br elements so stack traces are easier to read.
> [monitorlib/reports] Render newlines in string values

- monitoring/uss_qualifier/resources/interuss/uss_identification.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dp_behavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dp_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dp_behavior.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This PR technically implements the new test for ASTM F3411 NET0730 documented in #914.
The test executes, but does not verify compliance to NET0730 in CI currently because mock_uss does not establish subscriptions.  However, this PR has also been tested with #927 -- with that mock_uss behavior change, NET0730 is successfully verified by this test.
Some places in the test where queries were not recorded are also fixed in this PR (issue discovered during testing).
> [uss_qualifier/NetRID] Implement NET0730 test

- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.py
Expand the `OIRImplicitSubHandling` with another corner case mentioned here: https://github.com/interuss/dss/issues/1088
> [uss_qualifier] scd - implicit sub handling: new test case replaces explicit sub with implicit one

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight_details.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight_details.md
> [uss_qualifier] NetRID: migrate some severities to documentation

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
In #909's spirit this adds some unit tests for `_evaluate_timestamp_accuracy`
A new testing function has been added for evaluator without defaults.
> [uss_qualifier/scenarios/netrid/common_dictionary_evaluator] Test _evaluate_timestamp_accuracy

- monitoring/monitorlib/fetch/rid.py
- monitoring/uss_qualifier/resources/netrid/simulation/kml_flights.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
This PR compute height of the flight during kml flight generation, to test height and height accuracy in common_dict_eval.
A few remarks:
- The method of computing the height is a guess based on current altitude. Should we have the information somehow directly in the kml file?
- After a discussion with Mike related to KML, the vertical speed, currently set to zero, may be computed in a similar way. I created #943  to track it.
- I fixed a 19 -> 22 typo I found during debugging
- It seems the height is injected in two locations: the position and the state (v22/v19a ?) and the code is using various version of the field. To ensure it's working for this PR, I just used the same value in two locations and I created #942 to normalize it
- Like the test in the common_dict, I set the height to …
> [uss_qualifier/common_dict_eval] generate height for kml flights to test height fields

- monitoring/uss_qualifier/scenarios/astm/netrid/common/nominal_behavior.py
The nominal behavior scenario was ending too early, preventing the [Lingering Flight](https://github.com/interuss/monitoring/blob/51576beeb1bb536c4e2f9eb508996e0e0f302d04/monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py#L1440) check to run. 
Adding 10 seconds allows to guarantee that one of the polls (that occurs about every 5 seconds) will run after the flight is complete, and when no data should be returned anymore.
> [uss_qualifier] NetRID extend polling in nominal_behavior so all post-flight checks run

- monitoring/mock_uss/ridsp/user_notifications.py
Follow #916 , please review only the last commit.
Improve missing fields notifications introduced in #911 by using a smarter default that just using now()
Since timestamp field may be missing, we use, by the following order of priority, for each frame:
- The timestamp of the telemetry frame
- The timestamp used for the previous telemetry frame (the one selected by this list ^^')
- The timestamp of the start of the flight (if one is found)
- now()
>  [mock_uss] Improve missing field notifications with timestamp guessing 

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
With tests :)
Following @BenjaminPelletier remarks in #940, this moves speed checks to the `_generic_evaluator`, improving tests and edge case handeling.
> [uss_qualifier/common_dict_eval] Move speed to generic function

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
With tests.
Following @BenjaminPelletier remarks in https://github.com/interuss/monitoring/pull/940, this moves track direction checks to the _generic_evaluator, improving tests and edge case handling.
> [uss_qualifier/common_dict_eval] Move track to generic function

- monitoring/uss_qualifier/configurations/dev/uspace.yaml
In `uspace` configuration the requirement NET0730 is not validated while it is validated in `netrid_v22a`.
That's due to the fact that it is required for the `uss_identification` to be passed to the scenario to validate that requirement.
This was setup for configuration `netrid_v22a` but not `uspace`. This PR sets it up for `uspace`.
> [configurations/uspace] Pass uss_identification to required_services suite for NET0730 validation

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Follow #952 
Like #952, moving of timestamp to the generic function, with tests.
Fix an issue with the _generic_function as well, who was not using the `value_validator` for the `observed_val`
> [uss_qualifier/common_dict_eval] Move timestamp to generic function

- monitoring/monitorlib/fetch/rid.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
- monitoring/uss_qualifier/scenarios/astm/netrid/display_data_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_dp_flight.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/common_dictionary_evaluator_sp_flight.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This implements properly the check for height and height type in the common dictionary evaluator.
Note that most of the work has been done by @the-glu in 4f47ede11386f572bfdd0014a88cb4f0a68d1896.
In addition:
- cleanup legacy height and height types checks
- adapt generic evaluator to support multiple unknown values
- for mock USS DP v19: expose height correctly
With this PR the RID coverage should now be complete, modulo some still pending issues.
> [uss_qualifier/common_dict_eval] Move height and height type to generic function

- .github/workflows/ci.yml
- Makefile
- monitoring/Makefile
- monitoring/uss_qualifier/Makefile
The unit tests were tied to the `make test` command which run the full USS qualifier test suite. It makes more sense for those unit tests to be ran within the repository hygiene tests.
This PR also consolidates some make commands and CI targets to reduce noise.
cc @the-glu
> [CI/Makefiles] Run unit tests in 'hygiene-tests' instead of 'monitoring-test' and consolidate commands

- .dockerignore
This remove the .git folder, who seems to be unused, from the docker context build.
It does speed up building/running local images, especially with a big .git folder (5s -> 2.5s to run uss_qualifiers units tests on my machine).
> [dev] Remove .git from docker context

- monitoring/uss_qualifier/reports/templates/sequence_view/overview.html
- monitoring/uss_qualifier/reports/templates/sequence_view/style.html
- monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html
Currently, it is hard to tell which column is which on the sequence view overview because the header row is not sticky like it is for the tested requirements artifact.  This PR fixes that problem by making the header row sticky on the overview page and scenario pages of sequence view.
Due to CSS reasons beyond my current understanding, `box-sizing: border-box;` is key to obtaining the correct header row height since, without it, the sequence view header will be too tall even though the tested requirements header with apparently the same styling is not too tall.  For consistency/explicitness, this constraint is applied to the tested requirements styling as well.
> [uss_qualifier/reports] Make sequence view overview header row sticky

- monitoring/uss_qualifier/scenarios/scenario.py
During testing of scenario.py for the uss_qualifier, I found two minors issues:
- `record_note` is not ensuring a `_scenario_report` report exist like others functions
- `_get_check` is unused in the whole code base
This PR fixes them.
> [uss_qualifier] Units tests for scenario.py: fixes

- monitoring/uss_qualifier/resources/netrid/service_providers.py
- monitoring/uss_qualifier/scenarios/astm/netrid/injection.py
This PR fixes a uss_qualifier bug when invalid responses are received from a USS's user notifications endpoint -- prior to this PR, uss_qualifier would raise an uncaught exception (always indicating a uss_qualifier bug) if the USS response could not be parsed.  This PR records a failed check and proceeds gracefully instead of raising an uncaught exception.
> [uss_qualifier] Record failure for user notifications parsing errors

- monitoring/uss_qualifier/scenarios/astm/netrid/v19/networked_uas_disconnect.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/networked_uas_disconnect.md
This PR fixes [a bug](https://interuss.slack.com/archives/C05UVBHKQ0G/p1739987447769379?thread_ts=1739975246.437539&cid=C05UVBHKQ0G) where the severity of checks is not annotated in documentation nor specified in code.
> [uss_qualifier] Annotate severity of checks in networked_uas_disconnect

- Makefile
Follow-up to https://github.com/interuss/monitoring/pull/957/files#r1953440811
The comment on the target was indeed wrong and actually for a while: since then the different configurations were separated into separate jobs, and the job 'monitoring-tests' does not exist anymore.
This PR removes the target 'monitoring-tests' and add 'check-monitoring' as dependency of 'presubmit' to preserve its behavior.
> [Makefile] Remove 'monitoring-tests' target

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
This PR add all missing tests on common_dictionary_evaluator's _evaluate function.
It's mostly basic application of existing function, but also include a fix for the vertical speed who shouldn't be valid between -62 and -63
> [uss_qualifier/scenarios/netrid/common_dictionary_evaluator] Test alt, accuracy_v, accuracy_h, speed_accuracy, vertical_speed

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
This PR prepare the full removal of magic constants, by using correct values and adding todo when a new release of uas_standards is needed.
Some constants and related tests where fixed to adhere to the standard.
This PR contrib to #945
> [uss_qualifier/common_dict_eval] remove and prepare removal of magic constants

- monitoring/uss_qualifier/scenarios/astm/netrid/v19/fragments/sp_polling.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/fragments/sp_polling_queries.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/sp_operator_notify_slow_update.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/fragments/sp_polling.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/fragments/sp_polling_queries.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/sp_operator_notify_slow_update.md
- monitoring/uss_qualifier/scenarios/documentation/checks_without_severity.json
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.md
- monitoring/uss_qualifier/suites/uspace/network_identification.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
The `ServiceProviderNotifiesSlowUpdates` scenario had some checks that were documented but not actually done, due to the reuse of a too-general fragment.
The fragment has been split to allow using only what is required. 
Running the uspace configuration locally, for example, the superfluously documented checks don't appear in `output/uspace/requirements` under section `NET0710,1`
Part of the effort on #975
> [uss_qualifier] slow_update scenario remove unchecked checks from doc

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/heavy_traffic_concurrent.py
The concurrent ISA creation in `HeavyTrafficConcurrent` was not checking for the return code of the request, despite this being documented.
The PR fixes this by introducing a check
Part of the effort on #975
> [uss_qualifier] concurrent isa creation scenario now checks return code

- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dp_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/heavy_traffic_concurrent.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/isa_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/create_isa.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/mutate_isa.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/token_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss_interoperability.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dp_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/heavy_traffic_concurrent.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/isa_simple.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/create_isa.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/mutate_isa.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/token_validation.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.md
The scenario checking for Display Provider behavior had two minor issues:
- documented version update check in situations where that check cannot be done
- missed opportunity for checking that versions are updated upon ISA mutation
This PR fixes the two points above by rearranging test fragments to have a finer granularity around the question of creation vs mutation, and by providing the previous ISA version where possible so we can check it changed.
This is part of the effort on #975
> [uss_qualifier] don't document version update check when it never happens

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validation.py
A documented check was not tested, likely because an omission during the implementation of the `isa_validation` scenario.
Part of #975
> [uss_qualifier] isa_validation now also checks extends validity

- monitoring/mock_uss/f3548v21/routes_scd.py
In support of #987, this PR implements makeUssReport in mock_uss by logging the report with the standard logger.
> [mock_uss/scd] Implement F3548 makeUssReport in mock_uss

- monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/test_steps/validate_notification_received.md
- monitoring/uss_qualifier/scenarios/astm/utm/subscription_notifications/test_steps/validate_notification_received.py
- monitoring/uss_qualifier/scenarios/interuss/mock_uss/test_steps.py
This PR reworks the test step fragment validate_notification_received and should address #994.
We don't consider anymore cases where the mock USS sends an invalid notification. This appears unnecessary since the mock USS is a piece of code instrumented by the USS qualifier: if it does not behave as we expect it is a bug that we must fix and we cannot anymore assume state of the USS. This also reduces complexity significantly.
- Pass check *Mock USS sends valid notification* to critical and return from code when an invalid mock USS behavior is detected (no notif, too many notif, invalid notif)
- Remove unneeded try/catch of `ValueError` and corresponding failure 
- Replace `_check_notification_sent_with_subscription_id_and_response` by a new interaction filter `notif_sub_id_filter`
- …
> [uss_qualifier/utm/sub_notif] Rework validate_notification_received test step fragment

- monitoring/uss_qualifier/configurations/dev/utm_implementation_us_lib/baseline.libsonnet
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss_equal_priority_not_permitted.py
Requirement for scope `utm.conformance_monitoring_sa` was added in `DownUSS`, however this is required only in `DownUSSEqualPriorityNotPermitted` which inherits from `DownUSS`.
This PR removes the requirement for scope `utm.conformance_monitoring_sa` in `DownUSS` but keep it in `DownUSSEqualPriorityNotPermitted`.
See https://github.com/interuss/monitoring/issues/991#issuecomment-2742983899
> [uss_qualifier/utm/down_uss] Contain requirement of utm.conformance_monitoring_sa scope to DownUSSEqualPriorityNotPermitted

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator_test.py
This PR does add UAS ID checks units test, and fix two minor typos found during development of thoses tests.
I tired to reuse as much as possible existing generic tests helpers, with some workarounds.
> [uss_qualifier/common_dict_eval] Add UAS ID checks tests

- .github/workflows/ci.yml
Adds the `force_orphan` option, which should cause the `gh-pages` branch to only have a single commit with the current published site, according to the [documentation](https://github.com/peaceiris/actions-gh-pages?tab=readme-ov-file#%EF%B8%8F-force-orphan-force_orphan) of the plugin.
This is a first attempt to solve #1002
> [ci] don't keep gh-pages history

- monitoring/monitorlib/rid_automated_testing/injection_api.py
- monitoring/uss_qualifier/resources/netrid/flight_data_resources.py
This PR partially addresses #1003 by fixing the UAS ID Field duplication in the `TestFlight` class, meaning it will be fixed when injecting a flight and when getting data from an injected flight.
A small typo has been fixed in checks, and a side small fix of `filter_invalid_telemetry` passed to the parent class has been done.
> [monitorlib/rid injection] Enforce and fix UAS ID at TestFlight level

- monitoring/uss_qualifier/scenarios/README.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/put_isa.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/sp_notification_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/put_isa.md
- monitoring/uss_qualifier/scenarios/astm/utm/data_exchange_validation/test_steps/validate_no_notification_operational_intent.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.md
- monitoring/uss_qualifier/scenarios/flight_planning/modify_activated_flight_intent.md
Low-severity findings are conceptually in a separate category from higher-severity findings since medium+ severity findings indicate some kind of compliance failure whereas low-severity findings do not indicate a failure to comply.  This PR attempts to clarify the situation by replacing mentions of "failing a low severity check" or similar with "producing a low-severity finding" since these findings are not actually failures.
The severity of the "Validate tested USS intersection algorithm check" is upgraded to medium since if the check failed (it can't actually fail as currently implemented; it can only be skipped since we can't differentiate between failure an inapplicability) it would indicate failure to comply with a requirement.
The severity of the "Mock USS interaction can be parsed …
> [uss_qualifier/docs] Clarify wording around low-severity findings

- monitoring/uss_qualifier/suites/astm/utm/f3548_21.yaml
This PR should resolve #903.  Unfortunately, it will also be too tolerant of a failure to clear the airspace (continuing with the suite even when the airspace couldn't be cleared) -- ideally, in that case, we should actually abort the test suite.  So, with our current feature set, I believe we will be wrong one of two ways: either we don't abort when the airspace was not cleared successfully, or we abort when the airspace was actually clear even though a particular USS failed to execute the clear instruction.  Given that the latter is causing our customers more trouble right now (#903), I think it's better to err in the former way rather than the latter.  This PR makes that change.
In the future, we could add a feature that avoids being wrong both ways by making the abort criteria more …
> [uss_qualifier/F3548] Make flight planner preparation best-effort

- monitoring/uss_qualifier/reports/templates/tested_requirements/participant_tested_requirements.html
- monitoring/uss_qualifier/reports/tested_requirements/breakdown.py
- monitoring/uss_qualifier/reports/tested_requirements/data_types.py
- monitoring/uss_qualifier/reports/tested_requirements/summaries.py
Currently, a low-severity finding (not a failure to comply with a requirement) will be summarized in the tested requirements artifact as Fail.  This PR fixes that situation by communicating the findings information while also correctly representing Pass as the overall status.
> [uss_qualifier/reports] Fix tested requirements representation of low-severity findings

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/subscription_simple.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/op_intent_ref_key_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_simple.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/constraint_ref_synchronization.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/subscription_synchronization.py
For some reason the assumption that scenario instances are reused has crept into multiples places.
Such reuse would in fact be a bug, so we can drop the assumption (and fix the bug if it ever appears)
Fixes #1022
> [uss_qualifier] expunge assumption of scenario re-use

- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/crud/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/oir_has_no_subscription.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_explicit_sub_handling.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_explicit_sub_handling.py
Extend `OIRSimple` with a test case that:
- checks we can create a subscription-free OIR
- then checks an explicit subscription can be attached, and that the subscription needs to cover the OIR.
This covers point (4) on https://github.com/interuss/dss/issues/1088
Note: this builds on top of #1012, only the last commit of this PR is relevant.
> [uss_qualifier] oir_simple: check oir can be created without sub and attached to explicit sub

- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_explicit_sub_handling.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_explicit_sub_handling.py
Extend OIRSimple to check that an OIR in the accepted state can be detached from an explicit subscription and left without subscription.
This covers scenario (5) from https://github.com/interuss/dss/issues/1088
Note: this builds on top of #804, only the last commit of this PR is relevant
> [uss_qualifier] oir_simple: accepted oir can be detached from explicit subscription

- monitoring/monitorlib/auth.py
This is to support values that contain `=` as part of their string. We ran into an issue where a client_secret value contained an `=` sign and it was not possible to get the test runner working with that secret. This change will make it so that the split occurs only on the first `=` and will ignore the ones in the value. It'll force a user to enter the params using key args but at least that path will work.
> Update the way key value parameters on auth adapter are parsed

- .github/workflows/ci.yml
- .github/workflows/monitoring-test.yml
- monitoring/uss_qualifier/fileio.py
- monitoring/uss_qualifier/run_locally.sh
uss_qualifier has the capability to access private GitHub repos when provided with one or more access tokens to do so via the GITHUB_PRIVATE_REPOS environment variable.  However, currently run_locally.sh produces an error when GITHUB_PRIVATE_REPOS is not provided because it is set to an empty value rather than being left unset.  This PR addresses that problem in two ways: first, it doesn't set the environment variable in the docker container when it isn't provided/present, and second, empty GITHUB_PRIVATE_REPOS values are ignored.
> [uss_qualifier] Fix private repos locally

- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/__init__.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_explicit_sub_handling.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.py
Cover the case where we attach an existing and valid implicit subscription to an OIR that is currently not attached to any subscription. 
This covers scenario (2) from https://github.com/interuss/dss/issues/1088
> [uss_qualifier] expand OIR implicit sub handling scenario

- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/oir_implicit_sub_handling.py
This covers the last scenario in https://github.com/interuss/dss/issues/1088
> [uss_qualifier] oir implicit sub scenario: oir with no subscription mutated to get implicit sub

- monitoring/uss_qualifier/configurations/dev/uspace.yaml
Add `NET0470,Table1,1` to uspace tests
Partially fix #857
> [uss_qualifier] Fix requierement collection of uspace test to check for UAS ID as well

- monitoring/uss_qualifier/scenarios/astm/netrid/common/sp_operator_notify_missing_fields.py
Partial fix for #1042, disable injection of empty-timestamp telemetry data
> [monitorlib/rid injection] Don't inject telemetry without timestamp

- monitoring/uss_qualifier/scenarios/astm/netrid/injection.py
> [uss_qualifier/netrid/injection:inject_flights] Allow undefined timestamps in injected telemetry returned by USS

- monitoring/uss_qualifier/scenarios/astm/netrid/common/sp_notification_behavior.py
- monitoring/uss_qualifier/scenarios/astm/netrid/injection.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/sp_notification_behavior.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/sp_notification_behavior.md
Remove redundant check, and wait for the acceptable notification delivery time before declaring that notifications have not been delivered.
The PR adds some retry logic, so we don't need to wait for the full 3 seconds in situations where notifications arrive earlier.
The PR also adds a duration field to the `InjectedFlight` class.
Should fix #1043
> [uss_qualifier] sp notifications: wait for permissible delay before requesting notifications

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
Ground work for addressing #857
> [uss_qualifier/netrid/common_dictionary_evaluator] Add to generic evaluator optional ability to skip evaluation; factor away 'dotted_get'

- monitoring/uss_qualifier/configurations/dev/netrid_v19.yaml
- monitoring/uss_qualifier/configurations/dev/netrid_v22a.yaml
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss_interoperability.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss_interoperability.md
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_19/dss_probing.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a.yaml
- monitoring/uss_qualifier/suites/astm/netrid/f3411_22a/dss_probing.yaml
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.yaml
- monitoring/uss_qualifier/suites/uspace/network_identification.yaml
- monitoring/uss_qualifier/suites/uspace/required_services.yaml
Replace the hardcoded vertices with a PlanningAreaResource in `DSSInteroperability`, so the area used for testing can be configured.
Fixes #843
all configurations that specify a `DSSInteroperability` scenario now need to provide a `PlanningAreaResource`. This resource is newly available as a general `resource`, and any existing `PlanningAreaResource` defined in the context of SCD/F3548 scenarios should be directly reusable in most situations.
> [uss_qualifier] netrid: DSSInteroperability scenario gets configurable area

- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/sync_fields.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/sync_get.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/cr/sync_search.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/sync_fields.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/sync_get.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/sync_search.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/constraint_ref_synchronization.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/op_intent_ref_synchronization.md
OIR and CR synchronization scenarios check that entities are properly synchronized via direct access as well as via search (which additionally allows to check if the area of an entity is synchronized).
These checks happen in distinct steps which currently still reference the same documentation fragment, which leads to the situation we'd like to avoid that is described in #975.
This PR splits the `sync.md` fragment into fragments that respectively handle the direct query and the search, so no "documented but not tested" check is present in the reports for the relevant checks.
Progress on #975
> [uss_qualifier] CR/OIR sync: cleanup search/get-specific checks

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/isa_validation.py
Found this one by perusing the logs while doing unrelated cleanups.
> [uss_qualifier] NetRID: add missing query attribution in isa_validation

- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss_interoperability.py
- monitoring/uss_qualifier/scenarios/astm/netrid/dss_wrapper.py
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/heavy_traffic_concurrent.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v19/dss/test_steps/put_isa.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/heavy_traffic_concurrent.md
- monitoring/uss_qualifier/scenarios/astm/netrid/v22a/dss/test_steps/put_isa.md
Progress on #975 for NetRID scenarios
Note that the removed `ISA version changed` checks were incorrectly present in the `put` fragment, and were already present in the `mutate` fragment (which is their intended home)
> [uss_qualifier] implement missing checks or cleanup relevant documentation for some ISA scenarios

- .github/workflows/image-publish.yml
- build/build_and_push.sh
- monitoring/README.md
Closes #1058 
This adds to the docker image built in the CI and pushed to Docker Hub a signature using sigstore.
The identity of the GitHub Actions CI workflow is used to perform the "keyless" signing.
This follows the exact same approach as https://github.com/interuss/dss/pull/1226
> [CI] Sign published images with cosign

- monitoring/loadtest/locust_files/ISA.py
Rid module has been removed in https://github.com/interuss/monitoring/commit/d49267437325a47e0e329ebf240e271a0e035e51, this just copy-paste the `VERTICES` to make loadtest working again.
Follow #1083
>  [loadtest] Fix missing import 

- monitoring/uss_qualifier/scenarios/astm/netrid/common_dictionary_evaluator.py
- monitoring/uss_qualifier/scenarios/scenario_test/utils.py
- test/isort/pyproject.toml
- test/isort/uv.lock
* Remove constrain about isort version ([UV take care of that for us](https://docs.astral.sh/uv/concepts/projects/sync/#upgrading-locked-package-versions))
* Upgrade to latest version
* Run isort (2 import changed)
>  [tooling] Upgrade isort to latest version 

- monitoring/mock_uss/flight_planning/routes.py
- monitoring/mock_uss/scd_injection/routes_injection.py
This PR contrib to #1100 , fixing point 3.
It make the delete flight call of mock_uss return proper status code.
No fix in tests seems to be needed (as the core problem is the absence of body in the response, not the status code).
> [mock_uss] Return correct status code on flight deletion

- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
Contrib to #1100 , point 4
This make the uss_qualifier to record notes about unexpected states when doing flight cleanup.
Until #1105 is merged, this will probably add some log, but none are to be expected after the other PR is merged.
This doesn't make a failing cleanup an error, should we want that (I would think that too 'strict'), #1105 will be needed first :)
> [uss_qualifier] Record unexpected responses when cleanuping flights

- monitoring/monitorlib/clients/flight_planning/client_v1.py
- monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py
This PR contrib to #1100 , point 1
It change try_end_flight behavior by ignoring wrong responses when the status code of the query is not 200.
In such cases, the response will have a limited field available. It's up to the caller to handle such cases.
The code base already handle this situation correctly, by ignoring 404 errors when doing wild cleanup: https://github.com/interuss/monitoring/blob/main/monitoring/uss_qualifier/scenarios/flight_planning/test_steps.py#L424
We don't have a rogue-dss implementation / tests, so I tested locally the new behavior with a special mock uss:
- When returning empty 404 on unknown flights, the test suite pass
- When always returning 404 on any flight delete, the test suite fail (as wanted, since we want to ensure deletion in such case).
Another test for …
> [monitorlib/flight_planning] Ignore wrong body on non-200 responses when a flight is deleted

- monitoring/monitorlib/fetch/__init__.py
- monitoring/monitorlib/infrastructure.py
- monitoring/uss_qualifier/scenarios/astm/netrid/common/dss/heavy_traffic_concurrent.py
This is a fix for #1078, which should allow uss_qualifier to proceed without crashing out when mime-type errors occur, while keeping around request details for possible troubleshooting.
> [uss_qualifier] NetRID heavy traffic concurrent: handle concurrent query exceptions 

- Makefile
This PR improves general compatibility & usability of the interuss/monitoring repository by:
- adding `venv` to .dockerignore, for any one using a local virtualenv that might live in `venv`
- replaces `sha256sum` (absent from OS X) with `sha -a 256`, which should work on both OS X and most linux environments 
- excluding `venv` and `.venv` from the `basedpyright` configuration (otherwise they get picked up and linted, which is both useless AND hellishly slow)
@the-glu you may want to confirm I'm not breaking any of your intentions here! :)
> [local-env] improve compatibility with different local dev environments

- NEXT_RELEASE_NOTES.md
- RELEASE.md
This PR updates NEXT_RELEASE_NOTES after the v0.18.0 and also takes the opportunity to clarify and expand documentation around releases.
> [docs] Update release documentation following v0.18.0 release

- .basedpyright/baseline.json
- monitoring/monitorlib/fetch/scd.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/oir/verify_clean_secondary_workspace.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/fragments/sub/verify_clean_secondary_workspace.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/subscription_interactions.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
- monitoring/uss_qualifier/scenarios/scenario.py
- monitoring/uss_qualifier/suites/astm/utm/dss_probing.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/astm/utm/prod_probe.md
- monitoring/uss_qualifier/suites/astm/utm/prod_probe_suite1.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/interuss/dss/all_tests.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This PR is a step in service of #810. It also introduces new Exceptions so as to follow what is outlined in #1130
> [uss_qualifier] subscription_interactions: verify secondary DSS instances are clean

- monitoring/uss_qualifier/resources/astm/f3548/v21/dss.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/authentication/authentication_validation.py
- monitoring/uss_qualifier/scenarios/astm/utm/dss/synchronization/uss_availability_synchronization.py
- monitoring/uss_qualifier/scenarios/astm/utm/off_nominal_planning/down_uss.py
- monitoring/uss_qualifier/scenarios/astm/utm/test_steps.py
`get_uss_availability` returns the `UssAvailabilityStatusResponse` containing the USS availability defined as `UssAvailabilityState`.
It would increase consistency to reuse this enum type in `set_uss_availability` instead of the more generic `bool | None` when updating the USS availability.
> [uss_qualifier] use UssAvailabilityState in dss api

- .basedpyright/baseline.json
- monitoring/mock_uss/f3548v21/flight_planning.py
- monitoring/mock_uss/scd_injection/routes_injection.py
- monitoring/uss_qualifier/configurations/dev/f3548_self_contained.yaml
- monitoring/uss_qualifier/scenarios/astm/utm/check_for_conflict_notification.md
- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_equal_priority_not_permitted/conflict_equal_priority_not_permitted.py
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
- monitoring/uss_qualifier/scenarios/astm/utm/notifications_to_operator/notification_checker.py
- monitoring/uss_qualifier/scenarios/astm/utm/record_current_notification.md
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
Follow #1155 
Implements https://github.com/interuss/monitoring/issues/1144
Add SCD0090 checks.
>  [utm] Add SCD0090 checks 

- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.md
- monitoring/uss_qualifier/scenarios/astm/utm/nominal_planning/conflict_higher_priority/conflict_higher_priority.py
- monitoring/uss_qualifier/scenarios/astm/utm/notifications_to_operator/notification_checker.py
- monitoring/uss_qualifier/suites/astm/utm/f3548_21.md
- monitoring/uss_qualifier/suites/faa/uft/message_signing.md
- monitoring/uss_qualifier/suites/uspace/flight_auth.md
- monitoring/uss_qualifier/suites/uspace/required_services.md
This PR primarily enhances SCD0090 and SCD0095 testing by checking pre-existing notifications before the flight planning action so that those notifications can be definitively excluded as notifications that may have been triggered by the flight planning action.  This makes it possible to incorporate more robust behavior in the presence of clock skew between uss_qualifier and USSs under test (previously, clock skew could have caused by false positives and false negatives).  Finally, a bug observed in the wild is fixed for a timing edge case (where `new_notifications` wasn't populated with all clients under certain conditions).
> [uss_qualifier] Examine pre-existing notifications for SCD0090/95

- monitoring/uss_qualifier/scenarios/astm/utm/dss/test_step_fragments.py
Follow-up from https://github.com/interuss/monitoring/pull/1164#discussion_r2353346064
Raise `ScenarioDidNotStopError` instead of ruturning default value in `get_uss_availability` and `set_uss_availability` fragments
> [uss_qualifier] raise ScenarioDidNotStopError in fragments
